// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: models/user/auth.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stored in Firestore collection `ingress_api_keys/{hash}`
type ApiKeyRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyRecord) Reset() {
	*x = ApiKeyRecord{}
	mi := &file_models_user_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyRecord) ProtoMessage() {}

func (x *ApiKeyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyRecord.ProtoReflect.Descriptor instead.
func (*ApiKeyRecord) Descriptor() ([]byte, []int) {
	return file_models_user_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ApiKeyRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ApiKeyRecord) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ApiKeyRecord) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ApiKeyRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApiKeyRecord) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

// Stored in Firestore collection `integrations/{provider}/ids/{external_id}`
type IntegrationIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationIdentity) Reset() {
	*x = IntegrationIdentity{}
	mi := &file_models_user_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationIdentity) ProtoMessage() {}

func (x *IntegrationIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationIdentity.ProtoReflect.Descriptor instead.
func (*IntegrationIdentity) Descriptor() ([]byte, []int) {
	return file_models_user_auth_proto_rawDescGZIP(), []int{1}
}

func (x *IntegrationIdentity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IntegrationIdentity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_models_user_auth_proto protoreflect.FileDescriptor

const file_models_user_auth_proto_rawDesc = "" +
	"\n" +
	"\x16models/user/auth.proto\x12\x13fitglue.models.user\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n" +
	"\fApiKeyRecord\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"i\n" +
	"\x13IntegrationIdentity\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB;Z9github.com/fitglue/server/src/go/pkg/types/pb/models/userb\x06proto3"

var (
	file_models_user_auth_proto_rawDescOnce sync.Once
	file_models_user_auth_proto_rawDescData []byte
)

func file_models_user_auth_proto_rawDescGZIP() []byte {
	file_models_user_auth_proto_rawDescOnce.Do(func() {
		file_models_user_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_user_auth_proto_rawDesc), len(file_models_user_auth_proto_rawDesc)))
	})
	return file_models_user_auth_proto_rawDescData
}

var file_models_user_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_user_auth_proto_goTypes = []any{
	(*ApiKeyRecord)(nil),          // 0: fitglue.models.user.ApiKeyRecord
	(*IntegrationIdentity)(nil),   // 1: fitglue.models.user.IntegrationIdentity
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_models_user_auth_proto_depIdxs = []int32{
	2, // 0: fitglue.models.user.ApiKeyRecord.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: fitglue.models.user.ApiKeyRecord.last_used_at:type_name -> google.protobuf.Timestamp
	2, // 2: fitglue.models.user.IntegrationIdentity.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_models_user_auth_proto_init() }
func file_models_user_auth_proto_init() {
	if File_models_user_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_user_auth_proto_rawDesc), len(file_models_user_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_user_auth_proto_goTypes,
		DependencyIndexes: file_models_user_auth_proto_depIdxs,
		MessageInfos:      file_models_user_auth_proto_msgTypes,
	}.Build()
	File_models_user_auth_proto = out.File
	file_models_user_auth_proto_goTypes = nil
	file_models_user_auth_proto_depIdxs = nil
}
