// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: models/user/integration.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserIntegrations represents all connected third-party providers.
type UserIntegrations struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Hevy          *HevyIntegration          `protobuf:"bytes,1,opt,name=hevy,proto3" json:"hevy,omitempty"`
	Fitbit        *FitbitIntegration        `protobuf:"bytes,2,opt,name=fitbit,proto3" json:"fitbit,omitempty"`
	Strava        *StravaIntegration        `protobuf:"bytes,3,opt,name=strava,proto3" json:"strava,omitempty"`
	Mock          *MockIntegration          `protobuf:"bytes,4,opt,name=mock,proto3" json:"mock,omitempty"`
	Parkrun       *ParkrunIntegration       `protobuf:"bytes,5,opt,name=parkrun,proto3" json:"parkrun,omitempty"`
	Spotify       *SpotifyIntegration       `protobuf:"bytes,6,opt,name=spotify,proto3" json:"spotify,omitempty"`
	Trainingpeaks *TrainingPeaksIntegration `protobuf:"bytes,7,opt,name=trainingpeaks,proto3" json:"trainingpeaks,omitempty"`
	Intervals     *IntervalsIntegration     `protobuf:"bytes,8,opt,name=intervals,proto3" json:"intervals,omitempty"`
	Google        *GoogleIntegration        `protobuf:"bytes,9,opt,name=google,proto3" json:"google,omitempty"`
	Oura          *OuraIntegration          `protobuf:"bytes,10,opt,name=oura,proto3" json:"oura,omitempty"`
	Polar         *PolarIntegration         `protobuf:"bytes,11,opt,name=polar,proto3" json:"polar,omitempty"`
	Wahoo         *WahooIntegration         `protobuf:"bytes,12,opt,name=wahoo,proto3" json:"wahoo,omitempty"`
	Github        *GitHubIntegration        `protobuf:"bytes,13,opt,name=github,proto3" json:"github,omitempty"`
	AppleHealth   *AppleHealthIntegration   `protobuf:"bytes,14,opt,name=apple_health,json=appleHealth,proto3" json:"apple_health,omitempty"`
	HealthConnect *HealthConnectIntegration `protobuf:"bytes,15,opt,name=health_connect,json=healthConnect,proto3" json:"health_connect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIntegrations) Reset() {
	*x = UserIntegrations{}
	mi := &file_models_user_integration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIntegrations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIntegrations) ProtoMessage() {}

func (x *UserIntegrations) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIntegrations.ProtoReflect.Descriptor instead.
func (*UserIntegrations) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{0}
}

func (x *UserIntegrations) GetHevy() *HevyIntegration {
	if x != nil {
		return x.Hevy
	}
	return nil
}

func (x *UserIntegrations) GetFitbit() *FitbitIntegration {
	if x != nil {
		return x.Fitbit
	}
	return nil
}

func (x *UserIntegrations) GetStrava() *StravaIntegration {
	if x != nil {
		return x.Strava
	}
	return nil
}

func (x *UserIntegrations) GetMock() *MockIntegration {
	if x != nil {
		return x.Mock
	}
	return nil
}

func (x *UserIntegrations) GetParkrun() *ParkrunIntegration {
	if x != nil {
		return x.Parkrun
	}
	return nil
}

func (x *UserIntegrations) GetSpotify() *SpotifyIntegration {
	if x != nil {
		return x.Spotify
	}
	return nil
}

func (x *UserIntegrations) GetTrainingpeaks() *TrainingPeaksIntegration {
	if x != nil {
		return x.Trainingpeaks
	}
	return nil
}

func (x *UserIntegrations) GetIntervals() *IntervalsIntegration {
	if x != nil {
		return x.Intervals
	}
	return nil
}

func (x *UserIntegrations) GetGoogle() *GoogleIntegration {
	if x != nil {
		return x.Google
	}
	return nil
}

func (x *UserIntegrations) GetOura() *OuraIntegration {
	if x != nil {
		return x.Oura
	}
	return nil
}

func (x *UserIntegrations) GetPolar() *PolarIntegration {
	if x != nil {
		return x.Polar
	}
	return nil
}

func (x *UserIntegrations) GetWahoo() *WahooIntegration {
	if x != nil {
		return x.Wahoo
	}
	return nil
}

func (x *UserIntegrations) GetGithub() *GitHubIntegration {
	if x != nil {
		return x.Github
	}
	return nil
}

func (x *UserIntegrations) GetAppleHealth() *AppleHealthIntegration {
	if x != nil {
		return x.AppleHealth
	}
	return nil
}

func (x *UserIntegrations) GetHealthConnect() *HealthConnectIntegration {
	if x != nil {
		return x.HealthConnect
	}
	return nil
}

type MockIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockIntegration) Reset() {
	*x = MockIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockIntegration) ProtoMessage() {}

func (x *MockIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockIntegration.ProtoReflect.Descriptor instead.
func (*MockIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{1}
}

func (x *MockIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MockIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MockIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type HevyIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HevyIntegration) Reset() {
	*x = HevyIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HevyIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HevyIntegration) ProtoMessage() {}

func (x *HevyIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HevyIntegration.ProtoReflect.Descriptor instead.
func (*HevyIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{2}
}

func (x *HevyIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HevyIntegration) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *HevyIntegration) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HevyIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *HevyIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type FitbitIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	FitbitUserId  string                 `protobuf:"bytes,5,opt,name=fitbit_user_id,json=fitbitUserId,proto3" json:"fitbit_user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FitbitIntegration) Reset() {
	*x = FitbitIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FitbitIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FitbitIntegration) ProtoMessage() {}

func (x *FitbitIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FitbitIntegration.ProtoReflect.Descriptor instead.
func (*FitbitIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{3}
}

func (x *FitbitIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FitbitIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *FitbitIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *FitbitIntegration) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *FitbitIntegration) GetFitbitUserId() string {
	if x != nil {
		return x.FitbitUserId
	}
	return ""
}

func (x *FitbitIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FitbitIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type StravaIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AthleteId     int64                  `protobuf:"varint,5,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StravaIntegration) Reset() {
	*x = StravaIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StravaIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StravaIntegration) ProtoMessage() {}

func (x *StravaIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StravaIntegration.ProtoReflect.Descriptor instead.
func (*StravaIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{4}
}

func (x *StravaIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StravaIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *StravaIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *StravaIntegration) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *StravaIntegration) GetAthleteId() int64 {
	if x != nil {
		return x.AthleteId
	}
	return 0
}

func (x *StravaIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StravaIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type ParkrunIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AthleteId     string                 `protobuf:"bytes,2,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	CountryUrl    string                 `protobuf:"bytes,3,opt,name=country_url,json=countryUrl,proto3" json:"country_url,omitempty"`
	ConsentGiven  bool                   `protobuf:"varint,4,opt,name=consent_given,json=consentGiven,proto3" json:"consent_given,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkrunIntegration) Reset() {
	*x = ParkrunIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkrunIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkrunIntegration) ProtoMessage() {}

func (x *ParkrunIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkrunIntegration.ProtoReflect.Descriptor instead.
func (*ParkrunIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{5}
}

func (x *ParkrunIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ParkrunIntegration) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *ParkrunIntegration) GetCountryUrl() string {
	if x != nil {
		return x.CountryUrl
	}
	return ""
}

func (x *ParkrunIntegration) GetConsentGiven() bool {
	if x != nil {
		return x.ConsentGiven
	}
	return false
}

func (x *ParkrunIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ParkrunIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type SpotifyIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SpotifyUserId string                 `protobuf:"bytes,5,opt,name=spotify_user_id,json=spotifyUserId,proto3" json:"spotify_user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpotifyIntegration) Reset() {
	*x = SpotifyIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpotifyIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotifyIntegration) ProtoMessage() {}

func (x *SpotifyIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotifyIntegration.ProtoReflect.Descriptor instead.
func (*SpotifyIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{6}
}

func (x *SpotifyIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SpotifyIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SpotifyIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SpotifyIntegration) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SpotifyIntegration) GetSpotifyUserId() string {
	if x != nil {
		return x.SpotifyUserId
	}
	return ""
}

func (x *SpotifyIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SpotifyIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type TrainingPeaksIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AthleteId     string                 `protobuf:"bytes,5,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingPeaksIntegration) Reset() {
	*x = TrainingPeaksIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingPeaksIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingPeaksIntegration) ProtoMessage() {}

func (x *TrainingPeaksIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingPeaksIntegration.ProtoReflect.Descriptor instead.
func (*TrainingPeaksIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{7}
}

func (x *TrainingPeaksIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TrainingPeaksIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TrainingPeaksIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TrainingPeaksIntegration) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TrainingPeaksIntegration) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *TrainingPeaksIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TrainingPeaksIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type IntervalsIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	AthleteId     string                 `protobuf:"bytes,3,opt,name=athlete_id,json=athleteId,proto3" json:"athlete_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntervalsIntegration) Reset() {
	*x = IntervalsIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntervalsIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntervalsIntegration) ProtoMessage() {}

func (x *IntervalsIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntervalsIntegration.ProtoReflect.Descriptor instead.
func (*IntervalsIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{8}
}

func (x *IntervalsIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *IntervalsIntegration) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *IntervalsIntegration) GetAthleteId() string {
	if x != nil {
		return x.AthleteId
	}
	return ""
}

func (x *IntervalsIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *IntervalsIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type OuraIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	OuraUserId    string                 `protobuf:"bytes,5,opt,name=oura_user_id,json=ouraUserId,proto3" json:"oura_user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OuraIntegration) Reset() {
	*x = OuraIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OuraIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OuraIntegration) ProtoMessage() {}

func (x *OuraIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OuraIntegration.ProtoReflect.Descriptor instead.
func (*OuraIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{9}
}

func (x *OuraIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OuraIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OuraIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OuraIntegration) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *OuraIntegration) GetOuraUserId() string {
	if x != nil {
		return x.OuraUserId
	}
	return ""
}

func (x *OuraIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OuraIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type GoogleIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	GoogleUserId  string                 `protobuf:"bytes,5,opt,name=google_user_id,json=googleUserId,proto3" json:"google_user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleIntegration) Reset() {
	*x = GoogleIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleIntegration) ProtoMessage() {}

func (x *GoogleIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleIntegration.ProtoReflect.Descriptor instead.
func (*GoogleIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{10}
}

func (x *GoogleIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GoogleIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GoogleIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GoogleIntegration) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GoogleIntegration) GetGoogleUserId() string {
	if x != nil {
		return x.GoogleUserId
	}
	return ""
}

func (x *GoogleIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GoogleIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type PolarIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	PolarUserId   string                 `protobuf:"bytes,5,opt,name=polar_user_id,json=polarUserId,proto3" json:"polar_user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolarIntegration) Reset() {
	*x = PolarIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolarIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolarIntegration) ProtoMessage() {}

func (x *PolarIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolarIntegration.ProtoReflect.Descriptor instead.
func (*PolarIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{11}
}

func (x *PolarIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PolarIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *PolarIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *PolarIntegration) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *PolarIntegration) GetPolarUserId() string {
	if x != nil {
		return x.PolarUserId
	}
	return ""
}

func (x *PolarIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PolarIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type WahooIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	WahooUserId   string                 `protobuf:"bytes,5,opt,name=wahoo_user_id,json=wahooUserId,proto3" json:"wahoo_user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WahooIntegration) Reset() {
	*x = WahooIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WahooIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WahooIntegration) ProtoMessage() {}

func (x *WahooIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WahooIntegration.ProtoReflect.Descriptor instead.
func (*WahooIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{12}
}

func (x *WahooIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WahooIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *WahooIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *WahooIntegration) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *WahooIntegration) GetWahooUserId() string {
	if x != nil {
		return x.WahooUserId
	}
	return ""
}

func (x *WahooIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WahooIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type GitHubIntegration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AccessToken    string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken   string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	GithubUserId   string                 `protobuf:"bytes,5,opt,name=github_user_id,json=githubUserId,proto3" json:"github_user_id,omitempty"`
	GithubUsername string                 `protobuf:"bytes,6,opt,name=github_username,json=githubUsername,proto3" json:"github_username,omitempty"`
	Scope          string                 `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GitHubIntegration) Reset() {
	*x = GitHubIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubIntegration) ProtoMessage() {}

func (x *GitHubIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubIntegration.ProtoReflect.Descriptor instead.
func (*GitHubIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{13}
}

func (x *GitHubIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GitHubIntegration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GitHubIntegration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GitHubIntegration) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GitHubIntegration) GetGithubUserId() string {
	if x != nil {
		return x.GithubUserId
	}
	return ""
}

func (x *GitHubIntegration) GetGithubUsername() string {
	if x != nil {
		return x.GithubUsername
	}
	return ""
}

func (x *GitHubIntegration) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GitHubIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GitHubIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type AppleHealthIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppleHealthIntegration) Reset() {
	*x = AppleHealthIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppleHealthIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppleHealthIntegration) ProtoMessage() {}

func (x *AppleHealthIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppleHealthIntegration.ProtoReflect.Descriptor instead.
func (*AppleHealthIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{14}
}

func (x *AppleHealthIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AppleHealthIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AppleHealthIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type HealthConnectIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthConnectIntegration) Reset() {
	*x = HealthConnectIntegration{}
	mi := &file_models_user_integration_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthConnectIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthConnectIntegration) ProtoMessage() {}

func (x *HealthConnectIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_integration_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthConnectIntegration.ProtoReflect.Descriptor instead.
func (*HealthConnectIntegration) Descriptor() ([]byte, []int) {
	return file_models_user_integration_proto_rawDescGZIP(), []int{15}
}

func (x *HealthConnectIntegration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HealthConnectIntegration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *HealthConnectIntegration) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

var File_models_user_integration_proto protoreflect.FileDescriptor

const file_models_user_integration_proto_rawDesc = "" +
	"\n" +
	"\x1dmodels/user/integration.proto\x12\x13fitglue.models.user\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\b\n" +
	"\x10UserIntegrations\x128\n" +
	"\x04hevy\x18\x01 \x01(\v2$.fitglue.models.user.HevyIntegrationR\x04hevy\x12>\n" +
	"\x06fitbit\x18\x02 \x01(\v2&.fitglue.models.user.FitbitIntegrationR\x06fitbit\x12>\n" +
	"\x06strava\x18\x03 \x01(\v2&.fitglue.models.user.StravaIntegrationR\x06strava\x128\n" +
	"\x04mock\x18\x04 \x01(\v2$.fitglue.models.user.MockIntegrationR\x04mock\x12A\n" +
	"\aparkrun\x18\x05 \x01(\v2'.fitglue.models.user.ParkrunIntegrationR\aparkrun\x12A\n" +
	"\aspotify\x18\x06 \x01(\v2'.fitglue.models.user.SpotifyIntegrationR\aspotify\x12S\n" +
	"\rtrainingpeaks\x18\a \x01(\v2-.fitglue.models.user.TrainingPeaksIntegrationR\rtrainingpeaks\x12G\n" +
	"\tintervals\x18\b \x01(\v2).fitglue.models.user.IntervalsIntegrationR\tintervals\x12>\n" +
	"\x06google\x18\t \x01(\v2&.fitglue.models.user.GoogleIntegrationR\x06google\x128\n" +
	"\x04oura\x18\n" +
	" \x01(\v2$.fitglue.models.user.OuraIntegrationR\x04oura\x12;\n" +
	"\x05polar\x18\v \x01(\v2%.fitglue.models.user.PolarIntegrationR\x05polar\x12;\n" +
	"\x05wahoo\x18\f \x01(\v2%.fitglue.models.user.WahooIntegrationR\x05wahoo\x12>\n" +
	"\x06github\x18\r \x01(\v2&.fitglue.models.user.GitHubIntegrationR\x06github\x12N\n" +
	"\fapple_health\x18\x0e \x01(\v2+.fitglue.models.user.AppleHealthIntegrationR\vappleHealth\x12T\n" +
	"\x0ehealth_connect\x18\x0f \x01(\v2-.fitglue.models.user.HealthConnectIntegrationR\rhealthConnect\"\xa4\x01\n" +
	"\x0fMockIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xd6\x01\n" +
	"\x0fHevyIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xcf\x02\n" +
	"\x11FitbitIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12$\n" +
	"\x0efitbit_user_id\x18\x05 \x01(\tR\ffitbitUserId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xc8\x02\n" +
	"\x11StravaIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x05 \x01(\x03R\tathleteId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\x8c\x02\n" +
	"\x12ParkrunIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x02 \x01(\tR\tathleteId\x12\x1f\n" +
	"\vcountry_url\x18\x03 \x01(\tR\n" +
	"countryUrl\x12#\n" +
	"\rconsent_given\x18\x04 \x01(\bR\fconsentGiven\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xd2\x02\n" +
	"\x12SpotifyIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12&\n" +
	"\x0fspotify_user_id\x18\x05 \x01(\tR\rspotifyUserId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xcf\x02\n" +
	"\x18TrainingPeaksIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x05 \x01(\tR\tathleteId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xe1\x01\n" +
	"\x14IntervalsIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"athlete_id\x18\x03 \x01(\tR\tathleteId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xc9\x02\n" +
	"\x0fOuraIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12 \n" +
	"\foura_user_id\x18\x05 \x01(\tR\n" +
	"ouraUserId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xcf\x02\n" +
	"\x11GoogleIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12$\n" +
	"\x0egoogle_user_id\x18\x05 \x01(\tR\fgoogleUserId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xcc\x02\n" +
	"\x10PolarIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\"\n" +
	"\rpolar_user_id\x18\x05 \x01(\tR\vpolarUserId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xcc\x02\n" +
	"\x10WahooIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\"\n" +
	"\rwahoo_user_id\x18\x05 \x01(\tR\vwahooUserId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\x8e\x03\n" +
	"\x11GitHubIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12$\n" +
	"\x0egithub_user_id\x18\x05 \x01(\tR\fgithubUserId\x12'\n" +
	"\x0fgithub_username\x18\x06 \x01(\tR\x0egithubUsername\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scope\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xab\x01\n" +
	"\x16AppleHealthIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\xad\x01\n" +
	"\x18HealthConnectIntegration\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAtB;Z9github.com/fitglue/server/src/go/pkg/types/pb/models/userb\x06proto3"

var (
	file_models_user_integration_proto_rawDescOnce sync.Once
	file_models_user_integration_proto_rawDescData []byte
)

func file_models_user_integration_proto_rawDescGZIP() []byte {
	file_models_user_integration_proto_rawDescOnce.Do(func() {
		file_models_user_integration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_user_integration_proto_rawDesc), len(file_models_user_integration_proto_rawDesc)))
	})
	return file_models_user_integration_proto_rawDescData
}

var file_models_user_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_models_user_integration_proto_goTypes = []any{
	(*UserIntegrations)(nil),         // 0: fitglue.models.user.UserIntegrations
	(*MockIntegration)(nil),          // 1: fitglue.models.user.MockIntegration
	(*HevyIntegration)(nil),          // 2: fitglue.models.user.HevyIntegration
	(*FitbitIntegration)(nil),        // 3: fitglue.models.user.FitbitIntegration
	(*StravaIntegration)(nil),        // 4: fitglue.models.user.StravaIntegration
	(*ParkrunIntegration)(nil),       // 5: fitglue.models.user.ParkrunIntegration
	(*SpotifyIntegration)(nil),       // 6: fitglue.models.user.SpotifyIntegration
	(*TrainingPeaksIntegration)(nil), // 7: fitglue.models.user.TrainingPeaksIntegration
	(*IntervalsIntegration)(nil),     // 8: fitglue.models.user.IntervalsIntegration
	(*OuraIntegration)(nil),          // 9: fitglue.models.user.OuraIntegration
	(*GoogleIntegration)(nil),        // 10: fitglue.models.user.GoogleIntegration
	(*PolarIntegration)(nil),         // 11: fitglue.models.user.PolarIntegration
	(*WahooIntegration)(nil),         // 12: fitglue.models.user.WahooIntegration
	(*GitHubIntegration)(nil),        // 13: fitglue.models.user.GitHubIntegration
	(*AppleHealthIntegration)(nil),   // 14: fitglue.models.user.AppleHealthIntegration
	(*HealthConnectIntegration)(nil), // 15: fitglue.models.user.HealthConnectIntegration
	(*timestamppb.Timestamp)(nil),    // 16: google.protobuf.Timestamp
}
var file_models_user_integration_proto_depIdxs = []int32{
	2,  // 0: fitglue.models.user.UserIntegrations.hevy:type_name -> fitglue.models.user.HevyIntegration
	3,  // 1: fitglue.models.user.UserIntegrations.fitbit:type_name -> fitglue.models.user.FitbitIntegration
	4,  // 2: fitglue.models.user.UserIntegrations.strava:type_name -> fitglue.models.user.StravaIntegration
	1,  // 3: fitglue.models.user.UserIntegrations.mock:type_name -> fitglue.models.user.MockIntegration
	5,  // 4: fitglue.models.user.UserIntegrations.parkrun:type_name -> fitglue.models.user.ParkrunIntegration
	6,  // 5: fitglue.models.user.UserIntegrations.spotify:type_name -> fitglue.models.user.SpotifyIntegration
	7,  // 6: fitglue.models.user.UserIntegrations.trainingpeaks:type_name -> fitglue.models.user.TrainingPeaksIntegration
	8,  // 7: fitglue.models.user.UserIntegrations.intervals:type_name -> fitglue.models.user.IntervalsIntegration
	10, // 8: fitglue.models.user.UserIntegrations.google:type_name -> fitglue.models.user.GoogleIntegration
	9,  // 9: fitglue.models.user.UserIntegrations.oura:type_name -> fitglue.models.user.OuraIntegration
	11, // 10: fitglue.models.user.UserIntegrations.polar:type_name -> fitglue.models.user.PolarIntegration
	12, // 11: fitglue.models.user.UserIntegrations.wahoo:type_name -> fitglue.models.user.WahooIntegration
	13, // 12: fitglue.models.user.UserIntegrations.github:type_name -> fitglue.models.user.GitHubIntegration
	14, // 13: fitglue.models.user.UserIntegrations.apple_health:type_name -> fitglue.models.user.AppleHealthIntegration
	15, // 14: fitglue.models.user.UserIntegrations.health_connect:type_name -> fitglue.models.user.HealthConnectIntegration
	16, // 15: fitglue.models.user.MockIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 16: fitglue.models.user.MockIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 17: fitglue.models.user.HevyIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 18: fitglue.models.user.HevyIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 19: fitglue.models.user.FitbitIntegration.expires_at:type_name -> google.protobuf.Timestamp
	16, // 20: fitglue.models.user.FitbitIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 21: fitglue.models.user.FitbitIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 22: fitglue.models.user.StravaIntegration.expires_at:type_name -> google.protobuf.Timestamp
	16, // 23: fitglue.models.user.StravaIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 24: fitglue.models.user.StravaIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 25: fitglue.models.user.ParkrunIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 26: fitglue.models.user.ParkrunIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 27: fitglue.models.user.SpotifyIntegration.expires_at:type_name -> google.protobuf.Timestamp
	16, // 28: fitglue.models.user.SpotifyIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 29: fitglue.models.user.SpotifyIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 30: fitglue.models.user.TrainingPeaksIntegration.expires_at:type_name -> google.protobuf.Timestamp
	16, // 31: fitglue.models.user.TrainingPeaksIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 32: fitglue.models.user.TrainingPeaksIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 33: fitglue.models.user.IntervalsIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 34: fitglue.models.user.IntervalsIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 35: fitglue.models.user.OuraIntegration.expires_at:type_name -> google.protobuf.Timestamp
	16, // 36: fitglue.models.user.OuraIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 37: fitglue.models.user.OuraIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 38: fitglue.models.user.GoogleIntegration.expires_at:type_name -> google.protobuf.Timestamp
	16, // 39: fitglue.models.user.GoogleIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 40: fitglue.models.user.GoogleIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 41: fitglue.models.user.PolarIntegration.expires_at:type_name -> google.protobuf.Timestamp
	16, // 42: fitglue.models.user.PolarIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 43: fitglue.models.user.PolarIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 44: fitglue.models.user.WahooIntegration.expires_at:type_name -> google.protobuf.Timestamp
	16, // 45: fitglue.models.user.WahooIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 46: fitglue.models.user.WahooIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 47: fitglue.models.user.GitHubIntegration.expires_at:type_name -> google.protobuf.Timestamp
	16, // 48: fitglue.models.user.GitHubIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 49: fitglue.models.user.GitHubIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 50: fitglue.models.user.AppleHealthIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 51: fitglue.models.user.AppleHealthIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	16, // 52: fitglue.models.user.HealthConnectIntegration.created_at:type_name -> google.protobuf.Timestamp
	16, // 53: fitglue.models.user.HealthConnectIntegration.last_used_at:type_name -> google.protobuf.Timestamp
	54, // [54:54] is the sub-list for method output_type
	54, // [54:54] is the sub-list for method input_type
	54, // [54:54] is the sub-list for extension type_name
	54, // [54:54] is the sub-list for extension extendee
	0,  // [0:54] is the sub-list for field type_name
}

func init() { file_models_user_integration_proto_init() }
func file_models_user_integration_proto_init() {
	if File_models_user_integration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_user_integration_proto_rawDesc), len(file_models_user_integration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_user_integration_proto_goTypes,
		DependencyIndexes: file_models_user_integration_proto_depIdxs,
		MessageInfos:      file_models_user_integration_proto_msgTypes,
	}.Build()
	File_models_user_integration_proto = out.File
	file_models_user_integration_proto_goTypes = nil
	file_models_user_integration_proto_depIdxs = nil
}
