// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/activity/roundup.proto

package activity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoundupPeriodType int32

const (
	RoundupPeriodType_ROUNDUP_PERIOD_TYPE_UNSPECIFIED RoundupPeriodType = 0
	RoundupPeriodType_ROUNDUP_PERIOD_TYPE_WEEK        RoundupPeriodType = 1
	RoundupPeriodType_ROUNDUP_PERIOD_TYPE_MONTH       RoundupPeriodType = 2
	RoundupPeriodType_ROUNDUP_PERIOD_TYPE_YEAR        RoundupPeriodType = 3
)

// Enum value maps for RoundupPeriodType.
var (
	RoundupPeriodType_name = map[int32]string{
		0: "ROUNDUP_PERIOD_TYPE_UNSPECIFIED",
		1: "ROUNDUP_PERIOD_TYPE_WEEK",
		2: "ROUNDUP_PERIOD_TYPE_MONTH",
		3: "ROUNDUP_PERIOD_TYPE_YEAR",
	}
	RoundupPeriodType_value = map[string]int32{
		"ROUNDUP_PERIOD_TYPE_UNSPECIFIED": 0,
		"ROUNDUP_PERIOD_TYPE_WEEK":        1,
		"ROUNDUP_PERIOD_TYPE_MONTH":       2,
		"ROUNDUP_PERIOD_TYPE_YEAR":        3,
	}
)

func (x RoundupPeriodType) Enum() *RoundupPeriodType {
	p := new(RoundupPeriodType)
	*p = x
	return p
}

func (x RoundupPeriodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoundupPeriodType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_activity_roundup_proto_enumTypes[0].Descriptor()
}

func (RoundupPeriodType) Type() protoreflect.EnumType {
	return &file_models_activity_roundup_proto_enumTypes[0]
}

func (x RoundupPeriodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoundupPeriodType.Descriptor instead.
func (RoundupPeriodType) EnumDescriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{0}
}

type RoundupActivityTypeBreakdown struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActivityType         ActivityType           `protobuf:"varint,1,opt,name=activity_type,json=activityType,proto3,enum=fitglue.models.activity.ActivityType" json:"activity_type,omitempty"`
	ActivityCount        int32                  `protobuf:"varint,2,opt,name=activity_count,json=activityCount,proto3" json:"activity_count,omitempty"`
	TotalDistanceMeters  float64                `protobuf:"fixed64,3,opt,name=total_distance_meters,json=totalDistanceMeters,proto3" json:"total_distance_meters,omitempty"`
	TotalDurationSeconds float64                `protobuf:"fixed64,4,opt,name=total_duration_seconds,json=totalDurationSeconds,proto3" json:"total_duration_seconds,omitempty"`
	TotalWeightKg        float64                `protobuf:"fixed64,5,opt,name=total_weight_kg,json=totalWeightKg,proto3" json:"total_weight_kg,omitempty"`
	TotalSets            int32                  `protobuf:"varint,6,opt,name=total_sets,json=totalSets,proto3" json:"total_sets,omitempty"`
	TotalReps            int32                  `protobuf:"varint,7,opt,name=total_reps,json=totalReps,proto3" json:"total_reps,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RoundupActivityTypeBreakdown) Reset() {
	*x = RoundupActivityTypeBreakdown{}
	mi := &file_models_activity_roundup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundupActivityTypeBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundupActivityTypeBreakdown) ProtoMessage() {}

func (x *RoundupActivityTypeBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_roundup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundupActivityTypeBreakdown.ProtoReflect.Descriptor instead.
func (*RoundupActivityTypeBreakdown) Descriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{0}
}

func (x *RoundupActivityTypeBreakdown) GetActivityType() ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *RoundupActivityTypeBreakdown) GetActivityCount() int32 {
	if x != nil {
		return x.ActivityCount
	}
	return 0
}

func (x *RoundupActivityTypeBreakdown) GetTotalDistanceMeters() float64 {
	if x != nil {
		return x.TotalDistanceMeters
	}
	return 0
}

func (x *RoundupActivityTypeBreakdown) GetTotalDurationSeconds() float64 {
	if x != nil {
		return x.TotalDurationSeconds
	}
	return 0
}

func (x *RoundupActivityTypeBreakdown) GetTotalWeightKg() float64 {
	if x != nil {
		return x.TotalWeightKg
	}
	return 0
}

func (x *RoundupActivityTypeBreakdown) GetTotalSets() int32 {
	if x != nil {
		return x.TotalSets
	}
	return 0
}

func (x *RoundupActivityTypeBreakdown) GetTotalReps() int32 {
	if x != nil {
		return x.TotalReps
	}
	return 0
}

type ShowcaseRoundup struct {
	state                    protoimpl.MessageState          `protogen:"open.v1"`
	RoundupId                string                          `protobuf:"bytes,1,opt,name=roundup_id,json=roundupId,proto3" json:"roundup_id,omitempty"`
	Slug                     string                          `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	UserId                   string                          `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PeriodType               RoundupPeriodType               `protobuf:"varint,4,opt,name=period_type,json=periodType,proto3,enum=fitglue.models.activity.RoundupPeriodType" json:"period_type,omitempty"`
	PeriodKey                string                          `protobuf:"bytes,5,opt,name=period_key,json=periodKey,proto3" json:"period_key,omitempty"`
	PeriodStart              *timestamppb.Timestamp          `protobuf:"bytes,6,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd                *timestamppb.Timestamp          `protobuf:"bytes,7,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	GeneratedAt              *timestamppb.Timestamp          `protobuf:"bytes,8,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	TotalActivities          int32                           `protobuf:"varint,9,opt,name=total_activities,json=totalActivities,proto3" json:"total_activities,omitempty"`
	TotalDurationSeconds     float64                         `protobuf:"fixed64,10,opt,name=total_duration_seconds,json=totalDurationSeconds,proto3" json:"total_duration_seconds,omitempty"`
	TotalDistanceMeters      float64                         `protobuf:"fixed64,11,opt,name=total_distance_meters,json=totalDistanceMeters,proto3" json:"total_distance_meters,omitempty"`
	TotalElevationGainMeters float64                         `protobuf:"fixed64,12,opt,name=total_elevation_gain_meters,json=totalElevationGainMeters,proto3" json:"total_elevation_gain_meters,omitempty"`
	TotalCaloriesKcal        int32                           `protobuf:"varint,13,opt,name=total_calories_kcal,json=totalCaloriesKcal,proto3" json:"total_calories_kcal,omitempty"`
	ActivityTypeBreakdowns   []*RoundupActivityTypeBreakdown `protobuf:"bytes,14,rep,name=activity_type_breakdowns,json=activityTypeBreakdowns,proto3" json:"activity_type_breakdowns,omitempty"`
	HrZoneMinutes            []int32                         `protobuf:"varint,15,rep,packed,name=hr_zone_minutes,json=hrZoneMinutes,proto3" json:"hr_zone_minutes,omitempty"`
	PrsAchieved              []*ShowcaseTopPR                `protobuf:"bytes,16,rep,name=prs_achieved,json=prsAchieved,proto3" json:"prs_achieved,omitempty"`
	Sources                  []ActivitySource                `protobuf:"varint,17,rep,packed,name=sources,proto3,enum=fitglue.models.activity.ActivitySource" json:"sources,omitempty"`
	EffortEasyCount          int32                           `protobuf:"varint,18,opt,name=effort_easy_count,json=effortEasyCount,proto3" json:"effort_easy_count,omitempty"`
	EffortModerateCount      int32                           `protobuf:"varint,19,opt,name=effort_moderate_count,json=effortModerateCount,proto3" json:"effort_moderate_count,omitempty"`
	EffortHardCount          int32                           `protobuf:"varint,20,opt,name=effort_hard_count,json=effortHardCount,proto3" json:"effort_hard_count,omitempty"`
	OwnerDisplayName         string                          `protobuf:"bytes,21,opt,name=owner_display_name,json=ownerDisplayName,proto3" json:"owner_display_name,omitempty"`
	OwnerProfilePictureUrl   string                          `protobuf:"bytes,22,opt,name=owner_profile_picture_url,json=ownerProfilePictureUrl,proto3" json:"owner_profile_picture_url,omitempty"`
	OwnerProfileSlug         string                          `protobuf:"bytes,23,opt,name=owner_profile_slug,json=ownerProfileSlug,proto3" json:"owner_profile_slug,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ShowcaseRoundup) Reset() {
	*x = ShowcaseRoundup{}
	mi := &file_models_activity_roundup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowcaseRoundup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowcaseRoundup) ProtoMessage() {}

func (x *ShowcaseRoundup) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_roundup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowcaseRoundup.ProtoReflect.Descriptor instead.
func (*ShowcaseRoundup) Descriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{1}
}

func (x *ShowcaseRoundup) GetRoundupId() string {
	if x != nil {
		return x.RoundupId
	}
	return ""
}

func (x *ShowcaseRoundup) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ShowcaseRoundup) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShowcaseRoundup) GetPeriodType() RoundupPeriodType {
	if x != nil {
		return x.PeriodType
	}
	return RoundupPeriodType_ROUNDUP_PERIOD_TYPE_UNSPECIFIED
}

func (x *ShowcaseRoundup) GetPeriodKey() string {
	if x != nil {
		return x.PeriodKey
	}
	return ""
}

func (x *ShowcaseRoundup) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *ShowcaseRoundup) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *ShowcaseRoundup) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *ShowcaseRoundup) GetTotalActivities() int32 {
	if x != nil {
		return x.TotalActivities
	}
	return 0
}

func (x *ShowcaseRoundup) GetTotalDurationSeconds() float64 {
	if x != nil {
		return x.TotalDurationSeconds
	}
	return 0
}

func (x *ShowcaseRoundup) GetTotalDistanceMeters() float64 {
	if x != nil {
		return x.TotalDistanceMeters
	}
	return 0
}

func (x *ShowcaseRoundup) GetTotalElevationGainMeters() float64 {
	if x != nil {
		return x.TotalElevationGainMeters
	}
	return 0
}

func (x *ShowcaseRoundup) GetTotalCaloriesKcal() int32 {
	if x != nil {
		return x.TotalCaloriesKcal
	}
	return 0
}

func (x *ShowcaseRoundup) GetActivityTypeBreakdowns() []*RoundupActivityTypeBreakdown {
	if x != nil {
		return x.ActivityTypeBreakdowns
	}
	return nil
}

func (x *ShowcaseRoundup) GetHrZoneMinutes() []int32 {
	if x != nil {
		return x.HrZoneMinutes
	}
	return nil
}

func (x *ShowcaseRoundup) GetPrsAchieved() []*ShowcaseTopPR {
	if x != nil {
		return x.PrsAchieved
	}
	return nil
}

func (x *ShowcaseRoundup) GetSources() []ActivitySource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ShowcaseRoundup) GetEffortEasyCount() int32 {
	if x != nil {
		return x.EffortEasyCount
	}
	return 0
}

func (x *ShowcaseRoundup) GetEffortModerateCount() int32 {
	if x != nil {
		return x.EffortModerateCount
	}
	return 0
}

func (x *ShowcaseRoundup) GetEffortHardCount() int32 {
	if x != nil {
		return x.EffortHardCount
	}
	return 0
}

func (x *ShowcaseRoundup) GetOwnerDisplayName() string {
	if x != nil {
		return x.OwnerDisplayName
	}
	return ""
}

func (x *ShowcaseRoundup) GetOwnerProfilePictureUrl() string {
	if x != nil {
		return x.OwnerProfilePictureUrl
	}
	return ""
}

func (x *ShowcaseRoundup) GetOwnerProfileSlug() string {
	if x != nil {
		return x.OwnerProfileSlug
	}
	return ""
}

var File_models_activity_roundup_proto protoreflect.FileDescriptor

const file_models_activity_roundup_proto_rawDesc = "" +
	"\n" +
	"\x1dmodels/activity/roundup.proto\x12\x17fitglue.models.activity\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cmodels/activity/source.proto\x1a\x1emodels/activity/uploaded.proto\"\xe1\x02\n" +
	"\x1cRoundupActivityTypeBreakdown\x12J\n" +
	"\ractivity_type\x18\x01 \x01(\x0e2%.fitglue.models.activity.ActivityTypeR\factivityType\x12%\n" +
	"\x0eactivity_count\x18\x02 \x01(\x05R\ractivityCount\x122\n" +
	"\x15total_distance_meters\x18\x03 \x01(\x01R\x13totalDistanceMeters\x124\n" +
	"\x16total_duration_seconds\x18\x04 \x01(\x01R\x14totalDurationSeconds\x12&\n" +
	"\x0ftotal_weight_kg\x18\x05 \x01(\x01R\rtotalWeightKg\x12\x1d\n" +
	"\n" +
	"total_sets\x18\x06 \x01(\x05R\ttotalSets\x12\x1d\n" +
	"\n" +
	"total_reps\x18\a \x01(\x05R\ttotalReps\"\xd0\t\n" +
	"\x0fShowcaseRoundup\x12\x1d\n" +
	"\n" +
	"roundup_id\x18\x01 \x01(\tR\troundupId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12K\n" +
	"\vperiod_type\x18\x04 \x01(\x0e2*.fitglue.models.activity.RoundupPeriodTypeR\n" +
	"periodType\x12\x1d\n" +
	"\n" +
	"period_key\x18\x05 \x01(\tR\tperiodKey\x12=\n" +
	"\fperiod_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12=\n" +
	"\fgenerated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12)\n" +
	"\x10total_activities\x18\t \x01(\x05R\x0ftotalActivities\x124\n" +
	"\x16total_duration_seconds\x18\n" +
	" \x01(\x01R\x14totalDurationSeconds\x122\n" +
	"\x15total_distance_meters\x18\v \x01(\x01R\x13totalDistanceMeters\x12=\n" +
	"\x1btotal_elevation_gain_meters\x18\f \x01(\x01R\x18totalElevationGainMeters\x12.\n" +
	"\x13total_calories_kcal\x18\r \x01(\x05R\x11totalCaloriesKcal\x12o\n" +
	"\x18activity_type_breakdowns\x18\x0e \x03(\v25.fitglue.models.activity.RoundupActivityTypeBreakdownR\x16activityTypeBreakdowns\x12&\n" +
	"\x0fhr_zone_minutes\x18\x0f \x03(\x05R\rhrZoneMinutes\x12I\n" +
	"\fprs_achieved\x18\x10 \x03(\v2&.fitglue.models.activity.ShowcaseTopPRR\vprsAchieved\x12A\n" +
	"\asources\x18\x11 \x03(\x0e2'.fitglue.models.activity.ActivitySourceR\asources\x12*\n" +
	"\x11effort_easy_count\x18\x12 \x01(\x05R\x0feffortEasyCount\x122\n" +
	"\x15effort_moderate_count\x18\x13 \x01(\x05R\x13effortModerateCount\x12*\n" +
	"\x11effort_hard_count\x18\x14 \x01(\x05R\x0feffortHardCount\x12,\n" +
	"\x12owner_display_name\x18\x15 \x01(\tR\x10ownerDisplayName\x129\n" +
	"\x19owner_profile_picture_url\x18\x16 \x01(\tR\x16ownerProfilePictureUrl\x12,\n" +
	"\x12owner_profile_slug\x18\x17 \x01(\tR\x10ownerProfileSlug*\x93\x01\n" +
	"\x11RoundupPeriodType\x12#\n" +
	"\x1fROUNDUP_PERIOD_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ROUNDUP_PERIOD_TYPE_WEEK\x10\x01\x12\x1d\n" +
	"\x19ROUNDUP_PERIOD_TYPE_MONTH\x10\x02\x12\x1c\n" +
	"\x18ROUNDUP_PERIOD_TYPE_YEAR\x10\x03B?Z=github.com/fitglue/server/src/go/pkg/types/pb/models/activityb\x06proto3"

var (
	file_models_activity_roundup_proto_rawDescOnce sync.Once
	file_models_activity_roundup_proto_rawDescData []byte
)

func file_models_activity_roundup_proto_rawDescGZIP() []byte {
	file_models_activity_roundup_proto_rawDescOnce.Do(func() {
		file_models_activity_roundup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_activity_roundup_proto_rawDesc), len(file_models_activity_roundup_proto_rawDesc)))
	})
	return file_models_activity_roundup_proto_rawDescData
}

var file_models_activity_roundup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_activity_roundup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_activity_roundup_proto_goTypes = []any{
	(RoundupPeriodType)(0),               // 0: fitglue.models.activity.RoundupPeriodType
	(*RoundupActivityTypeBreakdown)(nil), // 1: fitglue.models.activity.RoundupActivityTypeBreakdown
	(*ShowcaseRoundup)(nil),              // 2: fitglue.models.activity.ShowcaseRoundup
	(ActivityType)(0),                    // 3: fitglue.models.activity.ActivityType
	(*timestamppb.Timestamp)(nil),        // 4: google.protobuf.Timestamp
	(*ShowcaseTopPR)(nil),                // 5: fitglue.models.activity.ShowcaseTopPR
	(ActivitySource)(0),                  // 6: fitglue.models.activity.ActivitySource
}
var file_models_activity_roundup_proto_depIdxs = []int32{
	3, // 0: fitglue.models.activity.RoundupActivityTypeBreakdown.activity_type:type_name -> fitglue.models.activity.ActivityType
	0, // 1: fitglue.models.activity.ShowcaseRoundup.period_type:type_name -> fitglue.models.activity.RoundupPeriodType
	4, // 2: fitglue.models.activity.ShowcaseRoundup.period_start:type_name -> google.protobuf.Timestamp
	4, // 3: fitglue.models.activity.ShowcaseRoundup.period_end:type_name -> google.protobuf.Timestamp
	4, // 4: fitglue.models.activity.ShowcaseRoundup.generated_at:type_name -> google.protobuf.Timestamp
	1, // 5: fitglue.models.activity.ShowcaseRoundup.activity_type_breakdowns:type_name -> fitglue.models.activity.RoundupActivityTypeBreakdown
	5, // 6: fitglue.models.activity.ShowcaseRoundup.prs_achieved:type_name -> fitglue.models.activity.ShowcaseTopPR
	6, // 7: fitglue.models.activity.ShowcaseRoundup.sources:type_name -> fitglue.models.activity.ActivitySource
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_models_activity_roundup_proto_init() }
func file_models_activity_roundup_proto_init() {
	if File_models_activity_roundup_proto != nil {
		return
	}
	file_models_activity_source_proto_init()
	file_models_activity_uploaded_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_activity_roundup_proto_rawDesc), len(file_models_activity_roundup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_activity_roundup_proto_goTypes,
		DependencyIndexes: file_models_activity_roundup_proto_depIdxs,
		EnumInfos:         file_models_activity_roundup_proto_enumTypes,
		MessageInfos:      file_models_activity_roundup_proto_msgTypes,
	}.Build()
	File_models_activity_roundup_proto = out.File
	file_models_activity_roundup_proto_goTypes = nil
	file_models_activity_roundup_proto_depIdxs = nil
}
