// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/activity/roundup.proto

package activity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoundupPeriodType int32

const (
	RoundupPeriodType_ROUNDUP_PERIOD_TYPE_UNSPECIFIED RoundupPeriodType = 0
	RoundupPeriodType_ROUNDUP_PERIOD_TYPE_WEEK        RoundupPeriodType = 1
	RoundupPeriodType_ROUNDUP_PERIOD_TYPE_MONTH       RoundupPeriodType = 2
	RoundupPeriodType_ROUNDUP_PERIOD_TYPE_YEAR        RoundupPeriodType = 3
)

// Enum value maps for RoundupPeriodType.
var (
	RoundupPeriodType_name = map[int32]string{
		0: "ROUNDUP_PERIOD_TYPE_UNSPECIFIED",
		1: "ROUNDUP_PERIOD_TYPE_WEEK",
		2: "ROUNDUP_PERIOD_TYPE_MONTH",
		3: "ROUNDUP_PERIOD_TYPE_YEAR",
	}
	RoundupPeriodType_value = map[string]int32{
		"ROUNDUP_PERIOD_TYPE_UNSPECIFIED": 0,
		"ROUNDUP_PERIOD_TYPE_WEEK":        1,
		"ROUNDUP_PERIOD_TYPE_MONTH":       2,
		"ROUNDUP_PERIOD_TYPE_YEAR":        3,
	}
)

func (x RoundupPeriodType) Enum() *RoundupPeriodType {
	p := new(RoundupPeriodType)
	*p = x
	return p
}

func (x RoundupPeriodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoundupPeriodType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_activity_roundup_proto_enumTypes[0].Descriptor()
}

func (RoundupPeriodType) Type() protoreflect.EnumType {
	return &file_models_activity_roundup_proto_enumTypes[0]
}

func (x RoundupPeriodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoundupPeriodType.Descriptor instead.
func (RoundupPeriodType) EnumDescriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{0}
}

// Per-day effort record for the consistency calendar heatmap.
type RoundupDayEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`                                   // YYYY-MM-DD (UTC)
	EffortLevel   int32                  `protobuf:"varint,2,opt,name=effort_level,json=effortLevel,proto3" json:"effort_level,omitempty"` // 0=rest 1=easy 2=moderate 3=hard 4=peak
	ActivityCount int32                  `protobuf:"varint,3,opt,name=activity_count,json=activityCount,proto3" json:"activity_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundupDayEntry) Reset() {
	*x = RoundupDayEntry{}
	mi := &file_models_activity_roundup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundupDayEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundupDayEntry) ProtoMessage() {}

func (x *RoundupDayEntry) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_roundup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundupDayEntry.ProtoReflect.Descriptor instead.
func (*RoundupDayEntry) Descriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{0}
}

func (x *RoundupDayEntry) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RoundupDayEntry) GetEffortLevel() int32 {
	if x != nil {
		return x.EffortLevel
	}
	return 0
}

func (x *RoundupDayEntry) GetActivityCount() int32 {
	if x != nil {
		return x.ActivityCount
	}
	return 0
}

// Pre-computed spotlight card — biggest session, longest streak, peak PR day.
type ShowcaseCalloutActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // e.g. "BIGGEST SESSION"
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StatValue     string                 `protobuf:"bytes,3,opt,name=stat_value,json=statValue,proto3" json:"stat_value,omitempty"` // pre-formatted primary stat, e.g. "5:42"
	StatUnit      string                 `protobuf:"bytes,4,opt,name=stat_unit,json=statUnit,proto3" json:"stat_unit,omitempty"`    // unit/sub-stat line, e.g. "H:MM · 142 KM"
	Sub           string                 `protobuf:"bytes,5,opt,name=sub,proto3" json:"sub,omitempty"`                              // second detail line
	Date          string                 `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`                            // e.g. "14 Sep"
	ActivityType  ActivityType           `protobuf:"varint,7,opt,name=activity_type,json=activityType,proto3,enum=fitglue.models.activity.ActivityType" json:"activity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowcaseCalloutActivity) Reset() {
	*x = ShowcaseCalloutActivity{}
	mi := &file_models_activity_roundup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowcaseCalloutActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowcaseCalloutActivity) ProtoMessage() {}

func (x *ShowcaseCalloutActivity) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_roundup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowcaseCalloutActivity.ProtoReflect.Descriptor instead.
func (*ShowcaseCalloutActivity) Descriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{1}
}

func (x *ShowcaseCalloutActivity) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ShowcaseCalloutActivity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShowcaseCalloutActivity) GetStatValue() string {
	if x != nil {
		return x.StatValue
	}
	return ""
}

func (x *ShowcaseCalloutActivity) GetStatUnit() string {
	if x != nil {
		return x.StatUnit
	}
	return ""
}

func (x *ShowcaseCalloutActivity) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *ShowcaseCalloutActivity) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ShowcaseCalloutActivity) GetActivityType() ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

// A photo surfaced in the roundup photo mosaic.
type RoundupPhoto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ActivityTitle string                 `protobuf:"bytes,2,opt,name=activity_title,json=activityTitle,proto3" json:"activity_title,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // e.g. "14 Sep"
	ActivityType  ActivityType           `protobuf:"varint,4,opt,name=activity_type,json=activityType,proto3,enum=fitglue.models.activity.ActivityType" json:"activity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundupPhoto) Reset() {
	*x = RoundupPhoto{}
	mi := &file_models_activity_roundup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundupPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundupPhoto) ProtoMessage() {}

func (x *RoundupPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_roundup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundupPhoto.ProtoReflect.Descriptor instead.
func (*RoundupPhoto) Descriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{2}
}

func (x *RoundupPhoto) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RoundupPhoto) GetActivityTitle() string {
	if x != nil {
		return x.ActivityTitle
	}
	return ""
}

func (x *RoundupPhoto) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RoundupPhoto) GetActivityType() ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

// A GPS route thumbnail surfaced in the roundup route wall.
type RoundupRoute struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ThumbnailUrl   string                 `protobuf:"bytes,1,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	ActivityTitle  string                 `protobuf:"bytes,2,opt,name=activity_title,json=activityTitle,proto3" json:"activity_title,omitempty"`
	Date           string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // e.g. "14 Sep"
	DistanceMeters float64                `protobuf:"fixed64,4,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	ActivityType   ActivityType           `protobuf:"varint,5,opt,name=activity_type,json=activityType,proto3,enum=fitglue.models.activity.ActivityType" json:"activity_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoundupRoute) Reset() {
	*x = RoundupRoute{}
	mi := &file_models_activity_roundup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundupRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundupRoute) ProtoMessage() {}

func (x *RoundupRoute) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_roundup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundupRoute.ProtoReflect.Descriptor instead.
func (*RoundupRoute) Descriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{3}
}

func (x *RoundupRoute) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *RoundupRoute) GetActivityTitle() string {
	if x != nil {
		return x.ActivityTitle
	}
	return ""
}

func (x *RoundupRoute) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RoundupRoute) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *RoundupRoute) GetActivityType() ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

// A place trained at during the period (from LocationSummary).
type RoundupPlace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	ActivityCount int32                  `protobuf:"varint,3,opt,name=activity_count,json=activityCount,proto3" json:"activity_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundupPlace) Reset() {
	*x = RoundupPlace{}
	mi := &file_models_activity_roundup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundupPlace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundupPlace) ProtoMessage() {}

func (x *RoundupPlace) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_roundup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundupPlace.ProtoReflect.Descriptor instead.
func (*RoundupPlace) Descriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{4}
}

func (x *RoundupPlace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoundupPlace) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RoundupPlace) GetActivityCount() int32 {
	if x != nil {
		return x.ActivityCount
	}
	return 0
}

// Aggregate weather grit over the period (from WeatherSummary).
type RoundupWeather struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionCount  int32                  `protobuf:"varint,1,opt,name=session_count,json=sessionCount,proto3" json:"session_count,omitempty"` // sessions that carried weather data
	RainCount     int32                  `protobuf:"varint,2,opt,name=rain_count,json=rainCount,proto3" json:"rain_count,omitempty"`          // sessions in rain/drizzle/snow
	ColdestTempC  float64                `protobuf:"fixed64,3,opt,name=coldest_temp_c,json=coldestTempC,proto3" json:"coldest_temp_c,omitempty"`
	HottestTempC  float64                `protobuf:"fixed64,4,opt,name=hottest_temp_c,json=hottestTempC,proto3" json:"hottest_temp_c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundupWeather) Reset() {
	*x = RoundupWeather{}
	mi := &file_models_activity_roundup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundupWeather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundupWeather) ProtoMessage() {}

func (x *RoundupWeather) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_roundup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundupWeather.ProtoReflect.Descriptor instead.
func (*RoundupWeather) Descriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{5}
}

func (x *RoundupWeather) GetSessionCount() int32 {
	if x != nil {
		return x.SessionCount
	}
	return 0
}

func (x *RoundupWeather) GetRainCount() int32 {
	if x != nil {
		return x.RainCount
	}
	return 0
}

func (x *RoundupWeather) GetColdestTempC() float64 {
	if x != nil {
		return x.ColdestTempC
	}
	return 0
}

func (x *RoundupWeather) GetHottestTempC() float64 {
	if x != nil {
		return x.HottestTempC
	}
	return 0
}

// A muscle group worked across the period, with frequency (from MuscleHeatmapSummary).
type RoundupMuscle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundupMuscle) Reset() {
	*x = RoundupMuscle{}
	mi := &file_models_activity_roundup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundupMuscle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundupMuscle) ProtoMessage() {}

func (x *RoundupMuscle) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_roundup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundupMuscle.ProtoReflect.Descriptor instead.
func (*RoundupMuscle) Descriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{6}
}

func (x *RoundupMuscle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoundupMuscle) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RoundupActivityTypeBreakdown struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActivityType         ActivityType           `protobuf:"varint,1,opt,name=activity_type,json=activityType,proto3,enum=fitglue.models.activity.ActivityType" json:"activity_type,omitempty"`
	ActivityCount        int32                  `protobuf:"varint,2,opt,name=activity_count,json=activityCount,proto3" json:"activity_count,omitempty"`
	TotalDistanceMeters  float64                `protobuf:"fixed64,3,opt,name=total_distance_meters,json=totalDistanceMeters,proto3" json:"total_distance_meters,omitempty"`
	TotalDurationSeconds float64                `protobuf:"fixed64,4,opt,name=total_duration_seconds,json=totalDurationSeconds,proto3" json:"total_duration_seconds,omitempty"`
	TotalWeightKg        float64                `protobuf:"fixed64,5,opt,name=total_weight_kg,json=totalWeightKg,proto3" json:"total_weight_kg,omitempty"`
	TotalSets            int32                  `protobuf:"varint,6,opt,name=total_sets,json=totalSets,proto3" json:"total_sets,omitempty"`
	TotalReps            int32                  `protobuf:"varint,7,opt,name=total_reps,json=totalReps,proto3" json:"total_reps,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RoundupActivityTypeBreakdown) Reset() {
	*x = RoundupActivityTypeBreakdown{}
	mi := &file_models_activity_roundup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundupActivityTypeBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundupActivityTypeBreakdown) ProtoMessage() {}

func (x *RoundupActivityTypeBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_roundup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundupActivityTypeBreakdown.ProtoReflect.Descriptor instead.
func (*RoundupActivityTypeBreakdown) Descriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{7}
}

func (x *RoundupActivityTypeBreakdown) GetActivityType() ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *RoundupActivityTypeBreakdown) GetActivityCount() int32 {
	if x != nil {
		return x.ActivityCount
	}
	return 0
}

func (x *RoundupActivityTypeBreakdown) GetTotalDistanceMeters() float64 {
	if x != nil {
		return x.TotalDistanceMeters
	}
	return 0
}

func (x *RoundupActivityTypeBreakdown) GetTotalDurationSeconds() float64 {
	if x != nil {
		return x.TotalDurationSeconds
	}
	return 0
}

func (x *RoundupActivityTypeBreakdown) GetTotalWeightKg() float64 {
	if x != nil {
		return x.TotalWeightKg
	}
	return 0
}

func (x *RoundupActivityTypeBreakdown) GetTotalSets() int32 {
	if x != nil {
		return x.TotalSets
	}
	return 0
}

func (x *RoundupActivityTypeBreakdown) GetTotalReps() int32 {
	if x != nil {
		return x.TotalReps
	}
	return 0
}

type ShowcaseRoundup struct {
	state                    protoimpl.MessageState          `protogen:"open.v1"`
	RoundupId                string                          `protobuf:"bytes,1,opt,name=roundup_id,json=roundupId,proto3" json:"roundup_id,omitempty"`
	Slug                     string                          `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	UserId                   string                          `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PeriodType               RoundupPeriodType               `protobuf:"varint,4,opt,name=period_type,json=periodType,proto3,enum=fitglue.models.activity.RoundupPeriodType" json:"period_type,omitempty"`
	PeriodKey                string                          `protobuf:"bytes,5,opt,name=period_key,json=periodKey,proto3" json:"period_key,omitempty"`
	PeriodStart              *timestamppb.Timestamp          `protobuf:"bytes,6,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd                *timestamppb.Timestamp          `protobuf:"bytes,7,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	GeneratedAt              *timestamppb.Timestamp          `protobuf:"bytes,8,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	TotalActivities          int32                           `protobuf:"varint,9,opt,name=total_activities,json=totalActivities,proto3" json:"total_activities,omitempty"`
	TotalDurationSeconds     float64                         `protobuf:"fixed64,10,opt,name=total_duration_seconds,json=totalDurationSeconds,proto3" json:"total_duration_seconds,omitempty"`
	TotalDistanceMeters      float64                         `protobuf:"fixed64,11,opt,name=total_distance_meters,json=totalDistanceMeters,proto3" json:"total_distance_meters,omitempty"`
	TotalElevationGainMeters float64                         `protobuf:"fixed64,12,opt,name=total_elevation_gain_meters,json=totalElevationGainMeters,proto3" json:"total_elevation_gain_meters,omitempty"`
	TotalCaloriesKcal        int32                           `protobuf:"varint,13,opt,name=total_calories_kcal,json=totalCaloriesKcal,proto3" json:"total_calories_kcal,omitempty"`
	ActivityTypeBreakdowns   []*RoundupActivityTypeBreakdown `protobuf:"bytes,14,rep,name=activity_type_breakdowns,json=activityTypeBreakdowns,proto3" json:"activity_type_breakdowns,omitempty"`
	HrZoneMinutes            []int32                         `protobuf:"varint,15,rep,packed,name=hr_zone_minutes,json=hrZoneMinutes,proto3" json:"hr_zone_minutes,omitempty"`
	PrsAchieved              []*ShowcaseTopPR                `protobuf:"bytes,16,rep,name=prs_achieved,json=prsAchieved,proto3" json:"prs_achieved,omitempty"`
	Sources                  []ActivitySource                `protobuf:"varint,17,rep,packed,name=sources,proto3,enum=fitglue.models.activity.ActivitySource" json:"sources,omitempty"`
	EffortEasyCount          int32                           `protobuf:"varint,18,opt,name=effort_easy_count,json=effortEasyCount,proto3" json:"effort_easy_count,omitempty"`
	EffortModerateCount      int32                           `protobuf:"varint,19,opt,name=effort_moderate_count,json=effortModerateCount,proto3" json:"effort_moderate_count,omitempty"`
	EffortHardCount          int32                           `protobuf:"varint,20,opt,name=effort_hard_count,json=effortHardCount,proto3" json:"effort_hard_count,omitempty"`
	OwnerDisplayName         string                          `protobuf:"bytes,21,opt,name=owner_display_name,json=ownerDisplayName,proto3" json:"owner_display_name,omitempty"`
	OwnerProfilePictureUrl   string                          `protobuf:"bytes,22,opt,name=owner_profile_picture_url,json=ownerProfilePictureUrl,proto3" json:"owner_profile_picture_url,omitempty"`
	OwnerProfileSlug         string                          `protobuf:"bytes,23,opt,name=owner_profile_slug,json=ownerProfileSlug,proto3" json:"owner_profile_slug,omitempty"`
	// Highlight stats — best single activity across the period
	LongestActivityDurationSeconds float64 `protobuf:"fixed64,24,opt,name=longest_activity_duration_seconds,json=longestActivityDurationSeconds,proto3" json:"longest_activity_duration_seconds,omitempty"`
	HighestSingleLiftKg            float64 `protobuf:"fixed64,25,opt,name=highest_single_lift_kg,json=highestSingleLiftKg,proto3" json:"highest_single_lift_kg,omitempty"`
	HighestCaloriesPerHourKcal     float64 `protobuf:"fixed64,26,opt,name=highest_calories_per_hour_kcal,json=highestCaloriesPerHourKcal,proto3" json:"highest_calories_per_hour_kcal,omitempty"`
	HighestAvgBpmActivityTitle     string  `protobuf:"bytes,27,opt,name=highest_avg_bpm_activity_title,json=highestAvgBpmActivityTitle,proto3" json:"highest_avg_bpm_activity_title,omitempty"`
	HighestAvgBpm                  int32   `protobuf:"varint,28,opt,name=highest_avg_bpm,json=highestAvgBpm,proto3" json:"highest_avg_bpm,omitempty"`
	// AI-generated narrative summary of the period, empty if unavailable
	AiSummary string `protobuf:"bytes,29,opt,name=ai_summary,json=aiSummary,proto3" json:"ai_summary,omitempty"`
	// Pre-computed spotlight callouts (biggest session, longest streak, peak PR day)
	CalloutActivities []*ShowcaseCalloutActivity `protobuf:"bytes,30,rep,name=callout_activities,json=calloutActivities,proto3" json:"callout_activities,omitempty"`
	// Per-day effort entries for the consistency calendar heatmap
	DayEntries []*RoundupDayEntry `protobuf:"bytes,31,rep,name=day_entries,json=dayEntries,proto3" json:"day_entries,omitempty"`
	// Photos collected from the period's activities (gated by show_photo_gallery)
	Photos []*RoundupPhoto `protobuf:"bytes,32,rep,name=photos,proto3" json:"photos,omitempty"`
	// GPS route thumbnails collected from the period's activities
	Routes []*RoundupRoute `protobuf:"bytes,33,rep,name=routes,proto3" json:"routes,omitempty"`
	// Enrichment aggregates (elevation feeds total_elevation_gain_meters above)
	Places        []*RoundupPlace  `protobuf:"bytes,34,rep,name=places,proto3" json:"places,omitempty"`
	Weather       *RoundupWeather  `protobuf:"bytes,35,opt,name=weather,proto3,oneof" json:"weather,omitempty"`
	BestEfforts   []*BestEffort    `protobuf:"bytes,36,rep,name=best_efforts,json=bestEfforts,proto3" json:"best_efforts,omitempty"` // fastest per distance across the period
	Muscles       []*RoundupMuscle `protobuf:"bytes,37,rep,name=muscles,proto3" json:"muscles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowcaseRoundup) Reset() {
	*x = ShowcaseRoundup{}
	mi := &file_models_activity_roundup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowcaseRoundup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowcaseRoundup) ProtoMessage() {}

func (x *ShowcaseRoundup) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_roundup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowcaseRoundup.ProtoReflect.Descriptor instead.
func (*ShowcaseRoundup) Descriptor() ([]byte, []int) {
	return file_models_activity_roundup_proto_rawDescGZIP(), []int{8}
}

func (x *ShowcaseRoundup) GetRoundupId() string {
	if x != nil {
		return x.RoundupId
	}
	return ""
}

func (x *ShowcaseRoundup) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ShowcaseRoundup) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShowcaseRoundup) GetPeriodType() RoundupPeriodType {
	if x != nil {
		return x.PeriodType
	}
	return RoundupPeriodType_ROUNDUP_PERIOD_TYPE_UNSPECIFIED
}

func (x *ShowcaseRoundup) GetPeriodKey() string {
	if x != nil {
		return x.PeriodKey
	}
	return ""
}

func (x *ShowcaseRoundup) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *ShowcaseRoundup) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *ShowcaseRoundup) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *ShowcaseRoundup) GetTotalActivities() int32 {
	if x != nil {
		return x.TotalActivities
	}
	return 0
}

func (x *ShowcaseRoundup) GetTotalDurationSeconds() float64 {
	if x != nil {
		return x.TotalDurationSeconds
	}
	return 0
}

func (x *ShowcaseRoundup) GetTotalDistanceMeters() float64 {
	if x != nil {
		return x.TotalDistanceMeters
	}
	return 0
}

func (x *ShowcaseRoundup) GetTotalElevationGainMeters() float64 {
	if x != nil {
		return x.TotalElevationGainMeters
	}
	return 0
}

func (x *ShowcaseRoundup) GetTotalCaloriesKcal() int32 {
	if x != nil {
		return x.TotalCaloriesKcal
	}
	return 0
}

func (x *ShowcaseRoundup) GetActivityTypeBreakdowns() []*RoundupActivityTypeBreakdown {
	if x != nil {
		return x.ActivityTypeBreakdowns
	}
	return nil
}

func (x *ShowcaseRoundup) GetHrZoneMinutes() []int32 {
	if x != nil {
		return x.HrZoneMinutes
	}
	return nil
}

func (x *ShowcaseRoundup) GetPrsAchieved() []*ShowcaseTopPR {
	if x != nil {
		return x.PrsAchieved
	}
	return nil
}

func (x *ShowcaseRoundup) GetSources() []ActivitySource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ShowcaseRoundup) GetEffortEasyCount() int32 {
	if x != nil {
		return x.EffortEasyCount
	}
	return 0
}

func (x *ShowcaseRoundup) GetEffortModerateCount() int32 {
	if x != nil {
		return x.EffortModerateCount
	}
	return 0
}

func (x *ShowcaseRoundup) GetEffortHardCount() int32 {
	if x != nil {
		return x.EffortHardCount
	}
	return 0
}

func (x *ShowcaseRoundup) GetOwnerDisplayName() string {
	if x != nil {
		return x.OwnerDisplayName
	}
	return ""
}

func (x *ShowcaseRoundup) GetOwnerProfilePictureUrl() string {
	if x != nil {
		return x.OwnerProfilePictureUrl
	}
	return ""
}

func (x *ShowcaseRoundup) GetOwnerProfileSlug() string {
	if x != nil {
		return x.OwnerProfileSlug
	}
	return ""
}

func (x *ShowcaseRoundup) GetLongestActivityDurationSeconds() float64 {
	if x != nil {
		return x.LongestActivityDurationSeconds
	}
	return 0
}

func (x *ShowcaseRoundup) GetHighestSingleLiftKg() float64 {
	if x != nil {
		return x.HighestSingleLiftKg
	}
	return 0
}

func (x *ShowcaseRoundup) GetHighestCaloriesPerHourKcal() float64 {
	if x != nil {
		return x.HighestCaloriesPerHourKcal
	}
	return 0
}

func (x *ShowcaseRoundup) GetHighestAvgBpmActivityTitle() string {
	if x != nil {
		return x.HighestAvgBpmActivityTitle
	}
	return ""
}

func (x *ShowcaseRoundup) GetHighestAvgBpm() int32 {
	if x != nil {
		return x.HighestAvgBpm
	}
	return 0
}

func (x *ShowcaseRoundup) GetAiSummary() string {
	if x != nil {
		return x.AiSummary
	}
	return ""
}

func (x *ShowcaseRoundup) GetCalloutActivities() []*ShowcaseCalloutActivity {
	if x != nil {
		return x.CalloutActivities
	}
	return nil
}

func (x *ShowcaseRoundup) GetDayEntries() []*RoundupDayEntry {
	if x != nil {
		return x.DayEntries
	}
	return nil
}

func (x *ShowcaseRoundup) GetPhotos() []*RoundupPhoto {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *ShowcaseRoundup) GetRoutes() []*RoundupRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *ShowcaseRoundup) GetPlaces() []*RoundupPlace {
	if x != nil {
		return x.Places
	}
	return nil
}

func (x *ShowcaseRoundup) GetWeather() *RoundupWeather {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *ShowcaseRoundup) GetBestEfforts() []*BestEffort {
	if x != nil {
		return x.BestEfforts
	}
	return nil
}

func (x *ShowcaseRoundup) GetMuscles() []*RoundupMuscle {
	if x != nil {
		return x.Muscles
	}
	return nil
}

var File_models_activity_roundup_proto protoreflect.FileDescriptor

const file_models_activity_roundup_proto_rawDesc = "" +
	"\n" +
	"\x1dmodels/activity/roundup.proto\x12\x17fitglue.models.activity\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cmodels/activity/source.proto\x1a\x1emodels/activity/uploaded.proto\x1a!models/activity/enrichments.proto\"o\n" +
	"\x0fRoundupDayEntry\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12!\n" +
	"\feffort_level\x18\x02 \x01(\x05R\veffortLevel\x12%\n" +
	"\x0eactivity_count\x18\x03 \x01(\x05R\ractivityCount\"\xf1\x01\n" +
	"\x17ShowcaseCalloutActivity\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"stat_value\x18\x03 \x01(\tR\tstatValue\x12\x1b\n" +
	"\tstat_unit\x18\x04 \x01(\tR\bstatUnit\x12\x10\n" +
	"\x03sub\x18\x05 \x01(\tR\x03sub\x12\x12\n" +
	"\x04date\x18\x06 \x01(\tR\x04date\x12J\n" +
	"\ractivity_type\x18\a \x01(\x0e2%.fitglue.models.activity.ActivityTypeR\factivityType\"\xa7\x01\n" +
	"\fRoundupPhoto\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12%\n" +
	"\x0eactivity_title\x18\x02 \x01(\tR\ractivityTitle\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12J\n" +
	"\ractivity_type\x18\x04 \x01(\x0e2%.fitglue.models.activity.ActivityTypeR\factivityType\"\xe3\x01\n" +
	"\fRoundupRoute\x12#\n" +
	"\rthumbnail_url\x18\x01 \x01(\tR\fthumbnailUrl\x12%\n" +
	"\x0eactivity_title\x18\x02 \x01(\tR\ractivityTitle\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12'\n" +
	"\x0fdistance_meters\x18\x04 \x01(\x01R\x0edistanceMeters\x12J\n" +
	"\ractivity_type\x18\x05 \x01(\x0e2%.fitglue.models.activity.ActivityTypeR\factivityType\"c\n" +
	"\fRoundupPlace\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12%\n" +
	"\x0eactivity_count\x18\x03 \x01(\x05R\ractivityCount\"\xa0\x01\n" +
	"\x0eRoundupWeather\x12#\n" +
	"\rsession_count\x18\x01 \x01(\x05R\fsessionCount\x12\x1d\n" +
	"\n" +
	"rain_count\x18\x02 \x01(\x05R\trainCount\x12$\n" +
	"\x0ecoldest_temp_c\x18\x03 \x01(\x01R\fcoldestTempC\x12$\n" +
	"\x0ehottest_temp_c\x18\x04 \x01(\x01R\fhottestTempC\"9\n" +
	"\rRoundupMuscle\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xe1\x02\n" +
	"\x1cRoundupActivityTypeBreakdown\x12J\n" +
	"\ractivity_type\x18\x01 \x01(\x0e2%.fitglue.models.activity.ActivityTypeR\factivityType\x12%\n" +
	"\x0eactivity_count\x18\x02 \x01(\x05R\ractivityCount\x122\n" +
	"\x15total_distance_meters\x18\x03 \x01(\x01R\x13totalDistanceMeters\x124\n" +
	"\x16total_duration_seconds\x18\x04 \x01(\x01R\x14totalDurationSeconds\x12&\n" +
	"\x0ftotal_weight_kg\x18\x05 \x01(\x01R\rtotalWeightKg\x12\x1d\n" +
	"\n" +
	"total_sets\x18\x06 \x01(\x05R\ttotalSets\x12\x1d\n" +
	"\n" +
	"total_reps\x18\a \x01(\x05R\ttotalReps\"\xe6\x10\n" +
	"\x0fShowcaseRoundup\x12\x1d\n" +
	"\n" +
	"roundup_id\x18\x01 \x01(\tR\troundupId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12K\n" +
	"\vperiod_type\x18\x04 \x01(\x0e2*.fitglue.models.activity.RoundupPeriodTypeR\n" +
	"periodType\x12\x1d\n" +
	"\n" +
	"period_key\x18\x05 \x01(\tR\tperiodKey\x12=\n" +
	"\fperiod_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12=\n" +
	"\fgenerated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12)\n" +
	"\x10total_activities\x18\t \x01(\x05R\x0ftotalActivities\x124\n" +
	"\x16total_duration_seconds\x18\n" +
	" \x01(\x01R\x14totalDurationSeconds\x122\n" +
	"\x15total_distance_meters\x18\v \x01(\x01R\x13totalDistanceMeters\x12=\n" +
	"\x1btotal_elevation_gain_meters\x18\f \x01(\x01R\x18totalElevationGainMeters\x12.\n" +
	"\x13total_calories_kcal\x18\r \x01(\x05R\x11totalCaloriesKcal\x12o\n" +
	"\x18activity_type_breakdowns\x18\x0e \x03(\v25.fitglue.models.activity.RoundupActivityTypeBreakdownR\x16activityTypeBreakdowns\x12&\n" +
	"\x0fhr_zone_minutes\x18\x0f \x03(\x05R\rhrZoneMinutes\x12I\n" +
	"\fprs_achieved\x18\x10 \x03(\v2&.fitglue.models.activity.ShowcaseTopPRR\vprsAchieved\x12A\n" +
	"\asources\x18\x11 \x03(\x0e2'.fitglue.models.activity.ActivitySourceR\asources\x12*\n" +
	"\x11effort_easy_count\x18\x12 \x01(\x05R\x0feffortEasyCount\x122\n" +
	"\x15effort_moderate_count\x18\x13 \x01(\x05R\x13effortModerateCount\x12*\n" +
	"\x11effort_hard_count\x18\x14 \x01(\x05R\x0feffortHardCount\x12,\n" +
	"\x12owner_display_name\x18\x15 \x01(\tR\x10ownerDisplayName\x129\n" +
	"\x19owner_profile_picture_url\x18\x16 \x01(\tR\x16ownerProfilePictureUrl\x12,\n" +
	"\x12owner_profile_slug\x18\x17 \x01(\tR\x10ownerProfileSlug\x12I\n" +
	"!longest_activity_duration_seconds\x18\x18 \x01(\x01R\x1elongestActivityDurationSeconds\x123\n" +
	"\x16highest_single_lift_kg\x18\x19 \x01(\x01R\x13highestSingleLiftKg\x12B\n" +
	"\x1ehighest_calories_per_hour_kcal\x18\x1a \x01(\x01R\x1ahighestCaloriesPerHourKcal\x12B\n" +
	"\x1ehighest_avg_bpm_activity_title\x18\x1b \x01(\tR\x1ahighestAvgBpmActivityTitle\x12&\n" +
	"\x0fhighest_avg_bpm\x18\x1c \x01(\x05R\rhighestAvgBpm\x12\x1d\n" +
	"\n" +
	"ai_summary\x18\x1d \x01(\tR\taiSummary\x12_\n" +
	"\x12callout_activities\x18\x1e \x03(\v20.fitglue.models.activity.ShowcaseCalloutActivityR\x11calloutActivities\x12I\n" +
	"\vday_entries\x18\x1f \x03(\v2(.fitglue.models.activity.RoundupDayEntryR\n" +
	"dayEntries\x12=\n" +
	"\x06photos\x18  \x03(\v2%.fitglue.models.activity.RoundupPhotoR\x06photos\x12=\n" +
	"\x06routes\x18! \x03(\v2%.fitglue.models.activity.RoundupRouteR\x06routes\x12=\n" +
	"\x06places\x18\" \x03(\v2%.fitglue.models.activity.RoundupPlaceR\x06places\x12F\n" +
	"\aweather\x18# \x01(\v2'.fitglue.models.activity.RoundupWeatherH\x00R\aweather\x88\x01\x01\x12F\n" +
	"\fbest_efforts\x18$ \x03(\v2#.fitglue.models.activity.BestEffortR\vbestEfforts\x12@\n" +
	"\amuscles\x18% \x03(\v2&.fitglue.models.activity.RoundupMuscleR\amusclesB\n" +
	"\n" +
	"\b_weather*\x93\x01\n" +
	"\x11RoundupPeriodType\x12#\n" +
	"\x1fROUNDUP_PERIOD_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ROUNDUP_PERIOD_TYPE_WEEK\x10\x01\x12\x1d\n" +
	"\x19ROUNDUP_PERIOD_TYPE_MONTH\x10\x02\x12\x1c\n" +
	"\x18ROUNDUP_PERIOD_TYPE_YEAR\x10\x03B?Z=github.com/fitglue/server/src/go/pkg/types/pb/models/activityb\x06proto3"

var (
	file_models_activity_roundup_proto_rawDescOnce sync.Once
	file_models_activity_roundup_proto_rawDescData []byte
)

func file_models_activity_roundup_proto_rawDescGZIP() []byte {
	file_models_activity_roundup_proto_rawDescOnce.Do(func() {
		file_models_activity_roundup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_activity_roundup_proto_rawDesc), len(file_models_activity_roundup_proto_rawDesc)))
	})
	return file_models_activity_roundup_proto_rawDescData
}

var file_models_activity_roundup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_activity_roundup_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_models_activity_roundup_proto_goTypes = []any{
	(RoundupPeriodType)(0),               // 0: fitglue.models.activity.RoundupPeriodType
	(*RoundupDayEntry)(nil),              // 1: fitglue.models.activity.RoundupDayEntry
	(*ShowcaseCalloutActivity)(nil),      // 2: fitglue.models.activity.ShowcaseCalloutActivity
	(*RoundupPhoto)(nil),                 // 3: fitglue.models.activity.RoundupPhoto
	(*RoundupRoute)(nil),                 // 4: fitglue.models.activity.RoundupRoute
	(*RoundupPlace)(nil),                 // 5: fitglue.models.activity.RoundupPlace
	(*RoundupWeather)(nil),               // 6: fitglue.models.activity.RoundupWeather
	(*RoundupMuscle)(nil),                // 7: fitglue.models.activity.RoundupMuscle
	(*RoundupActivityTypeBreakdown)(nil), // 8: fitglue.models.activity.RoundupActivityTypeBreakdown
	(*ShowcaseRoundup)(nil),              // 9: fitglue.models.activity.ShowcaseRoundup
	(ActivityType)(0),                    // 10: fitglue.models.activity.ActivityType
	(*timestamppb.Timestamp)(nil),        // 11: google.protobuf.Timestamp
	(*ShowcaseTopPR)(nil),                // 12: fitglue.models.activity.ShowcaseTopPR
	(ActivitySource)(0),                  // 13: fitglue.models.activity.ActivitySource
	(*BestEffort)(nil),                   // 14: fitglue.models.activity.BestEffort
}
var file_models_activity_roundup_proto_depIdxs = []int32{
	10, // 0: fitglue.models.activity.ShowcaseCalloutActivity.activity_type:type_name -> fitglue.models.activity.ActivityType
	10, // 1: fitglue.models.activity.RoundupPhoto.activity_type:type_name -> fitglue.models.activity.ActivityType
	10, // 2: fitglue.models.activity.RoundupRoute.activity_type:type_name -> fitglue.models.activity.ActivityType
	10, // 3: fitglue.models.activity.RoundupActivityTypeBreakdown.activity_type:type_name -> fitglue.models.activity.ActivityType
	0,  // 4: fitglue.models.activity.ShowcaseRoundup.period_type:type_name -> fitglue.models.activity.RoundupPeriodType
	11, // 5: fitglue.models.activity.ShowcaseRoundup.period_start:type_name -> google.protobuf.Timestamp
	11, // 6: fitglue.models.activity.ShowcaseRoundup.period_end:type_name -> google.protobuf.Timestamp
	11, // 7: fitglue.models.activity.ShowcaseRoundup.generated_at:type_name -> google.protobuf.Timestamp
	8,  // 8: fitglue.models.activity.ShowcaseRoundup.activity_type_breakdowns:type_name -> fitglue.models.activity.RoundupActivityTypeBreakdown
	12, // 9: fitglue.models.activity.ShowcaseRoundup.prs_achieved:type_name -> fitglue.models.activity.ShowcaseTopPR
	13, // 10: fitglue.models.activity.ShowcaseRoundup.sources:type_name -> fitglue.models.activity.ActivitySource
	2,  // 11: fitglue.models.activity.ShowcaseRoundup.callout_activities:type_name -> fitglue.models.activity.ShowcaseCalloutActivity
	1,  // 12: fitglue.models.activity.ShowcaseRoundup.day_entries:type_name -> fitglue.models.activity.RoundupDayEntry
	3,  // 13: fitglue.models.activity.ShowcaseRoundup.photos:type_name -> fitglue.models.activity.RoundupPhoto
	4,  // 14: fitglue.models.activity.ShowcaseRoundup.routes:type_name -> fitglue.models.activity.RoundupRoute
	5,  // 15: fitglue.models.activity.ShowcaseRoundup.places:type_name -> fitglue.models.activity.RoundupPlace
	6,  // 16: fitglue.models.activity.ShowcaseRoundup.weather:type_name -> fitglue.models.activity.RoundupWeather
	14, // 17: fitglue.models.activity.ShowcaseRoundup.best_efforts:type_name -> fitglue.models.activity.BestEffort
	7,  // 18: fitglue.models.activity.ShowcaseRoundup.muscles:type_name -> fitglue.models.activity.RoundupMuscle
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_models_activity_roundup_proto_init() }
func file_models_activity_roundup_proto_init() {
	if File_models_activity_roundup_proto != nil {
		return
	}
	file_models_activity_source_proto_init()
	file_models_activity_uploaded_proto_init()
	file_models_activity_enrichments_proto_init()
	file_models_activity_roundup_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_activity_roundup_proto_rawDesc), len(file_models_activity_roundup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_activity_roundup_proto_goTypes,
		DependencyIndexes: file_models_activity_roundup_proto_depIdxs,
		EnumInfos:         file_models_activity_roundup_proto_enumTypes,
		MessageInfos:      file_models_activity_roundup_proto_msgTypes,
	}.Build()
	File_models_activity_roundup_proto = out.File
	file_models_activity_roundup_proto_goTypes = nil
	file_models_activity_roundup_proto_depIdxs = nil
}
