// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/activity/uploaded.proto

package activity

import (
	plugin "github.com/fitglue/server/src/go/pkg/types/pb/models/plugin"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadedActivityRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Source        ActivitySource         `protobuf:"varint,3,opt,name=source,proto3,enum=fitglue.models.activity.ActivitySource" json:"source,omitempty"`
	ExternalId    string                 `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Destination   plugin.DestinationType `protobuf:"varint,6,opt,name=destination,proto3,enum=fitglue.models.plugin.DestinationType" json:"destination,omitempty"`
	DestinationId string                 `protobuf:"bytes,7,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadedActivityRecord) Reset() {
	*x = UploadedActivityRecord{}
	mi := &file_models_activity_uploaded_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadedActivityRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadedActivityRecord) ProtoMessage() {}

func (x *UploadedActivityRecord) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_uploaded_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadedActivityRecord.ProtoReflect.Descriptor instead.
func (*UploadedActivityRecord) Descriptor() ([]byte, []int) {
	return file_models_activity_uploaded_proto_rawDescGZIP(), []int{0}
}

func (x *UploadedActivityRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadedActivityRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadedActivityRecord) GetSource() ActivitySource {
	if x != nil {
		return x.Source
	}
	return ActivitySource_SOURCE_UNSPECIFIED
}

func (x *UploadedActivityRecord) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *UploadedActivityRecord) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UploadedActivityRecord) GetDestination() plugin.DestinationType {
	if x != nil {
		return x.Destination
	}
	return plugin.DestinationType(0)
}

func (x *UploadedActivityRecord) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *UploadedActivityRecord) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

// ShowcasedActivity represents a publicly shareable activity snapshot.
type ShowcasedActivity struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ShowcaseId             string                 `protobuf:"bytes,1,opt,name=showcase_id,json=showcaseId,proto3" json:"showcase_id,omitempty"`
	ActivityId             string                 `protobuf:"bytes,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	UserId                 string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                  string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description            string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ActivityType           ActivityType           `protobuf:"varint,6,opt,name=activity_type,json=activityType,proto3,enum=fitglue.models.activity.ActivityType" json:"activity_type,omitempty"`
	Source                 ActivitySource         `protobuf:"varint,7,opt,name=source,proto3,enum=fitglue.models.activity.ActivitySource" json:"source,omitempty"`
	StartTime              *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ActivityData           *StandardizedActivity  `protobuf:"bytes,9,opt,name=activity_data,json=activityData,proto3" json:"activity_data,omitempty"`
	FitFileUri             string                 `protobuf:"bytes,10,opt,name=fit_file_uri,json=fitFileUri,proto3" json:"fit_file_uri,omitempty"`
	AppliedEnrichments     []string               `protobuf:"bytes,11,rep,name=applied_enrichments,json=appliedEnrichments,proto3" json:"applied_enrichments,omitempty"`
	Tags                   []string               `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	PipelineExecutionId    *string                `protobuf:"bytes,14,opt,name=pipeline_execution_id,json=pipelineExecutionId,proto3,oneof" json:"pipeline_execution_id,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt              *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	OwnerDisplayName       string                 `protobuf:"bytes,17,opt,name=owner_display_name,json=ownerDisplayName,proto3" json:"owner_display_name,omitempty"`
	ActivityDataUri        string                 `protobuf:"bytes,18,opt,name=activity_data_uri,json=activityDataUri,proto3" json:"activity_data_uri,omitempty"`
	OwnerProfilePictureUrl string                 `protobuf:"bytes,19,opt,name=owner_profile_picture_url,json=ownerProfilePictureUrl,proto3" json:"owner_profile_picture_url,omitempty"`
	OwnerProfileSlug       string                 `protobuf:"bytes,20,opt,name=owner_profile_slug,json=ownerProfileSlug,proto3" json:"owner_profile_slug,omitempty"`
	PhotoUrls              []string               `protobuf:"bytes,21,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	Enrichments            *ActivityEnrichments   `protobuf:"bytes,22,opt,name=enrichments,proto3" json:"enrichments,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ShowcasedActivity) Reset() {
	*x = ShowcasedActivity{}
	mi := &file_models_activity_uploaded_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowcasedActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowcasedActivity) ProtoMessage() {}

func (x *ShowcasedActivity) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_uploaded_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowcasedActivity.ProtoReflect.Descriptor instead.
func (*ShowcasedActivity) Descriptor() ([]byte, []int) {
	return file_models_activity_uploaded_proto_rawDescGZIP(), []int{1}
}

func (x *ShowcasedActivity) GetShowcaseId() string {
	if x != nil {
		return x.ShowcaseId
	}
	return ""
}

func (x *ShowcasedActivity) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *ShowcasedActivity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShowcasedActivity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShowcasedActivity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShowcasedActivity) GetActivityType() ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *ShowcasedActivity) GetSource() ActivitySource {
	if x != nil {
		return x.Source
	}
	return ActivitySource_SOURCE_UNSPECIFIED
}

func (x *ShowcasedActivity) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ShowcasedActivity) GetActivityData() *StandardizedActivity {
	if x != nil {
		return x.ActivityData
	}
	return nil
}

func (x *ShowcasedActivity) GetFitFileUri() string {
	if x != nil {
		return x.FitFileUri
	}
	return ""
}

func (x *ShowcasedActivity) GetAppliedEnrichments() []string {
	if x != nil {
		return x.AppliedEnrichments
	}
	return nil
}

func (x *ShowcasedActivity) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ShowcasedActivity) GetPipelineExecutionId() string {
	if x != nil && x.PipelineExecutionId != nil {
		return *x.PipelineExecutionId
	}
	return ""
}

func (x *ShowcasedActivity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShowcasedActivity) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ShowcasedActivity) GetOwnerDisplayName() string {
	if x != nil {
		return x.OwnerDisplayName
	}
	return ""
}

func (x *ShowcasedActivity) GetActivityDataUri() string {
	if x != nil {
		return x.ActivityDataUri
	}
	return ""
}

func (x *ShowcasedActivity) GetOwnerProfilePictureUrl() string {
	if x != nil {
		return x.OwnerProfilePictureUrl
	}
	return ""
}

func (x *ShowcasedActivity) GetOwnerProfileSlug() string {
	if x != nil {
		return x.OwnerProfileSlug
	}
	return ""
}

func (x *ShowcasedActivity) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

func (x *ShowcasedActivity) GetEnrichments() *ActivityEnrichments {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

type ShowcaseProfileEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ShowcaseId        string                 `protobuf:"bytes,1,opt,name=showcase_id,json=showcaseId,proto3" json:"showcase_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ActivityType      ActivityType           `protobuf:"varint,3,opt,name=activity_type,json=activityType,proto3,enum=fitglue.models.activity.ActivityType" json:"activity_type,omitempty"`
	Source            ActivitySource         `protobuf:"varint,4,opt,name=source,proto3,enum=fitglue.models.activity.ActivitySource" json:"source,omitempty"`
	StartTime         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	RouteThumbnailUrl string                 `protobuf:"bytes,6,opt,name=route_thumbnail_url,json=routeThumbnailUrl,proto3" json:"route_thumbnail_url,omitempty"`
	DistanceMeters    float64                `protobuf:"fixed64,7,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	DurationSeconds   float64                `protobuf:"fixed64,8,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	TotalSets         int32                  `protobuf:"varint,9,opt,name=total_sets,json=totalSets,proto3" json:"total_sets,omitempty"`
	TotalReps         int32                  `protobuf:"varint,10,opt,name=total_reps,json=totalReps,proto3" json:"total_reps,omitempty"`
	TotalWeightKg     float64                `protobuf:"fixed64,11,opt,name=total_weight_kg,json=totalWeightKg,proto3" json:"total_weight_kg,omitempty"`
	// Reskin additions — populated on each activity sync
	BoosterCount     int32           `protobuf:"varint,12,opt,name=booster_count,json=boosterCount,proto3" json:"booster_count,omitempty"`
	DestinationCount int32           `protobuf:"varint,13,opt,name=destination_count,json=destinationCount,proto3" json:"destination_count,omitempty"`
	Sparkline        *EntrySparkline `protobuf:"bytes,14,opt,name=sparkline,proto3,oneof" json:"sparkline,omitempty"`
	AvgHeartRate     *int32          `protobuf:"varint,15,opt,name=avg_heart_rate,json=avgHeartRate,proto3,oneof" json:"avg_heart_rate,omitempty"`
	CaloriesKcal     *int32          `protobuf:"varint,16,opt,name=calories_kcal,json=caloriesKcal,proto3,oneof" json:"calories_kcal,omitempty"`
	// PR tag displayed on profile activity cards (e.g. "★ DEADLIFT 180KG · +5KG")
	PrLabel       *string `protobuf:"bytes,17,opt,name=pr_label,json=prLabel,proto3,oneof" json:"pr_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowcaseProfileEntry) Reset() {
	*x = ShowcaseProfileEntry{}
	mi := &file_models_activity_uploaded_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowcaseProfileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowcaseProfileEntry) ProtoMessage() {}

func (x *ShowcaseProfileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_uploaded_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowcaseProfileEntry.ProtoReflect.Descriptor instead.
func (*ShowcaseProfileEntry) Descriptor() ([]byte, []int) {
	return file_models_activity_uploaded_proto_rawDescGZIP(), []int{2}
}

func (x *ShowcaseProfileEntry) GetShowcaseId() string {
	if x != nil {
		return x.ShowcaseId
	}
	return ""
}

func (x *ShowcaseProfileEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShowcaseProfileEntry) GetActivityType() ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *ShowcaseProfileEntry) GetSource() ActivitySource {
	if x != nil {
		return x.Source
	}
	return ActivitySource_SOURCE_UNSPECIFIED
}

func (x *ShowcaseProfileEntry) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ShowcaseProfileEntry) GetRouteThumbnailUrl() string {
	if x != nil {
		return x.RouteThumbnailUrl
	}
	return ""
}

func (x *ShowcaseProfileEntry) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *ShowcaseProfileEntry) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *ShowcaseProfileEntry) GetTotalSets() int32 {
	if x != nil {
		return x.TotalSets
	}
	return 0
}

func (x *ShowcaseProfileEntry) GetTotalReps() int32 {
	if x != nil {
		return x.TotalReps
	}
	return 0
}

func (x *ShowcaseProfileEntry) GetTotalWeightKg() float64 {
	if x != nil {
		return x.TotalWeightKg
	}
	return 0
}

func (x *ShowcaseProfileEntry) GetBoosterCount() int32 {
	if x != nil {
		return x.BoosterCount
	}
	return 0
}

func (x *ShowcaseProfileEntry) GetDestinationCount() int32 {
	if x != nil {
		return x.DestinationCount
	}
	return 0
}

func (x *ShowcaseProfileEntry) GetSparkline() *EntrySparkline {
	if x != nil {
		return x.Sparkline
	}
	return nil
}

func (x *ShowcaseProfileEntry) GetAvgHeartRate() int32 {
	if x != nil && x.AvgHeartRate != nil {
		return *x.AvgHeartRate
	}
	return 0
}

func (x *ShowcaseProfileEntry) GetCaloriesKcal() int32 {
	if x != nil && x.CaloriesKcal != nil {
		return *x.CaloriesKcal
	}
	return 0
}

func (x *ShowcaseProfileEntry) GetPrLabel() string {
	if x != nil && x.PrLabel != nil {
		return *x.PrLabel
	}
	return ""
}

// EntrySparkline is a downsampled timeseries for card-level sparklines.
type EntrySparkline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`          // "heart_rate" | "pace" | "power" | "weight"
	Values        []float64              `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"` // ≤ 24 sample points, downsampled
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntrySparkline) Reset() {
	*x = EntrySparkline{}
	mi := &file_models_activity_uploaded_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntrySparkline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntrySparkline) ProtoMessage() {}

func (x *EntrySparkline) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_uploaded_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntrySparkline.ProtoReflect.Descriptor instead.
func (*EntrySparkline) Descriptor() ([]byte, []int) {
	return file_models_activity_uploaded_proto_rawDescGZIP(), []int{3}
}

func (x *EntrySparkline) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *EntrySparkline) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ShowcaseTheme struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ThemeId           string                 `protobuf:"bytes,1,opt,name=theme_id,json=themeId,proto3" json:"theme_id,omitempty"`
	CustomAccentColor string                 `protobuf:"bytes,2,opt,name=custom_accent_color,json=customAccentColor,proto3" json:"custom_accent_color,omitempty"`
	AnimationId       string                 `protobuf:"bytes,3,opt,name=animation_id,json=animationId,proto3" json:"animation_id,omitempty"`
	CardStyle         string                 `protobuf:"bytes,4,opt,name=card_style,json=cardStyle,proto3" json:"card_style,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShowcaseTheme) Reset() {
	*x = ShowcaseTheme{}
	mi := &file_models_activity_uploaded_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowcaseTheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowcaseTheme) ProtoMessage() {}

func (x *ShowcaseTheme) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_uploaded_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowcaseTheme.ProtoReflect.Descriptor instead.
func (*ShowcaseTheme) Descriptor() ([]byte, []int) {
	return file_models_activity_uploaded_proto_rawDescGZIP(), []int{4}
}

func (x *ShowcaseTheme) GetThemeId() string {
	if x != nil {
		return x.ThemeId
	}
	return ""
}

func (x *ShowcaseTheme) GetCustomAccentColor() string {
	if x != nil {
		return x.CustomAccentColor
	}
	return ""
}

func (x *ShowcaseTheme) GetAnimationId() string {
	if x != nil {
		return x.AnimationId
	}
	return ""
}

func (x *ShowcaseTheme) GetCardStyle() string {
	if x != nil {
		return x.CardStyle
	}
	return ""
}

type ShowcaseLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowcaseLink) Reset() {
	*x = ShowcaseLink{}
	mi := &file_models_activity_uploaded_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowcaseLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowcaseLink) ProtoMessage() {}

func (x *ShowcaseLink) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_uploaded_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowcaseLink.ProtoReflect.Descriptor instead.
func (*ShowcaseLink) Descriptor() ([]byte, []int) {
	return file_models_activity_uploaded_proto_rawDescGZIP(), []int{5}
}

func (x *ShowcaseLink) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ShowcaseLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShowcaseBioCallout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowcaseBioCallout) Reset() {
	*x = ShowcaseBioCallout{}
	mi := &file_models_activity_uploaded_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowcaseBioCallout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowcaseBioCallout) ProtoMessage() {}

func (x *ShowcaseBioCallout) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_uploaded_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowcaseBioCallout.ProtoReflect.Descriptor instead.
func (*ShowcaseBioCallout) Descriptor() ([]byte, []int) {
	return file_models_activity_uploaded_proto_rawDescGZIP(), []int{6}
}

func (x *ShowcaseBioCallout) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ShowcaseProfile struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	Slug                 string                  `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	UserId               string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName          string                  `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Entries              []*ShowcaseProfileEntry `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalActivities      int32                   `protobuf:"varint,5,opt,name=total_activities,json=totalActivities,proto3" json:"total_activities,omitempty"`
	TotalDistanceMeters  float64                 `protobuf:"fixed64,6,opt,name=total_distance_meters,json=totalDistanceMeters,proto3" json:"total_distance_meters,omitempty"`
	TotalDurationSeconds float64                 `protobuf:"fixed64,7,opt,name=total_duration_seconds,json=totalDurationSeconds,proto3" json:"total_duration_seconds,omitempty"`
	LatestActivityAt     *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=latest_activity_at,json=latestActivityAt,proto3" json:"latest_activity_at,omitempty"`
	TotalSets            int32                   `protobuf:"varint,11,opt,name=total_sets,json=totalSets,proto3" json:"total_sets,omitempty"`
	TotalReps            int32                   `protobuf:"varint,12,opt,name=total_reps,json=totalReps,proto3" json:"total_reps,omitempty"`
	TotalWeightKg        float64                 `protobuf:"fixed64,13,opt,name=total_weight_kg,json=totalWeightKg,proto3" json:"total_weight_kg,omitempty"`
	CreatedAt            *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Subtitle             string                  `protobuf:"bytes,14,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Bio                  string                  `protobuf:"bytes,15,opt,name=bio,proto3" json:"bio,omitempty"`
	ProfilePictureUrl    string                  `protobuf:"bytes,16,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	Visible              bool                    `protobuf:"varint,17,opt,name=visible,proto3" json:"visible,omitempty"`
	Theme                *ShowcaseTheme          `protobuf:"bytes,18,opt,name=theme,proto3" json:"theme,omitempty"`
	DefaultDestination   bool                    `protobuf:"varint,19,opt,name=default_destination,json=defaultDestination,proto3" json:"default_destination,omitempty"` // Auto-add Showcase destination when creating new pipelines
	ShowPhotoGallery     bool                    `protobuf:"varint,20,opt,name=show_photo_gallery,json=showPhotoGallery,proto3" json:"show_photo_gallery,omitempty"`
	Links                []*ShowcaseLink         `protobuf:"bytes,21,rep,name=links,proto3" json:"links,omitempty"`
	Callouts             []*ShowcaseBioCallout   `protobuf:"bytes,22,rep,name=callouts,proto3" json:"callouts,omitempty"`
	// Lifetime aggregates — written by a daily rollup job. Optional; absent means not yet computed.
	ZoneSplit     *LifetimeZoneSplit   `protobuf:"bytes,23,opt,name=zone_split,json=zoneSplit,proto3,oneof" json:"zone_split,omitempty"`
	StreakHistory *WeeklyStreakHistory `protobuf:"bytes,24,opt,name=streak_history,json=streakHistory,proto3,oneof" json:"streak_history,omitempty"`
	// Top strength PRs — populated at request time from users/{userId}/personal_records/
	TopPrs        []*ShowcaseTopPR `protobuf:"bytes,25,rep,name=top_prs,json=topPrs,proto3" json:"top_prs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowcaseProfile) Reset() {
	*x = ShowcaseProfile{}
	mi := &file_models_activity_uploaded_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowcaseProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowcaseProfile) ProtoMessage() {}

func (x *ShowcaseProfile) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_uploaded_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowcaseProfile.ProtoReflect.Descriptor instead.
func (*ShowcaseProfile) Descriptor() ([]byte, []int) {
	return file_models_activity_uploaded_proto_rawDescGZIP(), []int{7}
}

func (x *ShowcaseProfile) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ShowcaseProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShowcaseProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ShowcaseProfile) GetEntries() []*ShowcaseProfileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ShowcaseProfile) GetTotalActivities() int32 {
	if x != nil {
		return x.TotalActivities
	}
	return 0
}

func (x *ShowcaseProfile) GetTotalDistanceMeters() float64 {
	if x != nil {
		return x.TotalDistanceMeters
	}
	return 0
}

func (x *ShowcaseProfile) GetTotalDurationSeconds() float64 {
	if x != nil {
		return x.TotalDurationSeconds
	}
	return 0
}

func (x *ShowcaseProfile) GetLatestActivityAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LatestActivityAt
	}
	return nil
}

func (x *ShowcaseProfile) GetTotalSets() int32 {
	if x != nil {
		return x.TotalSets
	}
	return 0
}

func (x *ShowcaseProfile) GetTotalReps() int32 {
	if x != nil {
		return x.TotalReps
	}
	return 0
}

func (x *ShowcaseProfile) GetTotalWeightKg() float64 {
	if x != nil {
		return x.TotalWeightKg
	}
	return 0
}

func (x *ShowcaseProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShowcaseProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ShowcaseProfile) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *ShowcaseProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ShowcaseProfile) GetProfilePictureUrl() string {
	if x != nil {
		return x.ProfilePictureUrl
	}
	return ""
}

func (x *ShowcaseProfile) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *ShowcaseProfile) GetTheme() *ShowcaseTheme {
	if x != nil {
		return x.Theme
	}
	return nil
}

func (x *ShowcaseProfile) GetDefaultDestination() bool {
	if x != nil {
		return x.DefaultDestination
	}
	return false
}

func (x *ShowcaseProfile) GetShowPhotoGallery() bool {
	if x != nil {
		return x.ShowPhotoGallery
	}
	return false
}

func (x *ShowcaseProfile) GetLinks() []*ShowcaseLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ShowcaseProfile) GetCallouts() []*ShowcaseBioCallout {
	if x != nil {
		return x.Callouts
	}
	return nil
}

func (x *ShowcaseProfile) GetZoneSplit() *LifetimeZoneSplit {
	if x != nil {
		return x.ZoneSplit
	}
	return nil
}

func (x *ShowcaseProfile) GetStreakHistory() *WeeklyStreakHistory {
	if x != nil {
		return x.StreakHistory
	}
	return nil
}

func (x *ShowcaseProfile) GetTopPrs() []*ShowcaseTopPR {
	if x != nil {
		return x.TopPrs
	}
	return nil
}

// ShowcaseTopPR is a lightweight personal record for display on the profile medal wall.
type ShowcaseTopPR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordType    string                 `protobuf:"bytes,1,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"` // e.g. "bench_press_1rm"
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`                           // e.g. 180
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`                               // "kg", "seconds", "meters"
	AchievedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=achieved_at,json=achievedAt,proto3,oneof" json:"achieved_at,omitempty"`
	PreviousValue *float64               `protobuf:"fixed64,5,opt,name=previous_value,json=previousValue,proto3,oneof" json:"previous_value,omitempty"` // for computing improvement delta
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowcaseTopPR) Reset() {
	*x = ShowcaseTopPR{}
	mi := &file_models_activity_uploaded_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowcaseTopPR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowcaseTopPR) ProtoMessage() {}

func (x *ShowcaseTopPR) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_uploaded_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowcaseTopPR.ProtoReflect.Descriptor instead.
func (*ShowcaseTopPR) Descriptor() ([]byte, []int) {
	return file_models_activity_uploaded_proto_rawDescGZIP(), []int{8}
}

func (x *ShowcaseTopPR) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *ShowcaseTopPR) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ShowcaseTopPR) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ShowcaseTopPR) GetAchievedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AchievedAt
	}
	return nil
}

func (x *ShowcaseTopPR) GetPreviousValue() float64 {
	if x != nil && x.PreviousValue != nil {
		return *x.PreviousValue
	}
	return 0
}

type LifetimeZoneSplit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*HeartRateZoneBucket `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"` // re-uses HeartRateZoneBucket from enrichments.proto
	ComputedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=computed_at,json=computedAt,proto3" json:"computed_at,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"` // "Polarized", "Pyramidal", "Threshold"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifetimeZoneSplit) Reset() {
	*x = LifetimeZoneSplit{}
	mi := &file_models_activity_uploaded_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifetimeZoneSplit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifetimeZoneSplit) ProtoMessage() {}

func (x *LifetimeZoneSplit) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_uploaded_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifetimeZoneSplit.ProtoReflect.Descriptor instead.
func (*LifetimeZoneSplit) Descriptor() ([]byte, []int) {
	return file_models_activity_uploaded_proto_rawDescGZIP(), []int{9}
}

func (x *LifetimeZoneSplit) GetZones() []*HeartRateZoneBucket {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *LifetimeZoneSplit) GetComputedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ComputedAt
	}
	return nil
}

func (x *LifetimeZoneSplit) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type WeeklyStreakHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeeksTracked  int32                  `protobuf:"varint,1,opt,name=weeks_tracked,json=weeksTracked,proto3" json:"weeks_tracked,omitempty"`        // e.g. 26
	MissedWeeks   int32                  `protobuf:"varint,2,opt,name=missed_weeks,json=missedWeeks,proto3" json:"missed_weeks,omitempty"`           // count of weeks with zero qualifying activities
	WeeklyActive  []bool                 `protobuf:"varint,3,rep,packed,name=weekly_active,json=weeklyActive,proto3" json:"weekly_active,omitempty"` // most-recent-last; true = had at least one activity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeklyStreakHistory) Reset() {
	*x = WeeklyStreakHistory{}
	mi := &file_models_activity_uploaded_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyStreakHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyStreakHistory) ProtoMessage() {}

func (x *WeeklyStreakHistory) ProtoReflect() protoreflect.Message {
	mi := &file_models_activity_uploaded_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyStreakHistory.ProtoReflect.Descriptor instead.
func (*WeeklyStreakHistory) Descriptor() ([]byte, []int) {
	return file_models_activity_uploaded_proto_rawDescGZIP(), []int{10}
}

func (x *WeeklyStreakHistory) GetWeeksTracked() int32 {
	if x != nil {
		return x.WeeksTracked
	}
	return 0
}

func (x *WeeklyStreakHistory) GetMissedWeeks() int32 {
	if x != nil {
		return x.MissedWeeks
	}
	return 0
}

func (x *WeeklyStreakHistory) GetWeeklyActive() []bool {
	if x != nil {
		return x.WeeklyActive
	}
	return nil
}

var File_models_activity_uploaded_proto protoreflect.FileDescriptor

const file_models_activity_uploaded_proto_rawDesc = "" +
	"\n" +
	"\x1emodels/activity/uploaded.proto\x12\x17fitglue.models.activity\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cmodels/activity/source.proto\x1a\x1cmodels/plugin/provider.proto\x1a\"models/activity/standardized.proto\x1a!models/activity/enrichments.proto\"\x8c\x03\n" +
	"\x16UploadedActivityRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12?\n" +
	"\x06source\x18\x03 \x01(\x0e2'.fitglue.models.activity.ActivitySourceR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x04 \x01(\tR\n" +
	"externalId\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12H\n" +
	"\vdestination\x18\x06 \x01(\x0e2&.fitglue.models.plugin.DestinationTypeR\vdestination\x12%\n" +
	"\x0edestination_id\x18\a \x01(\tR\rdestinationId\x12;\n" +
	"\vuploaded_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\"\xaa\b\n" +
	"\x11ShowcasedActivity\x12\x1f\n" +
	"\vshowcase_id\x18\x01 \x01(\tR\n" +
	"showcaseId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\tR\n" +
	"activityId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12J\n" +
	"\ractivity_type\x18\x06 \x01(\x0e2%.fitglue.models.activity.ActivityTypeR\factivityType\x12?\n" +
	"\x06source\x18\a \x01(\x0e2'.fitglue.models.activity.ActivitySourceR\x06source\x129\n" +
	"\n" +
	"start_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12R\n" +
	"\ractivity_data\x18\t \x01(\v2-.fitglue.models.activity.StandardizedActivityR\factivityData\x12 \n" +
	"\ffit_file_uri\x18\n" +
	" \x01(\tR\n" +
	"fitFileUri\x12/\n" +
	"\x13applied_enrichments\x18\v \x03(\tR\x12appliedEnrichments\x12\x12\n" +
	"\x04tags\x18\r \x03(\tR\x04tags\x127\n" +
	"\x15pipeline_execution_id\x18\x0e \x01(\tH\x00R\x13pipelineExecutionId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12,\n" +
	"\x12owner_display_name\x18\x11 \x01(\tR\x10ownerDisplayName\x12*\n" +
	"\x11activity_data_uri\x18\x12 \x01(\tR\x0factivityDataUri\x129\n" +
	"\x19owner_profile_picture_url\x18\x13 \x01(\tR\x16ownerProfilePictureUrl\x12,\n" +
	"\x12owner_profile_slug\x18\x14 \x01(\tR\x10ownerProfileSlug\x12\x1d\n" +
	"\n" +
	"photo_urls\x18\x15 \x03(\tR\tphotoUrls\x12N\n" +
	"\venrichments\x18\x16 \x01(\v2,.fitglue.models.activity.ActivityEnrichmentsR\venrichmentsB\x18\n" +
	"\x16_pipeline_execution_idJ\x04\b\f\x10\r\"\xd2\x06\n" +
	"\x14ShowcaseProfileEntry\x12\x1f\n" +
	"\vshowcase_id\x18\x01 \x01(\tR\n" +
	"showcaseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12J\n" +
	"\ractivity_type\x18\x03 \x01(\x0e2%.fitglue.models.activity.ActivityTypeR\factivityType\x12?\n" +
	"\x06source\x18\x04 \x01(\x0e2'.fitglue.models.activity.ActivitySourceR\x06source\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12.\n" +
	"\x13route_thumbnail_url\x18\x06 \x01(\tR\x11routeThumbnailUrl\x12'\n" +
	"\x0fdistance_meters\x18\a \x01(\x01R\x0edistanceMeters\x12)\n" +
	"\x10duration_seconds\x18\b \x01(\x01R\x0fdurationSeconds\x12\x1d\n" +
	"\n" +
	"total_sets\x18\t \x01(\x05R\ttotalSets\x12\x1d\n" +
	"\n" +
	"total_reps\x18\n" +
	" \x01(\x05R\ttotalReps\x12&\n" +
	"\x0ftotal_weight_kg\x18\v \x01(\x01R\rtotalWeightKg\x12#\n" +
	"\rbooster_count\x18\f \x01(\x05R\fboosterCount\x12+\n" +
	"\x11destination_count\x18\r \x01(\x05R\x10destinationCount\x12J\n" +
	"\tsparkline\x18\x0e \x01(\v2'.fitglue.models.activity.EntrySparklineH\x00R\tsparkline\x88\x01\x01\x12)\n" +
	"\x0eavg_heart_rate\x18\x0f \x01(\x05H\x01R\favgHeartRate\x88\x01\x01\x12(\n" +
	"\rcalories_kcal\x18\x10 \x01(\x05H\x02R\fcaloriesKcal\x88\x01\x01\x12\x1e\n" +
	"\bpr_label\x18\x11 \x01(\tH\x03R\aprLabel\x88\x01\x01B\f\n" +
	"\n" +
	"_sparklineB\x11\n" +
	"\x0f_avg_heart_rateB\x10\n" +
	"\x0e_calories_kcalB\v\n" +
	"\t_pr_label\"@\n" +
	"\x0eEntrySparkline\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x01R\x06values\"\x9c\x01\n" +
	"\rShowcaseTheme\x12\x19\n" +
	"\btheme_id\x18\x01 \x01(\tR\athemeId\x12.\n" +
	"\x13custom_accent_color\x18\x02 \x01(\tR\x11customAccentColor\x12!\n" +
	"\fanimation_id\x18\x03 \x01(\tR\vanimationId\x12\x1d\n" +
	"\n" +
	"card_style\x18\x04 \x01(\tR\tcardStyle\"6\n" +
	"\fShowcaseLink\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"(\n" +
	"\x12ShowcaseBioCallout\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x8d\n" +
	"\n" +
	"\x0fShowcaseProfile\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12G\n" +
	"\aentries\x18\x04 \x03(\v2-.fitglue.models.activity.ShowcaseProfileEntryR\aentries\x12)\n" +
	"\x10total_activities\x18\x05 \x01(\x05R\x0ftotalActivities\x122\n" +
	"\x15total_distance_meters\x18\x06 \x01(\x01R\x13totalDistanceMeters\x124\n" +
	"\x16total_duration_seconds\x18\a \x01(\x01R\x14totalDurationSeconds\x12H\n" +
	"\x12latest_activity_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x10latestActivityAt\x12\x1d\n" +
	"\n" +
	"total_sets\x18\v \x01(\x05R\ttotalSets\x12\x1d\n" +
	"\n" +
	"total_reps\x18\f \x01(\x05R\ttotalReps\x12&\n" +
	"\x0ftotal_weight_kg\x18\r \x01(\x01R\rtotalWeightKg\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1a\n" +
	"\bsubtitle\x18\x0e \x01(\tR\bsubtitle\x12\x10\n" +
	"\x03bio\x18\x0f \x01(\tR\x03bio\x12.\n" +
	"\x13profile_picture_url\x18\x10 \x01(\tR\x11profilePictureUrl\x12\x18\n" +
	"\avisible\x18\x11 \x01(\bR\avisible\x12<\n" +
	"\x05theme\x18\x12 \x01(\v2&.fitglue.models.activity.ShowcaseThemeR\x05theme\x12/\n" +
	"\x13default_destination\x18\x13 \x01(\bR\x12defaultDestination\x12,\n" +
	"\x12show_photo_gallery\x18\x14 \x01(\bR\x10showPhotoGallery\x12;\n" +
	"\x05links\x18\x15 \x03(\v2%.fitglue.models.activity.ShowcaseLinkR\x05links\x12G\n" +
	"\bcallouts\x18\x16 \x03(\v2+.fitglue.models.activity.ShowcaseBioCalloutR\bcallouts\x12N\n" +
	"\n" +
	"zone_split\x18\x17 \x01(\v2*.fitglue.models.activity.LifetimeZoneSplitH\x00R\tzoneSplit\x88\x01\x01\x12X\n" +
	"\x0estreak_history\x18\x18 \x01(\v2,.fitglue.models.activity.WeeklyStreakHistoryH\x01R\rstreakHistory\x88\x01\x01\x12?\n" +
	"\atop_prs\x18\x19 \x03(\v2&.fitglue.models.activity.ShowcaseTopPRR\x06topPrsB\r\n" +
	"\v_zone_splitB\x11\n" +
	"\x0f_streak_history\"\xeb\x01\n" +
	"\rShowcaseTopPR\x12\x1f\n" +
	"\vrecord_type\x18\x01 \x01(\tR\n" +
	"recordType\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12@\n" +
	"\vachieved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"achievedAt\x88\x01\x01\x12*\n" +
	"\x0eprevious_value\x18\x05 \x01(\x01H\x01R\rpreviousValue\x88\x01\x01B\x0e\n" +
	"\f_achieved_atB\x11\n" +
	"\x0f_previous_value\"\xaa\x01\n" +
	"\x11LifetimeZoneSplit\x12B\n" +
	"\x05zones\x18\x01 \x03(\v2,.fitglue.models.activity.HeartRateZoneBucketR\x05zones\x12;\n" +
	"\vcomputed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"computedAt\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"\x82\x01\n" +
	"\x13WeeklyStreakHistory\x12#\n" +
	"\rweeks_tracked\x18\x01 \x01(\x05R\fweeksTracked\x12!\n" +
	"\fmissed_weeks\x18\x02 \x01(\x05R\vmissedWeeks\x12#\n" +
	"\rweekly_active\x18\x03 \x03(\bR\fweeklyActiveB?Z=github.com/fitglue/server/src/go/pkg/types/pb/models/activityb\x06proto3"

var (
	file_models_activity_uploaded_proto_rawDescOnce sync.Once
	file_models_activity_uploaded_proto_rawDescData []byte
)

func file_models_activity_uploaded_proto_rawDescGZIP() []byte {
	file_models_activity_uploaded_proto_rawDescOnce.Do(func() {
		file_models_activity_uploaded_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_activity_uploaded_proto_rawDesc), len(file_models_activity_uploaded_proto_rawDesc)))
	})
	return file_models_activity_uploaded_proto_rawDescData
}

var file_models_activity_uploaded_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_models_activity_uploaded_proto_goTypes = []any{
	(*UploadedActivityRecord)(nil), // 0: fitglue.models.activity.UploadedActivityRecord
	(*ShowcasedActivity)(nil),      // 1: fitglue.models.activity.ShowcasedActivity
	(*ShowcaseProfileEntry)(nil),   // 2: fitglue.models.activity.ShowcaseProfileEntry
	(*EntrySparkline)(nil),         // 3: fitglue.models.activity.EntrySparkline
	(*ShowcaseTheme)(nil),          // 4: fitglue.models.activity.ShowcaseTheme
	(*ShowcaseLink)(nil),           // 5: fitglue.models.activity.ShowcaseLink
	(*ShowcaseBioCallout)(nil),     // 6: fitglue.models.activity.ShowcaseBioCallout
	(*ShowcaseProfile)(nil),        // 7: fitglue.models.activity.ShowcaseProfile
	(*ShowcaseTopPR)(nil),          // 8: fitglue.models.activity.ShowcaseTopPR
	(*LifetimeZoneSplit)(nil),      // 9: fitglue.models.activity.LifetimeZoneSplit
	(*WeeklyStreakHistory)(nil),    // 10: fitglue.models.activity.WeeklyStreakHistory
	(ActivitySource)(0),            // 11: fitglue.models.activity.ActivitySource
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
	(plugin.DestinationType)(0),    // 13: fitglue.models.plugin.DestinationType
	(ActivityType)(0),              // 14: fitglue.models.activity.ActivityType
	(*StandardizedActivity)(nil),   // 15: fitglue.models.activity.StandardizedActivity
	(*ActivityEnrichments)(nil),    // 16: fitglue.models.activity.ActivityEnrichments
	(*HeartRateZoneBucket)(nil),    // 17: fitglue.models.activity.HeartRateZoneBucket
}
var file_models_activity_uploaded_proto_depIdxs = []int32{
	11, // 0: fitglue.models.activity.UploadedActivityRecord.source:type_name -> fitglue.models.activity.ActivitySource
	12, // 1: fitglue.models.activity.UploadedActivityRecord.start_time:type_name -> google.protobuf.Timestamp
	13, // 2: fitglue.models.activity.UploadedActivityRecord.destination:type_name -> fitglue.models.plugin.DestinationType
	12, // 3: fitglue.models.activity.UploadedActivityRecord.uploaded_at:type_name -> google.protobuf.Timestamp
	14, // 4: fitglue.models.activity.ShowcasedActivity.activity_type:type_name -> fitglue.models.activity.ActivityType
	11, // 5: fitglue.models.activity.ShowcasedActivity.source:type_name -> fitglue.models.activity.ActivitySource
	12, // 6: fitglue.models.activity.ShowcasedActivity.start_time:type_name -> google.protobuf.Timestamp
	15, // 7: fitglue.models.activity.ShowcasedActivity.activity_data:type_name -> fitglue.models.activity.StandardizedActivity
	12, // 8: fitglue.models.activity.ShowcasedActivity.created_at:type_name -> google.protobuf.Timestamp
	12, // 9: fitglue.models.activity.ShowcasedActivity.expires_at:type_name -> google.protobuf.Timestamp
	16, // 10: fitglue.models.activity.ShowcasedActivity.enrichments:type_name -> fitglue.models.activity.ActivityEnrichments
	14, // 11: fitglue.models.activity.ShowcaseProfileEntry.activity_type:type_name -> fitglue.models.activity.ActivityType
	11, // 12: fitglue.models.activity.ShowcaseProfileEntry.source:type_name -> fitglue.models.activity.ActivitySource
	12, // 13: fitglue.models.activity.ShowcaseProfileEntry.start_time:type_name -> google.protobuf.Timestamp
	3,  // 14: fitglue.models.activity.ShowcaseProfileEntry.sparkline:type_name -> fitglue.models.activity.EntrySparkline
	2,  // 15: fitglue.models.activity.ShowcaseProfile.entries:type_name -> fitglue.models.activity.ShowcaseProfileEntry
	12, // 16: fitglue.models.activity.ShowcaseProfile.latest_activity_at:type_name -> google.protobuf.Timestamp
	12, // 17: fitglue.models.activity.ShowcaseProfile.created_at:type_name -> google.protobuf.Timestamp
	12, // 18: fitglue.models.activity.ShowcaseProfile.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 19: fitglue.models.activity.ShowcaseProfile.theme:type_name -> fitglue.models.activity.ShowcaseTheme
	5,  // 20: fitglue.models.activity.ShowcaseProfile.links:type_name -> fitglue.models.activity.ShowcaseLink
	6,  // 21: fitglue.models.activity.ShowcaseProfile.callouts:type_name -> fitglue.models.activity.ShowcaseBioCallout
	9,  // 22: fitglue.models.activity.ShowcaseProfile.zone_split:type_name -> fitglue.models.activity.LifetimeZoneSplit
	10, // 23: fitglue.models.activity.ShowcaseProfile.streak_history:type_name -> fitglue.models.activity.WeeklyStreakHistory
	8,  // 24: fitglue.models.activity.ShowcaseProfile.top_prs:type_name -> fitglue.models.activity.ShowcaseTopPR
	12, // 25: fitglue.models.activity.ShowcaseTopPR.achieved_at:type_name -> google.protobuf.Timestamp
	17, // 26: fitglue.models.activity.LifetimeZoneSplit.zones:type_name -> fitglue.models.activity.HeartRateZoneBucket
	12, // 27: fitglue.models.activity.LifetimeZoneSplit.computed_at:type_name -> google.protobuf.Timestamp
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_models_activity_uploaded_proto_init() }
func file_models_activity_uploaded_proto_init() {
	if File_models_activity_uploaded_proto != nil {
		return
	}
	file_models_activity_source_proto_init()
	file_models_activity_standardized_proto_init()
	file_models_activity_enrichments_proto_init()
	file_models_activity_uploaded_proto_msgTypes[1].OneofWrappers = []any{}
	file_models_activity_uploaded_proto_msgTypes[2].OneofWrappers = []any{}
	file_models_activity_uploaded_proto_msgTypes[7].OneofWrappers = []any{}
	file_models_activity_uploaded_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_activity_uploaded_proto_rawDesc), len(file_models_activity_uploaded_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_activity_uploaded_proto_goTypes,
		DependencyIndexes: file_models_activity_uploaded_proto_depIdxs,
		MessageInfos:      file_models_activity_uploaded_proto_msgTypes,
	}.Build()
	File_models_activity_uploaded_proto = out.File
	file_models_activity_uploaded_proto_goTypes = nil
	file_models_activity_uploaded_proto_depIdxs = nil
}
