// Code generated by generate-enum-formatters.ts. DO NOT EDIT.
package formatters

import (
	"strings"

	pbactivity "github.com/fitglue/server/src/go/pkg/types/pb/models/activity"
	pbevents "github.com/fitglue/server/src/go/pkg/types/pb/models/events"
	pbpipeline "github.com/fitglue/server/src/go/pkg/types/pb/models/pipeline"
	pbplugin "github.com/fitglue/server/src/go/pkg/types/pb/models/plugin"
	pbuser "github.com/fitglue/server/src/go/pkg/types/pb/models/user"
)

func FormatActivityType(value pbactivity.ActivityType) string {
	switch value {
	case pbactivity.ActivityType_ACTIVITY_TYPE_UNSPECIFIED:
		return "Workout"
	case pbactivity.ActivityType_ACTIVITY_TYPE_ALPINE_SKI:
		return "Alpine Ski"
	case pbactivity.ActivityType_ACTIVITY_TYPE_BACKCOUNTRY_SKI:
		return "Backcountry Ski"
	case pbactivity.ActivityType_ACTIVITY_TYPE_BADMINTON:
		return "Badminton"
	case pbactivity.ActivityType_ACTIVITY_TYPE_CANOEING:
		return "Canoeing"
	case pbactivity.ActivityType_ACTIVITY_TYPE_CROSSFIT:
		return "Crossfit"
	case pbactivity.ActivityType_ACTIVITY_TYPE_EBIKE_RIDE:
		return "E-Bike Ride"
	case pbactivity.ActivityType_ACTIVITY_TYPE_ELLIPTICAL:
		return "Elliptical"
	case pbactivity.ActivityType_ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE:
		return "E-Mountain Bike Ride"
	case pbactivity.ActivityType_ACTIVITY_TYPE_GOLF:
		return "Golf"
	case pbactivity.ActivityType_ACTIVITY_TYPE_GRAVEL_RIDE:
		return "Gravel Ride"
	case pbactivity.ActivityType_ACTIVITY_TYPE_HANDCYCLE:
		return "Handcycle"
	case pbactivity.ActivityType_ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING:
		return "HIIT"
	case pbactivity.ActivityType_ACTIVITY_TYPE_HIKE:
		return "Hike"
	case pbactivity.ActivityType_ACTIVITY_TYPE_ICE_SKATE:
		return "Ice Skate"
	case pbactivity.ActivityType_ACTIVITY_TYPE_INLINE_SKATE:
		return "Inline Skate"
	case pbactivity.ActivityType_ACTIVITY_TYPE_KAYAKING:
		return "Kayaking"
	case pbactivity.ActivityType_ACTIVITY_TYPE_KITESURF:
		return "Kitesurf"
	case pbactivity.ActivityType_ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE:
		return "Mountain Bike Ride"
	case pbactivity.ActivityType_ACTIVITY_TYPE_NORDIC_SKI:
		return "Nordic Ski"
	case pbactivity.ActivityType_ACTIVITY_TYPE_PICKLEBALL:
		return "Pickleball"
	case pbactivity.ActivityType_ACTIVITY_TYPE_PILATES:
		return "Pilates"
	case pbactivity.ActivityType_ACTIVITY_TYPE_RACQUETBALL:
		return "Racquetball"
	case pbactivity.ActivityType_ACTIVITY_TYPE_RIDE:
		return "Ride"
	case pbactivity.ActivityType_ACTIVITY_TYPE_ROCK_CLIMBING:
		return "Rock Climbing"
	case pbactivity.ActivityType_ACTIVITY_TYPE_ROLLER_SKI:
		return "Roller Ski"
	case pbactivity.ActivityType_ACTIVITY_TYPE_ROWING:
		return "Rowing"
	case pbactivity.ActivityType_ACTIVITY_TYPE_RUN:
		return "Run"
	case pbactivity.ActivityType_ACTIVITY_TYPE_SAIL:
		return "Sail"
	case pbactivity.ActivityType_ACTIVITY_TYPE_SKATEBOARD:
		return "Skateboard"
	case pbactivity.ActivityType_ACTIVITY_TYPE_SNOWBOARD:
		return "Snowboard"
	case pbactivity.ActivityType_ACTIVITY_TYPE_SNOWSHOE:
		return "Snowshoe"
	case pbactivity.ActivityType_ACTIVITY_TYPE_SOCCER:
		return "Soccer"
	case pbactivity.ActivityType_ACTIVITY_TYPE_SQUASH:
		return "Squash"
	case pbactivity.ActivityType_ACTIVITY_TYPE_STAIR_STEPPER:
		return "Stair Stepper"
	case pbactivity.ActivityType_ACTIVITY_TYPE_STAND_UP_PADDLING:
		return "Stand Up Paddling"
	case pbactivity.ActivityType_ACTIVITY_TYPE_SURFING:
		return "Surfing"
	case pbactivity.ActivityType_ACTIVITY_TYPE_SWIM:
		return "Swim"
	case pbactivity.ActivityType_ACTIVITY_TYPE_TABLE_TENNIS:
		return "Table Tennis"
	case pbactivity.ActivityType_ACTIVITY_TYPE_TENNIS:
		return "Tennis"
	case pbactivity.ActivityType_ACTIVITY_TYPE_TRAIL_RUN:
		return "Trail Run"
	case pbactivity.ActivityType_ACTIVITY_TYPE_VELOMOBILE:
		return "Velomobile"
	case pbactivity.ActivityType_ACTIVITY_TYPE_VIRTUAL_RIDE:
		return "Virtual Ride"
	case pbactivity.ActivityType_ACTIVITY_TYPE_VIRTUAL_ROW:
		return "Virtual Row"
	case pbactivity.ActivityType_ACTIVITY_TYPE_VIRTUAL_RUN:
		return "Virtual Run"
	case pbactivity.ActivityType_ACTIVITY_TYPE_WALK:
		return "Walk"
	case pbactivity.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING:
		return "Weight Training"
	case pbactivity.ActivityType_ACTIVITY_TYPE_WHEELCHAIR:
		return "Wheelchair"
	case pbactivity.ActivityType_ACTIVITY_TYPE_WINDSURF:
		return "Windsurf"
	case pbactivity.ActivityType_ACTIVITY_TYPE_WORKOUT:
		return "Workout"
	case pbactivity.ActivityType_ACTIVITY_TYPE_YOGA:
		return "Yoga"
	default:
		return "Workout"
	}
}

func ParseActivityType(input string) pbactivity.ActivityType {
	// Try exact proto enum name first (fast path)
	if v, ok := pbactivity.ActivityType_value[input]; ok {
		return pbactivity.ActivityType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbactivity.ActivityType{
		"activity_type_unspecified":         pbactivity.ActivityType_ACTIVITY_TYPE_UNSPECIFIED,
		"unspecified":                       pbactivity.ActivityType_ACTIVITY_TYPE_UNSPECIFIED,
		"workout":                           pbactivity.ActivityType_ACTIVITY_TYPE_UNSPECIFIED,
		"activity_type_alpine_ski":          pbactivity.ActivityType_ACTIVITY_TYPE_ALPINE_SKI,
		"alpine_ski":                        pbactivity.ActivityType_ACTIVITY_TYPE_ALPINE_SKI,
		"alpine ski":                        pbactivity.ActivityType_ACTIVITY_TYPE_ALPINE_SKI,
		"activity_type_backcountry_ski":     pbactivity.ActivityType_ACTIVITY_TYPE_BACKCOUNTRY_SKI,
		"backcountry_ski":                   pbactivity.ActivityType_ACTIVITY_TYPE_BACKCOUNTRY_SKI,
		"backcountry ski":                   pbactivity.ActivityType_ACTIVITY_TYPE_BACKCOUNTRY_SKI,
		"activity_type_badminton":           pbactivity.ActivityType_ACTIVITY_TYPE_BADMINTON,
		"badminton":                         pbactivity.ActivityType_ACTIVITY_TYPE_BADMINTON,
		"activity_type_canoeing":            pbactivity.ActivityType_ACTIVITY_TYPE_CANOEING,
		"canoeing":                          pbactivity.ActivityType_ACTIVITY_TYPE_CANOEING,
		"activity_type_crossfit":            pbactivity.ActivityType_ACTIVITY_TYPE_CROSSFIT,
		"crossfit":                          pbactivity.ActivityType_ACTIVITY_TYPE_CROSSFIT,
		"activity_type_ebike_ride":          pbactivity.ActivityType_ACTIVITY_TYPE_EBIKE_RIDE,
		"ebike_ride":                        pbactivity.ActivityType_ACTIVITY_TYPE_EBIKE_RIDE,
		"e-bike ride":                       pbactivity.ActivityType_ACTIVITY_TYPE_EBIKE_RIDE,
		"activity_type_elliptical":          pbactivity.ActivityType_ACTIVITY_TYPE_ELLIPTICAL,
		"elliptical":                        pbactivity.ActivityType_ACTIVITY_TYPE_ELLIPTICAL,
		"activity_type_emountain_bike_ride": pbactivity.ActivityType_ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE,
		"emountain_bike_ride":               pbactivity.ActivityType_ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE,
		"e-mountain bike ride":              pbactivity.ActivityType_ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE,
		"activity_type_golf":                pbactivity.ActivityType_ACTIVITY_TYPE_GOLF,
		"golf":                              pbactivity.ActivityType_ACTIVITY_TYPE_GOLF,
		"activity_type_gravel_ride":         pbactivity.ActivityType_ACTIVITY_TYPE_GRAVEL_RIDE,
		"gravel_ride":                       pbactivity.ActivityType_ACTIVITY_TYPE_GRAVEL_RIDE,
		"gravel ride":                       pbactivity.ActivityType_ACTIVITY_TYPE_GRAVEL_RIDE,
		"activity_type_handcycle":           pbactivity.ActivityType_ACTIVITY_TYPE_HANDCYCLE,
		"handcycle":                         pbactivity.ActivityType_ACTIVITY_TYPE_HANDCYCLE,
		"activity_type_high_intensity_interval_training": pbactivity.ActivityType_ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING,
		"high_intensity_interval_training":               pbactivity.ActivityType_ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING,
		"hiit":                                           pbactivity.ActivityType_ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING,
		"activity_type_hike":                             pbactivity.ActivityType_ACTIVITY_TYPE_HIKE,
		"hike":                                           pbactivity.ActivityType_ACTIVITY_TYPE_HIKE,
		"activity_type_ice_skate":                        pbactivity.ActivityType_ACTIVITY_TYPE_ICE_SKATE,
		"ice_skate":                                      pbactivity.ActivityType_ACTIVITY_TYPE_ICE_SKATE,
		"ice skate":                                      pbactivity.ActivityType_ACTIVITY_TYPE_ICE_SKATE,
		"activity_type_inline_skate":                     pbactivity.ActivityType_ACTIVITY_TYPE_INLINE_SKATE,
		"inline_skate":                                   pbactivity.ActivityType_ACTIVITY_TYPE_INLINE_SKATE,
		"inline skate":                                   pbactivity.ActivityType_ACTIVITY_TYPE_INLINE_SKATE,
		"activity_type_kayaking":                         pbactivity.ActivityType_ACTIVITY_TYPE_KAYAKING,
		"kayaking":                                       pbactivity.ActivityType_ACTIVITY_TYPE_KAYAKING,
		"activity_type_kitesurf":                         pbactivity.ActivityType_ACTIVITY_TYPE_KITESURF,
		"kitesurf":                                       pbactivity.ActivityType_ACTIVITY_TYPE_KITESURF,
		"activity_type_mountain_bike_ride":               pbactivity.ActivityType_ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE,
		"mountain_bike_ride":                             pbactivity.ActivityType_ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE,
		"mountain bike ride":                             pbactivity.ActivityType_ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE,
		"activity_type_nordic_ski":                       pbactivity.ActivityType_ACTIVITY_TYPE_NORDIC_SKI,
		"nordic_ski":                                     pbactivity.ActivityType_ACTIVITY_TYPE_NORDIC_SKI,
		"nordic ski":                                     pbactivity.ActivityType_ACTIVITY_TYPE_NORDIC_SKI,
		"activity_type_pickleball":                       pbactivity.ActivityType_ACTIVITY_TYPE_PICKLEBALL,
		"pickleball":                                     pbactivity.ActivityType_ACTIVITY_TYPE_PICKLEBALL,
		"activity_type_pilates":                          pbactivity.ActivityType_ACTIVITY_TYPE_PILATES,
		"pilates":                                        pbactivity.ActivityType_ACTIVITY_TYPE_PILATES,
		"activity_type_racquetball":                      pbactivity.ActivityType_ACTIVITY_TYPE_RACQUETBALL,
		"racquetball":                                    pbactivity.ActivityType_ACTIVITY_TYPE_RACQUETBALL,
		"activity_type_ride":                             pbactivity.ActivityType_ACTIVITY_TYPE_RIDE,
		"ride":                                           pbactivity.ActivityType_ACTIVITY_TYPE_RIDE,
		"activity_type_rock_climbing":                    pbactivity.ActivityType_ACTIVITY_TYPE_ROCK_CLIMBING,
		"rock_climbing":                                  pbactivity.ActivityType_ACTIVITY_TYPE_ROCK_CLIMBING,
		"rock climbing":                                  pbactivity.ActivityType_ACTIVITY_TYPE_ROCK_CLIMBING,
		"activity_type_roller_ski":                       pbactivity.ActivityType_ACTIVITY_TYPE_ROLLER_SKI,
		"roller_ski":                                     pbactivity.ActivityType_ACTIVITY_TYPE_ROLLER_SKI,
		"roller ski":                                     pbactivity.ActivityType_ACTIVITY_TYPE_ROLLER_SKI,
		"activity_type_rowing":                           pbactivity.ActivityType_ACTIVITY_TYPE_ROWING,
		"rowing":                                         pbactivity.ActivityType_ACTIVITY_TYPE_ROWING,
		"activity_type_run":                              pbactivity.ActivityType_ACTIVITY_TYPE_RUN,
		"run":                                            pbactivity.ActivityType_ACTIVITY_TYPE_RUN,
		"activity_type_sail":                             pbactivity.ActivityType_ACTIVITY_TYPE_SAIL,
		"sail":                                           pbactivity.ActivityType_ACTIVITY_TYPE_SAIL,
		"activity_type_skateboard":                       pbactivity.ActivityType_ACTIVITY_TYPE_SKATEBOARD,
		"skateboard":                                     pbactivity.ActivityType_ACTIVITY_TYPE_SKATEBOARD,
		"activity_type_snowboard":                        pbactivity.ActivityType_ACTIVITY_TYPE_SNOWBOARD,
		"snowboard":                                      pbactivity.ActivityType_ACTIVITY_TYPE_SNOWBOARD,
		"activity_type_snowshoe":                         pbactivity.ActivityType_ACTIVITY_TYPE_SNOWSHOE,
		"snowshoe":                                       pbactivity.ActivityType_ACTIVITY_TYPE_SNOWSHOE,
		"activity_type_soccer":                           pbactivity.ActivityType_ACTIVITY_TYPE_SOCCER,
		"soccer":                                         pbactivity.ActivityType_ACTIVITY_TYPE_SOCCER,
		"activity_type_squash":                           pbactivity.ActivityType_ACTIVITY_TYPE_SQUASH,
		"squash":                                         pbactivity.ActivityType_ACTIVITY_TYPE_SQUASH,
		"activity_type_stair_stepper":                    pbactivity.ActivityType_ACTIVITY_TYPE_STAIR_STEPPER,
		"stair_stepper":                                  pbactivity.ActivityType_ACTIVITY_TYPE_STAIR_STEPPER,
		"stair stepper":                                  pbactivity.ActivityType_ACTIVITY_TYPE_STAIR_STEPPER,
		"activity_type_stand_up_paddling":                pbactivity.ActivityType_ACTIVITY_TYPE_STAND_UP_PADDLING,
		"stand_up_paddling":                              pbactivity.ActivityType_ACTIVITY_TYPE_STAND_UP_PADDLING,
		"stand up paddling":                              pbactivity.ActivityType_ACTIVITY_TYPE_STAND_UP_PADDLING,
		"activity_type_surfing":                          pbactivity.ActivityType_ACTIVITY_TYPE_SURFING,
		"surfing":                                        pbactivity.ActivityType_ACTIVITY_TYPE_SURFING,
		"activity_type_swim":                             pbactivity.ActivityType_ACTIVITY_TYPE_SWIM,
		"swim":                                           pbactivity.ActivityType_ACTIVITY_TYPE_SWIM,
		"activity_type_table_tennis":                     pbactivity.ActivityType_ACTIVITY_TYPE_TABLE_TENNIS,
		"table_tennis":                                   pbactivity.ActivityType_ACTIVITY_TYPE_TABLE_TENNIS,
		"table tennis":                                   pbactivity.ActivityType_ACTIVITY_TYPE_TABLE_TENNIS,
		"activity_type_tennis":                           pbactivity.ActivityType_ACTIVITY_TYPE_TENNIS,
		"tennis":                                         pbactivity.ActivityType_ACTIVITY_TYPE_TENNIS,
		"activity_type_trail_run":                        pbactivity.ActivityType_ACTIVITY_TYPE_TRAIL_RUN,
		"trail_run":                                      pbactivity.ActivityType_ACTIVITY_TYPE_TRAIL_RUN,
		"trail run":                                      pbactivity.ActivityType_ACTIVITY_TYPE_TRAIL_RUN,
		"activity_type_velomobile":                       pbactivity.ActivityType_ACTIVITY_TYPE_VELOMOBILE,
		"velomobile":                                     pbactivity.ActivityType_ACTIVITY_TYPE_VELOMOBILE,
		"activity_type_virtual_ride":                     pbactivity.ActivityType_ACTIVITY_TYPE_VIRTUAL_RIDE,
		"virtual_ride":                                   pbactivity.ActivityType_ACTIVITY_TYPE_VIRTUAL_RIDE,
		"virtual ride":                                   pbactivity.ActivityType_ACTIVITY_TYPE_VIRTUAL_RIDE,
		"activity_type_virtual_row":                      pbactivity.ActivityType_ACTIVITY_TYPE_VIRTUAL_ROW,
		"virtual_row":                                    pbactivity.ActivityType_ACTIVITY_TYPE_VIRTUAL_ROW,
		"virtual row":                                    pbactivity.ActivityType_ACTIVITY_TYPE_VIRTUAL_ROW,
		"activity_type_virtual_run":                      pbactivity.ActivityType_ACTIVITY_TYPE_VIRTUAL_RUN,
		"virtual_run":                                    pbactivity.ActivityType_ACTIVITY_TYPE_VIRTUAL_RUN,
		"virtual run":                                    pbactivity.ActivityType_ACTIVITY_TYPE_VIRTUAL_RUN,
		"activity_type_walk":                             pbactivity.ActivityType_ACTIVITY_TYPE_WALK,
		"walk":                                           pbactivity.ActivityType_ACTIVITY_TYPE_WALK,
		"activity_type_weight_training":                  pbactivity.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING,
		"weight_training":                                pbactivity.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING,
		"weight training":                                pbactivity.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING,
		"activity_type_wheelchair":                       pbactivity.ActivityType_ACTIVITY_TYPE_WHEELCHAIR,
		"wheelchair":                                     pbactivity.ActivityType_ACTIVITY_TYPE_WHEELCHAIR,
		"activity_type_windsurf":                         pbactivity.ActivityType_ACTIVITY_TYPE_WINDSURF,
		"windsurf":                                       pbactivity.ActivityType_ACTIVITY_TYPE_WINDSURF,
		"activity_type_workout":                          pbactivity.ActivityType_ACTIVITY_TYPE_WORKOUT,
		"activity_type_yoga":                             pbactivity.ActivityType_ACTIVITY_TYPE_YOGA,
		"yoga":                                           pbactivity.ActivityType_ACTIVITY_TYPE_YOGA,
		"running":                                        pbactivity.ActivityType_ACTIVITY_TYPE_RUN,
		"cycling":                                        pbactivity.ActivityType_ACTIVITY_TYPE_RIDE,
		"biking":                                         pbactivity.ActivityType_ACTIVITY_TYPE_RIDE,
		"bike":                                           pbactivity.ActivityType_ACTIVITY_TYPE_RIDE,
		"swimming":                                       pbactivity.ActivityType_ACTIVITY_TYPE_SWIM,
		"walking":                                        pbactivity.ActivityType_ACTIVITY_TYPE_WALK,
		"hiking":                                         pbactivity.ActivityType_ACTIVITY_TYPE_HIKE,
		"weights":                                        pbactivity.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING,
		"weighttraining":                                 pbactivity.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING,
		"strength":                                       pbactivity.ActivityType_ACTIVITY_TYPE_WEIGHT_TRAINING,
		"trailrun":                                       pbactivity.ActivityType_ACTIVITY_TYPE_TRAIL_RUN,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbactivity.ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func FormatMuscleGroup(value pbactivity.MuscleGroup) string {
	switch value {
	case pbactivity.MuscleGroup_MUSCLE_GROUP_UNSPECIFIED:
		return "Unknown"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_ABDOMINALS:
		return "Abdominals"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_SHOULDERS:
		return "Shoulders"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_BICEPS:
		return "Biceps"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_TRICEPS:
		return "Triceps"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_FOREARMS:
		return "Forearms"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_QUADRICEPS:
		return "Quadriceps"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_HAMSTRINGS:
		return "Hamstrings"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_CALVES:
		return "Calves"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_GLUTES:
		return "Glutes"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_ABDUCTORS:
		return "Abductors"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_ADDUCTORS:
		return "Adductors"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_LATS:
		return "Lats"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_UPPER_BACK:
		return "Upper Back"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_TRAPS:
		return "Traps"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_LOWER_BACK:
		return "Lower Back"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_CHEST:
		return "Chest"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_CARDIO:
		return "Cardio"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_NECK:
		return "Neck"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_FULL_BODY:
		return "Full Body"
	case pbactivity.MuscleGroup_MUSCLE_GROUP_OTHER:
		return "Other"
	default:
		return "Unknown"
	}
}

func ParseMuscleGroup(input string) pbactivity.MuscleGroup {
	// Try exact proto enum name first (fast path)
	if v, ok := pbactivity.MuscleGroup_value[input]; ok {
		return pbactivity.MuscleGroup(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbactivity.MuscleGroup{
		"muscle_group_unspecified": pbactivity.MuscleGroup_MUSCLE_GROUP_UNSPECIFIED,
		"unspecified":              pbactivity.MuscleGroup_MUSCLE_GROUP_UNSPECIFIED,
		"unknown":                  pbactivity.MuscleGroup_MUSCLE_GROUP_UNSPECIFIED,
		"muscle_group_abdominals":  pbactivity.MuscleGroup_MUSCLE_GROUP_ABDOMINALS,
		"abdominals":               pbactivity.MuscleGroup_MUSCLE_GROUP_ABDOMINALS,
		"muscle_group_shoulders":   pbactivity.MuscleGroup_MUSCLE_GROUP_SHOULDERS,
		"shoulders":                pbactivity.MuscleGroup_MUSCLE_GROUP_SHOULDERS,
		"muscle_group_biceps":      pbactivity.MuscleGroup_MUSCLE_GROUP_BICEPS,
		"biceps":                   pbactivity.MuscleGroup_MUSCLE_GROUP_BICEPS,
		"muscle_group_triceps":     pbactivity.MuscleGroup_MUSCLE_GROUP_TRICEPS,
		"triceps":                  pbactivity.MuscleGroup_MUSCLE_GROUP_TRICEPS,
		"muscle_group_forearms":    pbactivity.MuscleGroup_MUSCLE_GROUP_FOREARMS,
		"forearms":                 pbactivity.MuscleGroup_MUSCLE_GROUP_FOREARMS,
		"muscle_group_quadriceps":  pbactivity.MuscleGroup_MUSCLE_GROUP_QUADRICEPS,
		"quadriceps":               pbactivity.MuscleGroup_MUSCLE_GROUP_QUADRICEPS,
		"muscle_group_hamstrings":  pbactivity.MuscleGroup_MUSCLE_GROUP_HAMSTRINGS,
		"hamstrings":               pbactivity.MuscleGroup_MUSCLE_GROUP_HAMSTRINGS,
		"muscle_group_calves":      pbactivity.MuscleGroup_MUSCLE_GROUP_CALVES,
		"calves":                   pbactivity.MuscleGroup_MUSCLE_GROUP_CALVES,
		"muscle_group_glutes":      pbactivity.MuscleGroup_MUSCLE_GROUP_GLUTES,
		"glutes":                   pbactivity.MuscleGroup_MUSCLE_GROUP_GLUTES,
		"muscle_group_abductors":   pbactivity.MuscleGroup_MUSCLE_GROUP_ABDUCTORS,
		"abductors":                pbactivity.MuscleGroup_MUSCLE_GROUP_ABDUCTORS,
		"muscle_group_adductors":   pbactivity.MuscleGroup_MUSCLE_GROUP_ADDUCTORS,
		"adductors":                pbactivity.MuscleGroup_MUSCLE_GROUP_ADDUCTORS,
		"muscle_group_lats":        pbactivity.MuscleGroup_MUSCLE_GROUP_LATS,
		"lats":                     pbactivity.MuscleGroup_MUSCLE_GROUP_LATS,
		"muscle_group_upper_back":  pbactivity.MuscleGroup_MUSCLE_GROUP_UPPER_BACK,
		"upper_back":               pbactivity.MuscleGroup_MUSCLE_GROUP_UPPER_BACK,
		"upper back":               pbactivity.MuscleGroup_MUSCLE_GROUP_UPPER_BACK,
		"muscle_group_traps":       pbactivity.MuscleGroup_MUSCLE_GROUP_TRAPS,
		"traps":                    pbactivity.MuscleGroup_MUSCLE_GROUP_TRAPS,
		"muscle_group_lower_back":  pbactivity.MuscleGroup_MUSCLE_GROUP_LOWER_BACK,
		"lower_back":               pbactivity.MuscleGroup_MUSCLE_GROUP_LOWER_BACK,
		"lower back":               pbactivity.MuscleGroup_MUSCLE_GROUP_LOWER_BACK,
		"muscle_group_chest":       pbactivity.MuscleGroup_MUSCLE_GROUP_CHEST,
		"chest":                    pbactivity.MuscleGroup_MUSCLE_GROUP_CHEST,
		"muscle_group_cardio":      pbactivity.MuscleGroup_MUSCLE_GROUP_CARDIO,
		"cardio":                   pbactivity.MuscleGroup_MUSCLE_GROUP_CARDIO,
		"muscle_group_neck":        pbactivity.MuscleGroup_MUSCLE_GROUP_NECK,
		"neck":                     pbactivity.MuscleGroup_MUSCLE_GROUP_NECK,
		"muscle_group_full_body":   pbactivity.MuscleGroup_MUSCLE_GROUP_FULL_BODY,
		"full_body":                pbactivity.MuscleGroup_MUSCLE_GROUP_FULL_BODY,
		"full body":                pbactivity.MuscleGroup_MUSCLE_GROUP_FULL_BODY,
		"muscle_group_other":       pbactivity.MuscleGroup_MUSCLE_GROUP_OTHER,
		"other":                    pbactivity.MuscleGroup_MUSCLE_GROUP_OTHER,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbactivity.MuscleGroup_MUSCLE_GROUP_UNSPECIFIED
}

func FormatDestination(value pbplugin.DestinationType) string {
	switch value {
	case pbplugin.DestinationType_DESTINATION_UNSPECIFIED:
		return "Unknown"
	case pbplugin.DestinationType_DESTINATION_STRAVA:
		return "Strava"
	case pbplugin.DestinationType_DESTINATION_SHOWCASE:
		return "Showcase"
	case pbplugin.DestinationType_DESTINATION_HEVY:
		return "Hevy"
	case pbplugin.DestinationType_DESTINATION_TRAININGPEAKS:
		return "TrainingPeaks"
	case pbplugin.DestinationType_DESTINATION_INTERVALS:
		return "Intervals.icu"
	case pbplugin.DestinationType_DESTINATION_GOOGLESHEETS:
		return "Google Sheets"
	case pbplugin.DestinationType_DESTINATION_GITHUB:
		return "GitHub"
	case pbplugin.DestinationType_DESTINATION_MOCK:
		return "Mock"
	default:
		return "Unknown"
	}
}

func ParseDestination(input string) pbplugin.DestinationType {
	// Try exact proto enum name first (fast path)
	if v, ok := pbplugin.DestinationType_value[input]; ok {
		return pbplugin.DestinationType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbplugin.DestinationType{
		"destination_unspecified":   pbplugin.DestinationType_DESTINATION_UNSPECIFIED,
		"unspecified":               pbplugin.DestinationType_DESTINATION_UNSPECIFIED,
		"unknown":                   pbplugin.DestinationType_DESTINATION_UNSPECIFIED,
		"destination_strava":        pbplugin.DestinationType_DESTINATION_STRAVA,
		"strava":                    pbplugin.DestinationType_DESTINATION_STRAVA,
		"destination_showcase":      pbplugin.DestinationType_DESTINATION_SHOWCASE,
		"showcase":                  pbplugin.DestinationType_DESTINATION_SHOWCASE,
		"destination_hevy":          pbplugin.DestinationType_DESTINATION_HEVY,
		"hevy":                      pbplugin.DestinationType_DESTINATION_HEVY,
		"destination_trainingpeaks": pbplugin.DestinationType_DESTINATION_TRAININGPEAKS,
		"trainingpeaks":             pbplugin.DestinationType_DESTINATION_TRAININGPEAKS,
		"destination_intervals":     pbplugin.DestinationType_DESTINATION_INTERVALS,
		"intervals":                 pbplugin.DestinationType_DESTINATION_INTERVALS,
		"intervals.icu":             pbplugin.DestinationType_DESTINATION_INTERVALS,
		"destination_googlesheets":  pbplugin.DestinationType_DESTINATION_GOOGLESHEETS,
		"googlesheets":              pbplugin.DestinationType_DESTINATION_GOOGLESHEETS,
		"google sheets":             pbplugin.DestinationType_DESTINATION_GOOGLESHEETS,
		"destination_github":        pbplugin.DestinationType_DESTINATION_GITHUB,
		"github":                    pbplugin.DestinationType_DESTINATION_GITHUB,
		"destination_mock":          pbplugin.DestinationType_DESTINATION_MOCK,
		"mock":                      pbplugin.DestinationType_DESTINATION_MOCK,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbplugin.DestinationType_DESTINATION_UNSPECIFIED
}

func FormatCloudEventType(value pbevents.CloudEventType) string {
	switch value {
	case pbevents.CloudEventType_CLOUD_EVENT_TYPE_UNSPECIFIED:
		return "Unspecified"
	case pbevents.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_CREATED:
		return "Activity Created"
	case pbevents.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED:
		return "Activity Enriched"
	case pbevents.CloudEventType_CLOUD_EVENT_TYPE_JOB_ROUTED:
		return "Job Routed"
	case pbevents.CloudEventType_CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION:
		return "Fitbit Notification"
	case pbevents.CloudEventType_CLOUD_EVENT_TYPE_ENRICHMENT_LAG:
		return "Enrichment Lag"
	case pbevents.CloudEventType_CLOUD_EVENT_TYPE_INPUT_RESOLVED:
		return "Input Resolved"
	case pbevents.CloudEventType_CLOUD_EVENT_TYPE_PARKRUN_RESULTS:
		return "Parkrun Results"
	default:
		return "Unknown"
	}
}

func ParseCloudEventType(input string) pbevents.CloudEventType {
	// Try exact proto enum name first (fast path)
	if v, ok := pbevents.CloudEventType_value[input]; ok {
		return pbevents.CloudEventType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbevents.CloudEventType{
		"cloud_event_type_unspecified":         pbevents.CloudEventType_CLOUD_EVENT_TYPE_UNSPECIFIED,
		"unspecified":                          pbevents.CloudEventType_CLOUD_EVENT_TYPE_UNSPECIFIED,
		"cloud_event_type_activity_created":    pbevents.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_CREATED,
		"activity_created":                     pbevents.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_CREATED,
		"activity created":                     pbevents.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_CREATED,
		"cloud_event_type_activity_enriched":   pbevents.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED,
		"activity_enriched":                    pbevents.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED,
		"activity enriched":                    pbevents.CloudEventType_CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED,
		"cloud_event_type_job_routed":          pbevents.CloudEventType_CLOUD_EVENT_TYPE_JOB_ROUTED,
		"job_routed":                           pbevents.CloudEventType_CLOUD_EVENT_TYPE_JOB_ROUTED,
		"job routed":                           pbevents.CloudEventType_CLOUD_EVENT_TYPE_JOB_ROUTED,
		"cloud_event_type_fitbit_notification": pbevents.CloudEventType_CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION,
		"fitbit_notification":                  pbevents.CloudEventType_CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION,
		"fitbit notification":                  pbevents.CloudEventType_CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION,
		"cloud_event_type_enrichment_lag":      pbevents.CloudEventType_CLOUD_EVENT_TYPE_ENRICHMENT_LAG,
		"enrichment_lag":                       pbevents.CloudEventType_CLOUD_EVENT_TYPE_ENRICHMENT_LAG,
		"enrichment lag":                       pbevents.CloudEventType_CLOUD_EVENT_TYPE_ENRICHMENT_LAG,
		"cloud_event_type_input_resolved":      pbevents.CloudEventType_CLOUD_EVENT_TYPE_INPUT_RESOLVED,
		"input_resolved":                       pbevents.CloudEventType_CLOUD_EVENT_TYPE_INPUT_RESOLVED,
		"input resolved":                       pbevents.CloudEventType_CLOUD_EVENT_TYPE_INPUT_RESOLVED,
		"cloud_event_type_parkrun_results":     pbevents.CloudEventType_CLOUD_EVENT_TYPE_PARKRUN_RESULTS,
		"parkrun_results":                      pbevents.CloudEventType_CLOUD_EVENT_TYPE_PARKRUN_RESULTS,
		"parkrun results":                      pbevents.CloudEventType_CLOUD_EVENT_TYPE_PARKRUN_RESULTS,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbevents.CloudEventType_CLOUD_EVENT_TYPE_UNSPECIFIED
}

func FormatCloudEventSource(value pbevents.CloudEventSource) string {
	switch value {
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_UNSPECIFIED:
		return "Unspecified"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_HEVY:
		return "Hevy"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_WEBHOOK:
		return "Fitbit Webhook"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_INGEST:
		return "Fitbit Ingest"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_ENRICHER:
		return "Enricher"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_ROUTER:
		return "Router"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_INPUTS_HANDLER:
		return "Inputs Handler"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_PARKRUN_RESULTS:
		return "Parkrun Results"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_FILE_UPLOAD:
		return "File Upload"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_STRAVA:
		return "Strava"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_OURA:
		return "Oura"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_POLAR_WEBHOOK:
		return "Polar Webhook"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_WAHOO:
		return "Wahoo"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_PIPELINE_SPLITTER:
		return "Pipeline Splitter"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_GITHUB:
		return "Github"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_APPLE_HEALTH:
		return "Apple Health"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_HEALTH_CONNECT:
		return "Health Connect"
	case pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_MOCK:
		return "Mock"
	default:
		return "Unknown"
	}
}

func ParseCloudEventSource(input string) pbevents.CloudEventSource {
	// Try exact proto enum name first (fast path)
	if v, ok := pbevents.CloudEventSource_value[input]; ok {
		return pbevents.CloudEventSource(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbevents.CloudEventSource{
		"cloud_event_source_unspecified":       pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_UNSPECIFIED,
		"unspecified":                          pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_UNSPECIFIED,
		"cloud_event_source_hevy":              pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_HEVY,
		"hevy":                                 pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_HEVY,
		"cloud_event_source_fitbit_webhook":    pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_WEBHOOK,
		"fitbit_webhook":                       pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_WEBHOOK,
		"fitbit webhook":                       pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_WEBHOOK,
		"cloud_event_source_fitbit_ingest":     pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_INGEST,
		"fitbit_ingest":                        pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_INGEST,
		"fitbit ingest":                        pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_FITBIT_INGEST,
		"cloud_event_source_enricher":          pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_ENRICHER,
		"enricher":                             pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_ENRICHER,
		"cloud_event_source_router":            pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_ROUTER,
		"router":                               pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_ROUTER,
		"cloud_event_source_inputs_handler":    pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_INPUTS_HANDLER,
		"inputs_handler":                       pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_INPUTS_HANDLER,
		"inputs handler":                       pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_INPUTS_HANDLER,
		"cloud_event_source_parkrun_results":   pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_PARKRUN_RESULTS,
		"parkrun_results":                      pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_PARKRUN_RESULTS,
		"parkrun results":                      pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_PARKRUN_RESULTS,
		"cloud_event_source_file_upload":       pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_FILE_UPLOAD,
		"file_upload":                          pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_FILE_UPLOAD,
		"file upload":                          pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_FILE_UPLOAD,
		"cloud_event_source_strava":            pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_STRAVA,
		"strava":                               pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_STRAVA,
		"cloud_event_source_oura":              pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_OURA,
		"oura":                                 pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_OURA,
		"cloud_event_source_polar_webhook":     pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_POLAR_WEBHOOK,
		"polar_webhook":                        pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_POLAR_WEBHOOK,
		"polar webhook":                        pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_POLAR_WEBHOOK,
		"cloud_event_source_wahoo":             pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_WAHOO,
		"wahoo":                                pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_WAHOO,
		"cloud_event_source_pipeline_splitter": pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_PIPELINE_SPLITTER,
		"pipeline_splitter":                    pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_PIPELINE_SPLITTER,
		"pipeline splitter":                    pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_PIPELINE_SPLITTER,
		"cloud_event_source_github":            pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_GITHUB,
		"github":                               pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_GITHUB,
		"cloud_event_source_apple_health":      pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_APPLE_HEALTH,
		"apple_health":                         pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_APPLE_HEALTH,
		"apple health":                         pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_APPLE_HEALTH,
		"cloud_event_source_health_connect":    pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_HEALTH_CONNECT,
		"health_connect":                       pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_HEALTH_CONNECT,
		"health connect":                       pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_HEALTH_CONNECT,
		"cloud_event_source_mock":              pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_MOCK,
		"mock":                                 pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_MOCK,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbevents.CloudEventSource_CLOUD_EVENT_SOURCE_UNSPECIFIED
}

func FormatActivitySource(value pbactivity.ActivitySource) string {
	switch value {
	case pbactivity.ActivitySource_SOURCE_UNSPECIFIED:
		return "Unspecified"
	case pbactivity.ActivitySource_SOURCE_HEVY:
		return "Hevy"
	case pbactivity.ActivitySource_SOURCE_FITBIT:
		return "Fitbit"
	case pbactivity.ActivitySource_SOURCE_PARKRUN_RESULTS:
		return "Parkrun Results"
	case pbactivity.ActivitySource_SOURCE_FILE_UPLOAD:
		return "File Upload"
	case pbactivity.ActivitySource_SOURCE_STRAVA:
		return "Strava"
	case pbactivity.ActivitySource_SOURCE_GARMIN:
		return "Garmin"
	case pbactivity.ActivitySource_SOURCE_APPLE_HEALTH:
		return "Apple Health"
	case pbactivity.ActivitySource_SOURCE_HEALTH_CONNECT:
		return "Health Connect"
	case pbactivity.ActivitySource_SOURCE_OURA:
		return "Oura"
	case pbactivity.ActivitySource_SOURCE_POLAR:
		return "Polar"
	case pbactivity.ActivitySource_SOURCE_WAHOO:
		return "Wahoo"
	case pbactivity.ActivitySource_SOURCE_INTERVALS:
		return "Intervals"
	case pbactivity.ActivitySource_SOURCE_TRAININGPEAKS:
		return "Trainingpeaks"
	case pbactivity.ActivitySource_SOURCE_GOOGLESHEETS:
		return "Googlesheets"
	case pbactivity.ActivitySource_SOURCE_GITHUB:
		return "Github"
	case pbactivity.ActivitySource_SOURCE_TEST:
		return "Test"
	default:
		return "Unknown"
	}
}

func ParseActivitySource(input string) pbactivity.ActivitySource {
	// Try exact proto enum name first (fast path)
	if v, ok := pbactivity.ActivitySource_value[input]; ok {
		return pbactivity.ActivitySource(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbactivity.ActivitySource{
		"source_unspecified":     pbactivity.ActivitySource_SOURCE_UNSPECIFIED,
		"unspecified":            pbactivity.ActivitySource_SOURCE_UNSPECIFIED,
		"source_hevy":            pbactivity.ActivitySource_SOURCE_HEVY,
		"hevy":                   pbactivity.ActivitySource_SOURCE_HEVY,
		"source_fitbit":          pbactivity.ActivitySource_SOURCE_FITBIT,
		"fitbit":                 pbactivity.ActivitySource_SOURCE_FITBIT,
		"source_parkrun_results": pbactivity.ActivitySource_SOURCE_PARKRUN_RESULTS,
		"parkrun_results":        pbactivity.ActivitySource_SOURCE_PARKRUN_RESULTS,
		"parkrun results":        pbactivity.ActivitySource_SOURCE_PARKRUN_RESULTS,
		"source_file_upload":     pbactivity.ActivitySource_SOURCE_FILE_UPLOAD,
		"file_upload":            pbactivity.ActivitySource_SOURCE_FILE_UPLOAD,
		"file upload":            pbactivity.ActivitySource_SOURCE_FILE_UPLOAD,
		"source_strava":          pbactivity.ActivitySource_SOURCE_STRAVA,
		"strava":                 pbactivity.ActivitySource_SOURCE_STRAVA,
		"source_garmin":          pbactivity.ActivitySource_SOURCE_GARMIN,
		"garmin":                 pbactivity.ActivitySource_SOURCE_GARMIN,
		"source_apple_health":    pbactivity.ActivitySource_SOURCE_APPLE_HEALTH,
		"apple_health":           pbactivity.ActivitySource_SOURCE_APPLE_HEALTH,
		"apple health":           pbactivity.ActivitySource_SOURCE_APPLE_HEALTH,
		"source_health_connect":  pbactivity.ActivitySource_SOURCE_HEALTH_CONNECT,
		"health_connect":         pbactivity.ActivitySource_SOURCE_HEALTH_CONNECT,
		"health connect":         pbactivity.ActivitySource_SOURCE_HEALTH_CONNECT,
		"source_oura":            pbactivity.ActivitySource_SOURCE_OURA,
		"oura":                   pbactivity.ActivitySource_SOURCE_OURA,
		"source_polar":           pbactivity.ActivitySource_SOURCE_POLAR,
		"polar":                  pbactivity.ActivitySource_SOURCE_POLAR,
		"source_wahoo":           pbactivity.ActivitySource_SOURCE_WAHOO,
		"wahoo":                  pbactivity.ActivitySource_SOURCE_WAHOO,
		"source_intervals":       pbactivity.ActivitySource_SOURCE_INTERVALS,
		"intervals":              pbactivity.ActivitySource_SOURCE_INTERVALS,
		"source_trainingpeaks":   pbactivity.ActivitySource_SOURCE_TRAININGPEAKS,
		"trainingpeaks":          pbactivity.ActivitySource_SOURCE_TRAININGPEAKS,
		"source_googlesheets":    pbactivity.ActivitySource_SOURCE_GOOGLESHEETS,
		"googlesheets":           pbactivity.ActivitySource_SOURCE_GOOGLESHEETS,
		"source_github":          pbactivity.ActivitySource_SOURCE_GITHUB,
		"github":                 pbactivity.ActivitySource_SOURCE_GITHUB,
		"source_test":            pbactivity.ActivitySource_SOURCE_TEST,
		"test":                   pbactivity.ActivitySource_SOURCE_TEST,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbactivity.ActivitySource_SOURCE_UNSPECIFIED
}

func FormatEnricherProviderType(value pbplugin.EnricherProviderType) string {
	switch value {
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED:
		return "Unknown"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_FITBIT_HEART_RATE:
		return "Fitbit Heart Rate"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_WORKOUT_SUMMARY:
		return "Workout Summary"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP:
		return "Muscle Heatmap"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_SOURCE_LINK:
		return "Source Link"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_VIRTUAL_GPS:
		return "Virtual Gps"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_TYPE_MAPPER:
		return "Type Mapper"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PARKRUN:
		return "Parkrun"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_CONDITION_MATCHER:
		return "Condition Matcher"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AUTO_INCREMENT:
		return "Auto Increment"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_USER_INPUT:
		return "User Input"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ACTIVITY_FILTER:
		return "Activity Filter"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_LOGIC_GATE:
		return "Logic Gate"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_SUMMARY:
		return "Heart Rate Summary"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AI_COMPANION:
		return "Ai Companion"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PACE_SUMMARY:
		return "Pace Summary"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_CADENCE_SUMMARY:
		return "Cadence Summary"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_POWER_SUMMARY:
		return "Power Summary"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_SPEED_SUMMARY:
		return "Speed Summary"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PERSONAL_RECORDS:
		return "Personal Records"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_TRAINING_LOAD:
		return "Training Load"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_SPOTIFY_TRACKS:
		return "Spotify Tracks"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_WEATHER:
		return "Weather"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ELEVATION_SUMMARY:
		return "Elevation Summary"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_LOCATION_NAMING:
		return "Location Naming"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP_IMAGE:
		return "Muscle Heatmap Image"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ROUTE_THUMBNAIL:
		return "Route Thumbnail"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AI_BANNER:
		return "Ai Banner"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_FIT_FILE_HEART_RATE:
		return "Fit File Heart Rate"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_HYBRID_RACE_TAGGER:
		return "Hybrid Race Tagger"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_RUNNING_DYNAMICS:
		return "Running Dynamics"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_ZONES:
		return "Heart Rate Zones"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_CALORIES_BURNED:
		return "Calories Burned"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_GOAL_TRACKER:
		return "Goal Tracker"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_STREAK_TRACKER:
		return "Streak Tracker"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_DISTANCE_MILESTONES:
		return "Distance Milestones"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_RECOVERY_ADVISOR:
		return "Recovery Advisor"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_EFFORT_SCORE:
		return "Effort Score"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_INTERVALS:
		return "Intervals"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PHOTO_UPLOAD:
		return "Photo Upload"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MANUAL_WORKOUT_ENTRY:
		return "Manual Workout Entry"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AI_ACTIVITY_TYPE:
		return "Ai Activity Type"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ICAL_TITLE:
		return "Ical Title"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_TEMPERATURE_SUMMARY:
		return "Temperature Summary"
	case pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MOCK:
		return "Mock"
	default:
		return "Unknown"
	}
}

func ParseEnricherProviderType(input string) pbplugin.EnricherProviderType {
	// Try exact proto enum name first (fast path)
	if v, ok := pbplugin.EnricherProviderType_value[input]; ok {
		return pbplugin.EnricherProviderType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbplugin.EnricherProviderType{
		"enricher_provider_unspecified":          pbplugin.EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED,
		"unspecified":                            pbplugin.EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED,
		"unknown":                                pbplugin.EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED,
		"enricher_provider_fitbit_heart_rate":    pbplugin.EnricherProviderType_ENRICHER_PROVIDER_FITBIT_HEART_RATE,
		"fitbit_heart_rate":                      pbplugin.EnricherProviderType_ENRICHER_PROVIDER_FITBIT_HEART_RATE,
		"fitbit heart rate":                      pbplugin.EnricherProviderType_ENRICHER_PROVIDER_FITBIT_HEART_RATE,
		"enricher_provider_workout_summary":      pbplugin.EnricherProviderType_ENRICHER_PROVIDER_WORKOUT_SUMMARY,
		"workout_summary":                        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_WORKOUT_SUMMARY,
		"workout summary":                        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_WORKOUT_SUMMARY,
		"enricher_provider_muscle_heatmap":       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP,
		"muscle_heatmap":                         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP,
		"muscle heatmap":                         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP,
		"enricher_provider_source_link":          pbplugin.EnricherProviderType_ENRICHER_PROVIDER_SOURCE_LINK,
		"source_link":                            pbplugin.EnricherProviderType_ENRICHER_PROVIDER_SOURCE_LINK,
		"source link":                            pbplugin.EnricherProviderType_ENRICHER_PROVIDER_SOURCE_LINK,
		"enricher_provider_virtual_gps":          pbplugin.EnricherProviderType_ENRICHER_PROVIDER_VIRTUAL_GPS,
		"virtual_gps":                            pbplugin.EnricherProviderType_ENRICHER_PROVIDER_VIRTUAL_GPS,
		"virtual gps":                            pbplugin.EnricherProviderType_ENRICHER_PROVIDER_VIRTUAL_GPS,
		"enricher_provider_type_mapper":          pbplugin.EnricherProviderType_ENRICHER_PROVIDER_TYPE_MAPPER,
		"type_mapper":                            pbplugin.EnricherProviderType_ENRICHER_PROVIDER_TYPE_MAPPER,
		"type mapper":                            pbplugin.EnricherProviderType_ENRICHER_PROVIDER_TYPE_MAPPER,
		"enricher_provider_parkrun":              pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PARKRUN,
		"parkrun":                                pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PARKRUN,
		"enricher_provider_condition_matcher":    pbplugin.EnricherProviderType_ENRICHER_PROVIDER_CONDITION_MATCHER,
		"condition_matcher":                      pbplugin.EnricherProviderType_ENRICHER_PROVIDER_CONDITION_MATCHER,
		"condition matcher":                      pbplugin.EnricherProviderType_ENRICHER_PROVIDER_CONDITION_MATCHER,
		"enricher_provider_auto_increment":       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AUTO_INCREMENT,
		"auto_increment":                         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AUTO_INCREMENT,
		"auto increment":                         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AUTO_INCREMENT,
		"enricher_provider_user_input":           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_USER_INPUT,
		"user_input":                             pbplugin.EnricherProviderType_ENRICHER_PROVIDER_USER_INPUT,
		"user input":                             pbplugin.EnricherProviderType_ENRICHER_PROVIDER_USER_INPUT,
		"enricher_provider_activity_filter":      pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ACTIVITY_FILTER,
		"activity_filter":                        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ACTIVITY_FILTER,
		"activity filter":                        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ACTIVITY_FILTER,
		"enricher_provider_logic_gate":           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_LOGIC_GATE,
		"logic_gate":                             pbplugin.EnricherProviderType_ENRICHER_PROVIDER_LOGIC_GATE,
		"logic gate":                             pbplugin.EnricherProviderType_ENRICHER_PROVIDER_LOGIC_GATE,
		"enricher_provider_heart_rate_summary":   pbplugin.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_SUMMARY,
		"heart_rate_summary":                     pbplugin.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_SUMMARY,
		"heart rate summary":                     pbplugin.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_SUMMARY,
		"enricher_provider_ai_companion":         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AI_COMPANION,
		"ai_companion":                           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AI_COMPANION,
		"ai companion":                           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AI_COMPANION,
		"enricher_provider_pace_summary":         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PACE_SUMMARY,
		"pace_summary":                           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PACE_SUMMARY,
		"pace summary":                           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PACE_SUMMARY,
		"enricher_provider_cadence_summary":      pbplugin.EnricherProviderType_ENRICHER_PROVIDER_CADENCE_SUMMARY,
		"cadence_summary":                        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_CADENCE_SUMMARY,
		"cadence summary":                        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_CADENCE_SUMMARY,
		"enricher_provider_power_summary":        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_POWER_SUMMARY,
		"power_summary":                          pbplugin.EnricherProviderType_ENRICHER_PROVIDER_POWER_SUMMARY,
		"power summary":                          pbplugin.EnricherProviderType_ENRICHER_PROVIDER_POWER_SUMMARY,
		"enricher_provider_speed_summary":        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_SPEED_SUMMARY,
		"speed_summary":                          pbplugin.EnricherProviderType_ENRICHER_PROVIDER_SPEED_SUMMARY,
		"speed summary":                          pbplugin.EnricherProviderType_ENRICHER_PROVIDER_SPEED_SUMMARY,
		"enricher_provider_personal_records":     pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PERSONAL_RECORDS,
		"personal_records":                       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PERSONAL_RECORDS,
		"personal records":                       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PERSONAL_RECORDS,
		"enricher_provider_training_load":        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_TRAINING_LOAD,
		"training_load":                          pbplugin.EnricherProviderType_ENRICHER_PROVIDER_TRAINING_LOAD,
		"training load":                          pbplugin.EnricherProviderType_ENRICHER_PROVIDER_TRAINING_LOAD,
		"enricher_provider_spotify_tracks":       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_SPOTIFY_TRACKS,
		"spotify_tracks":                         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_SPOTIFY_TRACKS,
		"spotify tracks":                         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_SPOTIFY_TRACKS,
		"enricher_provider_weather":              pbplugin.EnricherProviderType_ENRICHER_PROVIDER_WEATHER,
		"weather":                                pbplugin.EnricherProviderType_ENRICHER_PROVIDER_WEATHER,
		"enricher_provider_elevation_summary":    pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ELEVATION_SUMMARY,
		"elevation_summary":                      pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ELEVATION_SUMMARY,
		"elevation summary":                      pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ELEVATION_SUMMARY,
		"enricher_provider_location_naming":      pbplugin.EnricherProviderType_ENRICHER_PROVIDER_LOCATION_NAMING,
		"location_naming":                        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_LOCATION_NAMING,
		"location naming":                        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_LOCATION_NAMING,
		"enricher_provider_muscle_heatmap_image": pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP_IMAGE,
		"muscle_heatmap_image":                   pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP_IMAGE,
		"muscle heatmap image":                   pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MUSCLE_HEATMAP_IMAGE,
		"enricher_provider_route_thumbnail":      pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ROUTE_THUMBNAIL,
		"route_thumbnail":                        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ROUTE_THUMBNAIL,
		"route thumbnail":                        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ROUTE_THUMBNAIL,
		"enricher_provider_ai_banner":            pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AI_BANNER,
		"ai_banner":                              pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AI_BANNER,
		"ai banner":                              pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AI_BANNER,
		"enricher_provider_fit_file_heart_rate":  pbplugin.EnricherProviderType_ENRICHER_PROVIDER_FIT_FILE_HEART_RATE,
		"fit_file_heart_rate":                    pbplugin.EnricherProviderType_ENRICHER_PROVIDER_FIT_FILE_HEART_RATE,
		"fit file heart rate":                    pbplugin.EnricherProviderType_ENRICHER_PROVIDER_FIT_FILE_HEART_RATE,
		"enricher_provider_hybrid_race_tagger":   pbplugin.EnricherProviderType_ENRICHER_PROVIDER_HYBRID_RACE_TAGGER,
		"hybrid_race_tagger":                     pbplugin.EnricherProviderType_ENRICHER_PROVIDER_HYBRID_RACE_TAGGER,
		"hybrid race tagger":                     pbplugin.EnricherProviderType_ENRICHER_PROVIDER_HYBRID_RACE_TAGGER,
		"enricher_provider_running_dynamics":     pbplugin.EnricherProviderType_ENRICHER_PROVIDER_RUNNING_DYNAMICS,
		"running_dynamics":                       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_RUNNING_DYNAMICS,
		"running dynamics":                       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_RUNNING_DYNAMICS,
		"enricher_provider_heart_rate_zones":     pbplugin.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_ZONES,
		"heart_rate_zones":                       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_ZONES,
		"heart rate zones":                       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_HEART_RATE_ZONES,
		"enricher_provider_calories_burned":      pbplugin.EnricherProviderType_ENRICHER_PROVIDER_CALORIES_BURNED,
		"calories_burned":                        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_CALORIES_BURNED,
		"calories burned":                        pbplugin.EnricherProviderType_ENRICHER_PROVIDER_CALORIES_BURNED,
		"enricher_provider_goal_tracker":         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_GOAL_TRACKER,
		"goal_tracker":                           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_GOAL_TRACKER,
		"goal tracker":                           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_GOAL_TRACKER,
		"enricher_provider_streak_tracker":       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_STREAK_TRACKER,
		"streak_tracker":                         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_STREAK_TRACKER,
		"streak tracker":                         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_STREAK_TRACKER,
		"enricher_provider_distance_milestones":  pbplugin.EnricherProviderType_ENRICHER_PROVIDER_DISTANCE_MILESTONES,
		"distance_milestones":                    pbplugin.EnricherProviderType_ENRICHER_PROVIDER_DISTANCE_MILESTONES,
		"distance milestones":                    pbplugin.EnricherProviderType_ENRICHER_PROVIDER_DISTANCE_MILESTONES,
		"enricher_provider_recovery_advisor":     pbplugin.EnricherProviderType_ENRICHER_PROVIDER_RECOVERY_ADVISOR,
		"recovery_advisor":                       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_RECOVERY_ADVISOR,
		"recovery advisor":                       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_RECOVERY_ADVISOR,
		"enricher_provider_effort_score":         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_EFFORT_SCORE,
		"effort_score":                           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_EFFORT_SCORE,
		"effort score":                           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_EFFORT_SCORE,
		"enricher_provider_intervals":            pbplugin.EnricherProviderType_ENRICHER_PROVIDER_INTERVALS,
		"intervals":                              pbplugin.EnricherProviderType_ENRICHER_PROVIDER_INTERVALS,
		"enricher_provider_photo_upload":         pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PHOTO_UPLOAD,
		"photo_upload":                           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PHOTO_UPLOAD,
		"photo upload":                           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_PHOTO_UPLOAD,
		"enricher_provider_manual_workout_entry": pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MANUAL_WORKOUT_ENTRY,
		"manual_workout_entry":                   pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MANUAL_WORKOUT_ENTRY,
		"manual workout entry":                   pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MANUAL_WORKOUT_ENTRY,
		"enricher_provider_ai_activity_type":     pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AI_ACTIVITY_TYPE,
		"ai_activity_type":                       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AI_ACTIVITY_TYPE,
		"ai activity type":                       pbplugin.EnricherProviderType_ENRICHER_PROVIDER_AI_ACTIVITY_TYPE,
		"enricher_provider_ical_title":           pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ICAL_TITLE,
		"ical_title":                             pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ICAL_TITLE,
		"ical title":                             pbplugin.EnricherProviderType_ENRICHER_PROVIDER_ICAL_TITLE,
		"enricher_provider_temperature_summary":  pbplugin.EnricherProviderType_ENRICHER_PROVIDER_TEMPERATURE_SUMMARY,
		"temperature_summary":                    pbplugin.EnricherProviderType_ENRICHER_PROVIDER_TEMPERATURE_SUMMARY,
		"temperature summary":                    pbplugin.EnricherProviderType_ENRICHER_PROVIDER_TEMPERATURE_SUMMARY,
		"enricher_provider_mock":                 pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MOCK,
		"mock":                                   pbplugin.EnricherProviderType_ENRICHER_PROVIDER_MOCK,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbplugin.EnricherProviderType_ENRICHER_PROVIDER_UNSPECIFIED
}

func FormatUserTier(value pbuser.UserTier) string {
	switch value {
	case pbuser.UserTier_USER_TIER_UNSPECIFIED:
		return "Hobbyist"
	case pbuser.UserTier_USER_TIER_HOBBYIST:
		return "Hobbyist"
	case pbuser.UserTier_USER_TIER_ATHLETE:
		return "Athlete"
	default:
		return "Hobbyist"
	}
}

func ParseUserTier(input string) pbuser.UserTier {
	// Try exact proto enum name first (fast path)
	if v, ok := pbuser.UserTier_value[input]; ok {
		return pbuser.UserTier(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbuser.UserTier{
		"user_tier_unspecified": pbuser.UserTier_USER_TIER_UNSPECIFIED,
		"unspecified":           pbuser.UserTier_USER_TIER_UNSPECIFIED,
		"hobbyist":              pbuser.UserTier_USER_TIER_UNSPECIFIED,
		"user_tier_hobbyist":    pbuser.UserTier_USER_TIER_HOBBYIST,
		"user_tier_athlete":     pbuser.UserTier_USER_TIER_ATHLETE,
		"athlete":               pbuser.UserTier_USER_TIER_ATHLETE,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbuser.UserTier_USER_TIER_UNSPECIFIED
}

func FormatExecutionStatus(value pbpipeline.ExecutionStatus) string {
	switch value {
	case pbpipeline.ExecutionStatus_STATUS_UNSPECIFIED:
		return "Unspecified"
	case pbpipeline.ExecutionStatus_STATUS_STARTED:
		return "Started"
	case pbpipeline.ExecutionStatus_STATUS_SUCCESS:
		return "Success"
	case pbpipeline.ExecutionStatus_STATUS_FAILED:
		return "Failed"
	case pbpipeline.ExecutionStatus_STATUS_PENDING:
		return "Pending"
	case pbpipeline.ExecutionStatus_STATUS_WAITING:
		return "Waiting"
	case pbpipeline.ExecutionStatus_STATUS_LAGGED_RETRY:
		return "Lagged Retry"
	case pbpipeline.ExecutionStatus_STATUS_SKIPPED:
		return "Skipped"
	default:
		return "Unknown"
	}
}

func ParseExecutionStatus(input string) pbpipeline.ExecutionStatus {
	// Try exact proto enum name first (fast path)
	if v, ok := pbpipeline.ExecutionStatus_value[input]; ok {
		return pbpipeline.ExecutionStatus(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbpipeline.ExecutionStatus{
		"status_unspecified":  pbpipeline.ExecutionStatus_STATUS_UNSPECIFIED,
		"unspecified":         pbpipeline.ExecutionStatus_STATUS_UNSPECIFIED,
		"status_started":      pbpipeline.ExecutionStatus_STATUS_STARTED,
		"started":             pbpipeline.ExecutionStatus_STATUS_STARTED,
		"status_success":      pbpipeline.ExecutionStatus_STATUS_SUCCESS,
		"success":             pbpipeline.ExecutionStatus_STATUS_SUCCESS,
		"status_failed":       pbpipeline.ExecutionStatus_STATUS_FAILED,
		"failed":              pbpipeline.ExecutionStatus_STATUS_FAILED,
		"status_pending":      pbpipeline.ExecutionStatus_STATUS_PENDING,
		"pending":             pbpipeline.ExecutionStatus_STATUS_PENDING,
		"status_waiting":      pbpipeline.ExecutionStatus_STATUS_WAITING,
		"waiting":             pbpipeline.ExecutionStatus_STATUS_WAITING,
		"status_lagged_retry": pbpipeline.ExecutionStatus_STATUS_LAGGED_RETRY,
		"lagged_retry":        pbpipeline.ExecutionStatus_STATUS_LAGGED_RETRY,
		"lagged retry":        pbpipeline.ExecutionStatus_STATUS_LAGGED_RETRY,
		"status_skipped":      pbpipeline.ExecutionStatus_STATUS_SKIPPED,
		"skipped":             pbpipeline.ExecutionStatus_STATUS_SKIPPED,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbpipeline.ExecutionStatus_STATUS_UNSPECIFIED
}

func FormatConfigFieldType(value pbplugin.ConfigFieldType) string {
	switch value {
	case pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_UNSPECIFIED:
		return "Unspecified"
	case pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_STRING:
		return "String"
	case pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_NUMBER:
		return "Number"
	case pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_BOOLEAN:
		return "Boolean"
	case pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_SELECT:
		return "Select"
	case pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_MULTI_SELECT:
		return "Multi Select"
	case pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_KEY_VALUE_MAP:
		return "Key Value Map"
	case pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_DYNAMIC_SELECT:
		return "Dynamic Select"
	default:
		return "String"
	}
}

func ParseConfigFieldType(input string) pbplugin.ConfigFieldType {
	// Try exact proto enum name first (fast path)
	if v, ok := pbplugin.ConfigFieldType_value[input]; ok {
		return pbplugin.ConfigFieldType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbplugin.ConfigFieldType{
		"config_field_type_unspecified":    pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_UNSPECIFIED,
		"unspecified":                      pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_UNSPECIFIED,
		"config_field_type_string":         pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_STRING,
		"string":                           pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_STRING,
		"config_field_type_number":         pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_NUMBER,
		"number":                           pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_NUMBER,
		"config_field_type_boolean":        pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_BOOLEAN,
		"boolean":                          pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_BOOLEAN,
		"config_field_type_select":         pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_SELECT,
		"select":                           pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_SELECT,
		"config_field_type_multi_select":   pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_MULTI_SELECT,
		"multi_select":                     pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_MULTI_SELECT,
		"multi select":                     pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_MULTI_SELECT,
		"config_field_type_key_value_map":  pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_KEY_VALUE_MAP,
		"key_value_map":                    pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_KEY_VALUE_MAP,
		"key value map":                    pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_KEY_VALUE_MAP,
		"config_field_type_dynamic_select": pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_DYNAMIC_SELECT,
		"dynamic_select":                   pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_DYNAMIC_SELECT,
		"dynamic select":                   pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_DYNAMIC_SELECT,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbplugin.ConfigFieldType_CONFIG_FIELD_TYPE_UNSPECIFIED
}

func FormatIntegrationAuthType(value pbplugin.IntegrationAuthType) string {
	switch value {
	case pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_UNSPECIFIED:
		return "Manual"
	case pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_OAUTH:
		return "Oauth"
	case pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_API_KEY:
		return "API Key"
	case pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_APP_SYNC:
		return "App Sync"
	case pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_PUBLIC_ID:
		return "Public ID"
	default:
		return "Manual"
	}
}

func ParseIntegrationAuthType(input string) pbplugin.IntegrationAuthType {
	// Try exact proto enum name first (fast path)
	if v, ok := pbplugin.IntegrationAuthType_value[input]; ok {
		return pbplugin.IntegrationAuthType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbplugin.IntegrationAuthType{
		"integration_auth_type_unspecified": pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_UNSPECIFIED,
		"unspecified":                       pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_UNSPECIFIED,
		"manual":                            pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_UNSPECIFIED,
		"integration_auth_type_oauth":       pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_OAUTH,
		"oauth":                             pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_OAUTH,
		"integration_auth_type_api_key":     pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_API_KEY,
		"api_key":                           pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_API_KEY,
		"api key":                           pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_API_KEY,
		"integration_auth_type_app_sync":    pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_APP_SYNC,
		"app_sync":                          pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_APP_SYNC,
		"app sync":                          pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_APP_SYNC,
		"integration_auth_type_public_id":   pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_PUBLIC_ID,
		"public_id":                         pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_PUBLIC_ID,
		"public id":                         pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_PUBLIC_ID,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbplugin.IntegrationAuthType_INTEGRATION_AUTH_TYPE_UNSPECIFIED
}

func FormatPluginType(value pbplugin.PluginType) string {
	switch value {
	case pbplugin.PluginType_PLUGIN_TYPE_UNSPECIFIED:
		return "Unspecified"
	case pbplugin.PluginType_PLUGIN_TYPE_SOURCE:
		return "Source"
	case pbplugin.PluginType_PLUGIN_TYPE_ENRICHER:
		return "Enricher"
	case pbplugin.PluginType_PLUGIN_TYPE_DESTINATION:
		return "Destination"
	default:
		return "Unknown"
	}
}

func ParsePluginType(input string) pbplugin.PluginType {
	// Try exact proto enum name first (fast path)
	if v, ok := pbplugin.PluginType_value[input]; ok {
		return pbplugin.PluginType(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbplugin.PluginType{
		"plugin_type_unspecified": pbplugin.PluginType_PLUGIN_TYPE_UNSPECIFIED,
		"unspecified":             pbplugin.PluginType_PLUGIN_TYPE_UNSPECIFIED,
		"plugin_type_source":      pbplugin.PluginType_PLUGIN_TYPE_SOURCE,
		"source":                  pbplugin.PluginType_PLUGIN_TYPE_SOURCE,
		"plugin_type_enricher":    pbplugin.PluginType_PLUGIN_TYPE_ENRICHER,
		"enricher":                pbplugin.PluginType_PLUGIN_TYPE_ENRICHER,
		"plugin_type_destination": pbplugin.PluginType_PLUGIN_TYPE_DESTINATION,
		"destination":             pbplugin.PluginType_PLUGIN_TYPE_DESTINATION,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbplugin.PluginType_PLUGIN_TYPE_UNSPECIFIED
}

func FormatMuscleHeatmapPreset(value pbplugin.MuscleHeatmapPreset) string {
	switch value {
	case pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_UNSPECIFIED:
		return "Unspecified"
	case pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_STANDARD:
		return "Standard"
	case pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_POWERLIFTING:
		return "Powerlifting"
	case pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_BODYBUILDING:
		return "Bodybuilding"
	default:
		return "Standard"
	}
}

func ParseMuscleHeatmapPreset(input string) pbplugin.MuscleHeatmapPreset {
	// Try exact proto enum name first (fast path)
	if v, ok := pbplugin.MuscleHeatmapPreset_value[input]; ok {
		return pbplugin.MuscleHeatmapPreset(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbplugin.MuscleHeatmapPreset{
		"muscle_heatmap_preset_unspecified":  pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_UNSPECIFIED,
		"unspecified":                        pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_UNSPECIFIED,
		"muscle_heatmap_preset_standard":     pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_STANDARD,
		"standard":                           pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_STANDARD,
		"muscle_heatmap_preset_powerlifting": pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_POWERLIFTING,
		"powerlifting":                       pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_POWERLIFTING,
		"muscle_heatmap_preset_bodybuilding": pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_BODYBUILDING,
		"bodybuilding":                       pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_BODYBUILDING,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbplugin.MuscleHeatmapPreset_MUSCLE_HEATMAP_PRESET_UNSPECIFIED
}

func FormatMuscleHeatmapStyle(value pbplugin.MuscleHeatmapStyle) string {
	switch value {
	case pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_UNSPECIFIED:
		return "Unspecified"
	case pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_EMOJI_BARS:
		return "Emoji Bars"
	case pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_PERCENTAGE:
		return "Percentage"
	case pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_TEXT_ONLY:
		return "Text Only"
	default:
		return "Emoji Bars"
	}
}

func ParseMuscleHeatmapStyle(input string) pbplugin.MuscleHeatmapStyle {
	// Try exact proto enum name first (fast path)
	if v, ok := pbplugin.MuscleHeatmapStyle_value[input]; ok {
		return pbplugin.MuscleHeatmapStyle(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbplugin.MuscleHeatmapStyle{
		"muscle_heatmap_style_unspecified": pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_UNSPECIFIED,
		"unspecified":                      pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_UNSPECIFIED,
		"muscle_heatmap_style_emoji_bars":  pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_EMOJI_BARS,
		"emoji_bars":                       pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_EMOJI_BARS,
		"emoji bars":                       pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_EMOJI_BARS,
		"muscle_heatmap_style_percentage":  pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_PERCENTAGE,
		"percentage":                       pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_PERCENTAGE,
		"muscle_heatmap_style_text_only":   pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_TEXT_ONLY,
		"text_only":                        pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_TEXT_ONLY,
		"text only":                        pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_TEXT_ONLY,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbplugin.MuscleHeatmapStyle_MUSCLE_HEATMAP_STYLE_UNSPECIFIED
}

func FormatParkrunResultsState(value pbpipeline.ParkrunResultsState) string {
	switch value {
	case pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_UNSPECIFIED:
		return "Unspecified"
	case pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_PENDING:
		return "Pending"
	case pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_COMPLETE:
		return "Complete"
	case pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_EXPIRED:
		return "Expired"
	case pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_IMMEDIATE:
		return "Immediate"
	default:
		return "Pending"
	}
}

func ParseParkrunResultsState(input string) pbpipeline.ParkrunResultsState {
	// Try exact proto enum name first (fast path)
	if v, ok := pbpipeline.ParkrunResultsState_value[input]; ok {
		return pbpipeline.ParkrunResultsState(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbpipeline.ParkrunResultsState{
		"parkrun_results_state_unspecified": pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_UNSPECIFIED,
		"unspecified":                       pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_UNSPECIFIED,
		"parkrun_results_state_pending":     pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_PENDING,
		"pending":                           pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_PENDING,
		"parkrun_results_state_complete":    pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_COMPLETE,
		"complete":                          pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_COMPLETE,
		"parkrun_results_state_expired":     pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_EXPIRED,
		"expired":                           pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_EXPIRED,
		"parkrun_results_state_immediate":   pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_IMMEDIATE,
		"immediate":                         pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_IMMEDIATE,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbpipeline.ParkrunResultsState_PARKRUN_RESULTS_STATE_UNSPECIFIED
}

func FormatVirtualGPSRoute(value pbplugin.VirtualGPSRoute) string {
	switch value {
	case pbplugin.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_UNSPECIFIED:
		return "Unspecified"
	case pbplugin.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_LONDON:
		return "London"
	case pbplugin.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_NYC:
		return "Nyc"
	default:
		return "None"
	}
}

func ParseVirtualGPSRoute(input string) pbplugin.VirtualGPSRoute {
	// Try exact proto enum name first (fast path)
	if v, ok := pbplugin.VirtualGPSRoute_value[input]; ok {
		return pbplugin.VirtualGPSRoute(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbplugin.VirtualGPSRoute{
		"virtual_gps_route_unspecified": pbplugin.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_UNSPECIFIED,
		"unspecified":                   pbplugin.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_UNSPECIFIED,
		"virtual_gps_route_london":      pbplugin.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_LONDON,
		"london":                        pbplugin.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_LONDON,
		"virtual_gps_route_nyc":         pbplugin.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_NYC,
		"nyc":                           pbplugin.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_NYC,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbplugin.VirtualGPSRoute_VIRTUAL_GPS_ROUTE_UNSPECIFIED
}

func FormatWorkoutSummaryFormat(value pbplugin.WorkoutSummaryFormat) string {
	switch value {
	case pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_UNSPECIFIED:
		return "Unspecified"
	case pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_COMPACT:
		return "Compact"
	case pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_DETAILED:
		return "Detailed"
	case pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_VERBOSE:
		return "Verbose"
	default:
		return "Compact"
	}
}

func ParseWorkoutSummaryFormat(input string) pbplugin.WorkoutSummaryFormat {
	// Try exact proto enum name first (fast path)
	if v, ok := pbplugin.WorkoutSummaryFormat_value[input]; ok {
		return pbplugin.WorkoutSummaryFormat(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbplugin.WorkoutSummaryFormat{
		"workout_summary_format_unspecified": pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_UNSPECIFIED,
		"unspecified":                        pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_UNSPECIFIED,
		"workout_summary_format_compact":     pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_COMPACT,
		"compact":                            pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_COMPACT,
		"workout_summary_format_detailed":    pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_DETAILED,
		"detailed":                           pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_DETAILED,
		"workout_summary_format_verbose":     pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_VERBOSE,
		"verbose":                            pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_VERBOSE,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbplugin.WorkoutSummaryFormat_WORKOUT_SUMMARY_FORMAT_UNSPECIFIED
}

func FormatPendingInputStatus(value pbpipeline.PendingInput_Status) string {
	switch value {
	case pbpipeline.PendingInput_STATUS_UNSPECIFIED:
		return "Unspecified"
	case pbpipeline.PendingInput_STATUS_WAITING:
		return "Waiting"
	case pbpipeline.PendingInput_STATUS_COMPLETED:
		return "Completed"
	default:
		return "Waiting"
	}
}

func ParsePendingInputStatus(input string) pbpipeline.PendingInput_Status {
	// Try exact proto enum name first (fast path)
	if v, ok := pbpipeline.PendingInput_Status_value[input]; ok {
		return pbpipeline.PendingInput_Status(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbpipeline.PendingInput_Status{
		"status_unspecified": pbpipeline.PendingInput_STATUS_UNSPECIFIED,
		"unspecified":        pbpipeline.PendingInput_STATUS_UNSPECIFIED,
		"status_waiting":     pbpipeline.PendingInput_STATUS_WAITING,
		"waiting":            pbpipeline.PendingInput_STATUS_WAITING,
		"status_completed":   pbpipeline.PendingInput_STATUS_COMPLETED,
		"completed":          pbpipeline.PendingInput_STATUS_COMPLETED,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbpipeline.PendingInput_STATUS_UNSPECIFIED
}

func FormatPipelineRunStatus(value pbpipeline.PipelineRunStatus) string {
	switch value {
	case pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_UNSPECIFIED:
		return "Unknown"
	case pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_RUNNING:
		return "In Progress"
	case pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_SYNCED:
		return "Synced"
	case pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_PARTIAL:
		return "Partial"
	case pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_FAILED:
		return "Failed"
	case pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_PENDING:
		return "Pending"
	case pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_SKIPPED:
		return "Skipped"
	case pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_ARCHIVED:
		return "Archived"
	case pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_TIER_BLOCKED:
		return "Tier Blocked"
	case pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_CANCELLED:
		return "Cancelled"
	default:
		return "Unknown"
	}
}

func ParsePipelineRunStatus(input string) pbpipeline.PipelineRunStatus {
	// Try exact proto enum name first (fast path)
	if v, ok := pbpipeline.PipelineRunStatus_value[input]; ok {
		return pbpipeline.PipelineRunStatus(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbpipeline.PipelineRunStatus{
		"pipeline_run_status_unspecified":  pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_UNSPECIFIED,
		"unspecified":                      pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_UNSPECIFIED,
		"unknown":                          pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_UNSPECIFIED,
		"pipeline_run_status_running":      pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_RUNNING,
		"running":                          pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_RUNNING,
		"in progress":                      pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_RUNNING,
		"pipeline_run_status_synced":       pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_SYNCED,
		"synced":                           pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_SYNCED,
		"pipeline_run_status_partial":      pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_PARTIAL,
		"partial":                          pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_PARTIAL,
		"pipeline_run_status_failed":       pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_FAILED,
		"failed":                           pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_FAILED,
		"pipeline_run_status_pending":      pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_PENDING,
		"pending":                          pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_PENDING,
		"pipeline_run_status_skipped":      pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_SKIPPED,
		"skipped":                          pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_SKIPPED,
		"pipeline_run_status_archived":     pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_ARCHIVED,
		"archived":                         pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_ARCHIVED,
		"pipeline_run_status_tier_blocked": pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_TIER_BLOCKED,
		"tier_blocked":                     pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_TIER_BLOCKED,
		"tier blocked":                     pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_TIER_BLOCKED,
		"pipeline_run_status_cancelled":    pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_CANCELLED,
		"cancelled":                        pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_CANCELLED,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbpipeline.PipelineRunStatus_PIPELINE_RUN_STATUS_UNSPECIFIED
}

func FormatDestinationStatus(value pbpipeline.DestinationStatus) string {
	switch value {
	case pbpipeline.DestinationStatus_DESTINATION_STATUS_UNSPECIFIED:
		return "Unknown"
	case pbpipeline.DestinationStatus_DESTINATION_STATUS_PENDING:
		return "Pending"
	case pbpipeline.DestinationStatus_DESTINATION_STATUS_SUCCESS:
		return "Success"
	case pbpipeline.DestinationStatus_DESTINATION_STATUS_FAILED:
		return "Failed"
	case pbpipeline.DestinationStatus_DESTINATION_STATUS_SKIPPED:
		return "Skipped"
	default:
		return "Unknown"
	}
}

func ParseDestinationStatus(input string) pbpipeline.DestinationStatus {
	// Try exact proto enum name first (fast path)
	if v, ok := pbpipeline.DestinationStatus_value[input]; ok {
		return pbpipeline.DestinationStatus(v)
	}

	// Case-insensitive lookup via display names, short names, and aliases
	lookup := map[string]pbpipeline.DestinationStatus{
		"destination_status_unspecified": pbpipeline.DestinationStatus_DESTINATION_STATUS_UNSPECIFIED,
		"unspecified":                    pbpipeline.DestinationStatus_DESTINATION_STATUS_UNSPECIFIED,
		"unknown":                        pbpipeline.DestinationStatus_DESTINATION_STATUS_UNSPECIFIED,
		"destination_status_pending":     pbpipeline.DestinationStatus_DESTINATION_STATUS_PENDING,
		"pending":                        pbpipeline.DestinationStatus_DESTINATION_STATUS_PENDING,
		"destination_status_success":     pbpipeline.DestinationStatus_DESTINATION_STATUS_SUCCESS,
		"success":                        pbpipeline.DestinationStatus_DESTINATION_STATUS_SUCCESS,
		"destination_status_failed":      pbpipeline.DestinationStatus_DESTINATION_STATUS_FAILED,
		"failed":                         pbpipeline.DestinationStatus_DESTINATION_STATUS_FAILED,
		"destination_status_skipped":     pbpipeline.DestinationStatus_DESTINATION_STATUS_SKIPPED,
		"skipped":                        pbpipeline.DestinationStatus_DESTINATION_STATUS_SKIPPED,
	}

	normalized := strings.ToLower(strings.TrimSpace(input))
	if v, ok := lookup[normalized]; ok {
		return v
	}
	return pbpipeline.DestinationStatus_DESTINATION_STATUS_UNSPECIFIED
}
