// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: services/pipeline/pipeline.proto

package pipeline

import (
	activity "github.com/fitglue/server/src/go/pkg/types/pb/models/activity"
	pipeline "github.com/fitglue/server/src/go/pkg/types/pb/models/pipeline"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Admin pipeline runs
type AdminListPipelineRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // optional filter
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListPipelineRunsRequest) Reset() {
	*x = AdminListPipelineRunsRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListPipelineRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListPipelineRunsRequest) ProtoMessage() {}

func (x *AdminListPipelineRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListPipelineRunsRequest.ProtoReflect.Descriptor instead.
func (*AdminListPipelineRunsRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *AdminListPipelineRunsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminListPipelineRunsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AdminListPipelineRunsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdminListPipelineRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AdminListPipelineRunsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type AdminListPipelineRunsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Runs          []*pipeline.PipelineRun `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextPageToken string                  `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListPipelineRunsResponse) Reset() {
	*x = AdminListPipelineRunsResponse{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListPipelineRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListPipelineRunsResponse) ProtoMessage() {}

func (x *AdminListPipelineRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListPipelineRunsResponse.ProtoReflect.Descriptor instead.
func (*AdminListPipelineRunsResponse) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *AdminListPipelineRunsResponse) GetRuns() []*pipeline.PipelineRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *AdminListPipelineRunsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListPipelinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesRequest) Reset() {
	*x = ListPipelinesRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesRequest) ProtoMessage() {}

func (x *ListPipelinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesRequest.ProtoReflect.Descriptor instead.
func (*ListPipelinesRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{2}
}

func (x *ListPipelinesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListPipelinesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Pipelines     []*pipeline.PipelineConfig `protobuf:"bytes,1,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesResponse) Reset() {
	*x = ListPipelinesResponse{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesResponse) ProtoMessage() {}

func (x *ListPipelinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesResponse.ProtoReflect.Descriptor instead.
func (*ListPipelinesResponse) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{3}
}

func (x *ListPipelinesResponse) GetPipelines() []*pipeline.PipelineConfig {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

type GetPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRequest) Reset() {
	*x = GetPipelineRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRequest) ProtoMessage() {}

func (x *GetPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{4}
}

func (x *GetPipelineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type CreatePipelineRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	UserId        string                   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pipeline      *pipeline.PipelineConfig `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineRequest) Reset() {
	*x = CreatePipelineRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineRequest) ProtoMessage() {}

func (x *CreatePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineRequest.ProtoReflect.Descriptor instead.
func (*CreatePipelineRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePipelineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePipelineRequest) GetPipeline() *pipeline.PipelineConfig {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type UpdatePipelineRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	UserId        string                   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PipelineId    string                   `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Pipeline      *pipeline.PipelineConfig `protobuf:"bytes,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePipelineRequest) Reset() {
	*x = UpdatePipelineRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePipelineRequest) ProtoMessage() {}

func (x *UpdatePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePipelineRequest.ProtoReflect.Descriptor instead.
func (*UpdatePipelineRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePipelineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *UpdatePipelineRequest) GetPipeline() *pipeline.PipelineConfig {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type DeletePipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePipelineRequest) Reset() {
	*x = DeletePipelineRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePipelineRequest) ProtoMessage() {}

func (x *DeletePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePipelineRequest.ProtoReflect.Descriptor instead.
func (*DeletePipelineRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePipelineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeletePipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type SubmitInputRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PendingInputId string                 `protobuf:"bytes,2,opt,name=pending_input_id,json=pendingInputId,proto3" json:"pending_input_id,omitempty"`
	InputData      map[string]string      `protobuf:"bytes,3,rep,name=input_data,json=inputData,proto3" json:"input_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitInputRequest) Reset() {
	*x = SubmitInputRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitInputRequest) ProtoMessage() {}

func (x *SubmitInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitInputRequest.ProtoReflect.Descriptor instead.
func (*SubmitInputRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitInputRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitInputRequest) GetPendingInputId() string {
	if x != nil {
		return x.PendingInputId
	}
	return ""
}

func (x *SubmitInputRequest) GetInputData() map[string]string {
	if x != nil {
		return x.InputData
	}
	return nil
}

type ListPendingInputsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingInputsRequest) Reset() {
	*x = ListPendingInputsRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingInputsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingInputsRequest) ProtoMessage() {}

func (x *ListPendingInputsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingInputsRequest.ProtoReflect.Descriptor instead.
func (*ListPendingInputsRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{9}
}

func (x *ListPendingInputsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListPendingInputsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Inputs        []*pipeline.PendingInput `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingInputsResponse) Reset() {
	*x = ListPendingInputsResponse{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingInputsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingInputsResponse) ProtoMessage() {}

func (x *ListPendingInputsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingInputsResponse.ProtoReflect.Descriptor instead.
func (*ListPendingInputsResponse) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{10}
}

func (x *ListPendingInputsResponse) GetInputs() []*pipeline.PendingInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type ResolvePendingInputRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PendingInputId string                 `protobuf:"bytes,2,opt,name=pending_input_id,json=pendingInputId,proto3" json:"pending_input_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolvePendingInputRequest) Reset() {
	*x = ResolvePendingInputRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePendingInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePendingInputRequest) ProtoMessage() {}

func (x *ResolvePendingInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePendingInputRequest.ProtoReflect.Descriptor instead.
func (*ResolvePendingInputRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{11}
}

func (x *ResolvePendingInputRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResolvePendingInputRequest) GetPendingInputId() string {
	if x != nil {
		return x.PendingInputId
	}
	return ""
}

type CancelPipelineRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PendingInputId string                 `protobuf:"bytes,2,opt,name=pending_input_id,json=pendingInputId,proto3" json:"pending_input_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelPipelineRequest) Reset() {
	*x = CancelPipelineRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPipelineRequest) ProtoMessage() {}

func (x *CancelPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPipelineRequest.ProtoReflect.Descriptor instead.
func (*CancelPipelineRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{12}
}

func (x *CancelPipelineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelPipelineRequest) GetPendingInputId() string {
	if x != nil {
		return x.PendingInputId
	}
	return ""
}

type CancelPipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPipelineRunRequest) Reset() {
	*x = CancelPipelineRunRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPipelineRunRequest) ProtoMessage() {}

func (x *CancelPipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPipelineRunRequest.ProtoReflect.Descriptor instead.
func (*CancelPipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{13}
}

func (x *CancelPipelineRunRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelPipelineRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RepostActivityRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserId     string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId string                 `protobuf:"bytes,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	// Repost mode: "missed-destination", "retry-destination", "full-pipeline"
	Mode string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// Target destination (required for missed-destination and retry-destination modes)
	Destination   string `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepostActivityRequest) Reset() {
	*x = RepostActivityRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepostActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepostActivityRequest) ProtoMessage() {}

func (x *RepostActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepostActivityRequest.ProtoReflect.Descriptor instead.
func (*RepostActivityRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{14}
}

func (x *RepostActivityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RepostActivityRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *RepostActivityRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RepostActivityRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type RefreshActivitySourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId    string                 `protobuf:"bytes,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshActivitySourceRequest) Reset() {
	*x = RefreshActivitySourceRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshActivitySourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshActivitySourceRequest) ProtoMessage() {}

func (x *RefreshActivitySourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshActivitySourceRequest.ProtoReflect.Descriptor instead.
func (*RefreshActivitySourceRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{15}
}

func (x *RefreshActivitySourceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefreshActivitySourceRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

type InvokeEnricherRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserId     string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId string                 `protobuf:"bytes,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	// provider_name is the enricher provider's registry name (Provider.Name()), e.g.
	// "heart-rate-summary", "weather".
	ProviderName  string `protobuf:"bytes,3,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeEnricherRequest) Reset() {
	*x = InvokeEnricherRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeEnricherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeEnricherRequest) ProtoMessage() {}

func (x *InvokeEnricherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeEnricherRequest.ProtoReflect.Descriptor instead.
func (*InvokeEnricherRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{16}
}

func (x *InvokeEnricherRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InvokeEnricherRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *InvokeEnricherRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

type InvokeEnricherResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The proposed enricher-run layer recorded on the activity. Unset when the enricher
	// ran but produced no layerable change (proposed_created = false).
	Proposed *activity.EnricherRunLayer `protobuf:"bytes,1,opt,name=proposed,proto3" json:"proposed,omitempty"`
	// Preview of the resolved activity if the proposal were accepted: the derived activity
	// with this proposal's contribution folded in and the user-edit overlay applied on top
	// (the overlay still wins). Non-persistent.
	Preview *activity.StandardizedActivity `protobuf:"bytes,2,opt,name=preview,proto3" json:"preview,omitempty"`
	// True when the enricher produced a change that was recorded as a proposal.
	ProposedCreated bool `protobuf:"varint,3,opt,name=proposed_created,json=proposedCreated,proto3" json:"proposed_created,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InvokeEnricherResponse) Reset() {
	*x = InvokeEnricherResponse{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeEnricherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeEnricherResponse) ProtoMessage() {}

func (x *InvokeEnricherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeEnricherResponse.ProtoReflect.Descriptor instead.
func (*InvokeEnricherResponse) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{17}
}

func (x *InvokeEnricherResponse) GetProposed() *activity.EnricherRunLayer {
	if x != nil {
		return x.Proposed
	}
	return nil
}

func (x *InvokeEnricherResponse) GetPreview() *activity.StandardizedActivity {
	if x != nil {
		return x.Preview
	}
	return nil
}

func (x *InvokeEnricherResponse) GetProposedCreated() bool {
	if x != nil {
		return x.ProposedCreated
	}
	return false
}

type AcceptProposedEnricherRunRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserId     string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId string                 `protobuf:"bytes,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	// execution_id identifies the proposed EnricherRunLayer to accept.
	ExecutionId   string `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptProposedEnricherRunRequest) Reset() {
	*x = AcceptProposedEnricherRunRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptProposedEnricherRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptProposedEnricherRunRequest) ProtoMessage() {}

func (x *AcceptProposedEnricherRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptProposedEnricherRunRequest.ProtoReflect.Descriptor instead.
func (*AcceptProposedEnricherRunRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{18}
}

func (x *AcceptProposedEnricherRunRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AcceptProposedEnricherRunRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *AcceptProposedEnricherRunRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type DismissProposedEnricherRunRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserId     string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId string                 `protobuf:"bytes,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	// execution_id identifies the proposed EnricherRunLayer to dismiss.
	ExecutionId   string `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissProposedEnricherRunRequest) Reset() {
	*x = DismissProposedEnricherRunRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissProposedEnricherRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissProposedEnricherRunRequest) ProtoMessage() {}

func (x *DismissProposedEnricherRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissProposedEnricherRunRequest.ProtoReflect.Descriptor instead.
func (*DismissProposedEnricherRunRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{19}
}

func (x *DismissProposedEnricherRunRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DismissProposedEnricherRunRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *DismissProposedEnricherRunRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetPipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRunRequest) Reset() {
	*x = GetPipelineRunRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRunRequest) ProtoMessage() {}

func (x *GetPipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRunRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{20}
}

func (x *GetPipelineRunRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPipelineRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ListPipelineRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=since,proto3,oneof" json:"since,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=until,proto3,oneof" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelineRunsRequest) Reset() {
	*x = ListPipelineRunsRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelineRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelineRunsRequest) ProtoMessage() {}

func (x *ListPipelineRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelineRunsRequest.ProtoReflect.Descriptor instead.
func (*ListPipelineRunsRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{21}
}

func (x *ListPipelineRunsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListPipelineRunsRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *ListPipelineRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPipelineRunsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPipelineRunsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListPipelineRunsRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type ListPipelineRunsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Runs          []*pipeline.PipelineRun `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextPageToken string                  `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelineRunsResponse) Reset() {
	*x = ListPipelineRunsResponse{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelineRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelineRunsResponse) ProtoMessage() {}

func (x *ListPipelineRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelineRunsResponse.ProtoReflect.Descriptor instead.
func (*ListPipelineRunsResponse) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{22}
}

func (x *ListPipelineRunsResponse) GetRuns() []*pipeline.PipelineRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListPipelineRunsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type SourceActivityItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceActivityId string                 `protobuf:"bytes,1,opt,name=source_activity_id,json=sourceActivityId,proto3" json:"source_activity_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	StartTime        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	AlreadySynced    bool                   `protobuf:"varint,5,opt,name=already_synced,json=alreadySynced,proto3" json:"already_synced,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SourceActivityItem) Reset() {
	*x = SourceActivityItem{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceActivityItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceActivityItem) ProtoMessage() {}

func (x *SourceActivityItem) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceActivityItem.ProtoReflect.Descriptor instead.
func (*SourceActivityItem) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{23}
}

func (x *SourceActivityItem) GetSourceActivityId() string {
	if x != nil {
		return x.SourceActivityId
	}
	return ""
}

func (x *SourceActivityItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SourceActivityItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SourceActivityItem) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SourceActivityItem) GetAlreadySynced() bool {
	if x != nil {
		return x.AlreadySynced
	}
	return false
}

type ListSourceActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourceActivitiesRequest) Reset() {
	*x = ListSourceActivitiesRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourceActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourceActivitiesRequest) ProtoMessage() {}

func (x *ListSourceActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourceActivitiesRequest.ProtoReflect.Descriptor instead.
func (*ListSourceActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{24}
}

func (x *ListSourceActivitiesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListSourceActivitiesRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *ListSourceActivitiesRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListSourceActivitiesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSourceActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*SourceActivityItem  `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourceActivitiesResponse) Reset() {
	*x = ListSourceActivitiesResponse{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourceActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourceActivitiesResponse) ProtoMessage() {}

func (x *ListSourceActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourceActivitiesResponse.ProtoReflect.Descriptor instead.
func (*ListSourceActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{25}
}

func (x *ListSourceActivitiesResponse) GetActivities() []*SourceActivityItem {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *ListSourceActivitiesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BackfillActivitiesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PipelineId        string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Source            string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	SourceActivityIds []string               `protobuf:"bytes,4,rep,name=source_activity_ids,json=sourceActivityIds,proto3" json:"source_activity_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BackfillActivitiesRequest) Reset() {
	*x = BackfillActivitiesRequest{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillActivitiesRequest) ProtoMessage() {}

func (x *BackfillActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillActivitiesRequest.ProtoReflect.Descriptor instead.
func (*BackfillActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{26}
}

func (x *BackfillActivitiesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BackfillActivitiesRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *BackfillActivitiesRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BackfillActivitiesRequest) GetSourceActivityIds() []string {
	if x != nil {
		return x.SourceActivityIds
	}
	return nil
}

type BackfillActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueuedCount   int32                  `protobuf:"varint,1,opt,name=queued_count,json=queuedCount,proto3" json:"queued_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillActivitiesResponse) Reset() {
	*x = BackfillActivitiesResponse{}
	mi := &file_services_pipeline_pipeline_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillActivitiesResponse) ProtoMessage() {}

func (x *BackfillActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_pipeline_pipeline_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillActivitiesResponse.ProtoReflect.Descriptor instead.
func (*BackfillActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_services_pipeline_pipeline_proto_rawDescGZIP(), []int{27}
}

func (x *BackfillActivitiesResponse) GetQueuedCount() int32 {
	if x != nil {
		return x.QueuedCount
	}
	return 0
}

var File_services_pipeline_pipeline_proto protoreflect.FileDescriptor

const file_services_pipeline_pipeline_proto_rawDesc = "" +
	"\n" +
	" services/pipeline/pipeline.proto\x12\x19fitglue.services.pipeline\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\"models/activity/standardized.proto\x1a\x1cmodels/activity/record.proto\x1a\x1cmodels/pipeline/config.proto\x1a\x1fmodels/pipeline/execution.proto\x1a#models/pipeline/pending_input.proto\"\x9c\x01\n" +
	"\x1cAdminListPipelineRunsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x81\x01\n" +
	"\x1dAdminListPipelineRunsResponse\x128\n" +
	"\x04runs\x18\x01 \x03(\v2$.fitglue.models.pipeline.PipelineRunR\x04runs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"/\n" +
	"\x14ListPipelinesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"^\n" +
	"\x15ListPipelinesResponse\x12E\n" +
	"\tpipelines\x18\x01 \x03(\v2'.fitglue.models.pipeline.PipelineConfigR\tpipelines\"N\n" +
	"\x12GetPipelineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\"u\n" +
	"\x15CreatePipelineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12C\n" +
	"\bpipeline\x18\x02 \x01(\v2'.fitglue.models.pipeline.PipelineConfigR\bpipeline\"\x96\x01\n" +
	"\x15UpdatePipelineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12C\n" +
	"\bpipeline\x18\x03 \x01(\v2'.fitglue.models.pipeline.PipelineConfigR\bpipeline\"Q\n" +
	"\x15DeletePipelineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\"\xf2\x01\n" +
	"\x12SubmitInputRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10pending_input_id\x18\x02 \x01(\tR\x0ependingInputId\x12[\n" +
	"\n" +
	"input_data\x18\x03 \x03(\v2<.fitglue.services.pipeline.SubmitInputRequest.InputDataEntryR\tinputData\x1a<\n" +
	"\x0eInputDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\x18ListPendingInputsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Z\n" +
	"\x19ListPendingInputsResponse\x12=\n" +
	"\x06inputs\x18\x01 \x03(\v2%.fitglue.models.pipeline.PendingInputR\x06inputs\"_\n" +
	"\x1aResolvePendingInputRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10pending_input_id\x18\x02 \x01(\tR\x0ependingInputId\"Z\n" +
	"\x15CancelPipelineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10pending_input_id\x18\x02 \x01(\tR\x0ependingInputId\"J\n" +
	"\x18CancelPipelineRunRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"\x87\x01\n" +
	"\x15RepostActivityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\tR\n" +
	"activityId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\"X\n" +
	"\x1cRefreshActivitySourceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\tR\n" +
	"activityId\"v\n" +
	"\x15InvokeEnricherRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\tR\n" +
	"activityId\x12#\n" +
	"\rprovider_name\x18\x03 \x01(\tR\fproviderName\"\xd3\x01\n" +
	"\x16InvokeEnricherResponse\x12E\n" +
	"\bproposed\x18\x01 \x01(\v2).fitglue.models.activity.EnricherRunLayerR\bproposed\x12G\n" +
	"\apreview\x18\x02 \x01(\v2-.fitglue.models.activity.StandardizedActivityR\apreview\x12)\n" +
	"\x10proposed_created\x18\x03 \x01(\bR\x0fproposedCreated\"\x7f\n" +
	" AcceptProposedEnricherRunRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\tR\n" +
	"activityId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\"\x80\x01\n" +
	"!DismissProposedEnricherRunRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\tR\n" +
	"activityId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\"G\n" +
	"\x15GetPipelineRunRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"\x8a\x02\n" +
	"\x17ListPipelineRunsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x125\n" +
	"\x05since\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05since\x88\x01\x01\x125\n" +
	"\x05until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x05until\x88\x01\x01B\b\n" +
	"\x06_sinceB\b\n" +
	"\x06_until\"|\n" +
	"\x18ListPipelineRunsResponse\x128\n" +
	"\x04runs\x18\x01 \x03(\v2$.fitglue.models.pipeline.PipelineRunR\x04runs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xce\x01\n" +
	"\x12SourceActivityItem\x12,\n" +
	"\x12source_activity_id\x18\x01 \x01(\tR\x10sourceActivityId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12%\n" +
	"\x0ealready_synced\x18\x05 \x01(\bR\ralreadySynced\"\x8e\x01\n" +
	"\x1bListSourceActivitiesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x95\x01\n" +
	"\x1cListSourceActivitiesResponse\x12M\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2-.fitglue.services.pipeline.SourceActivityItemR\n" +
	"activities\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x9d\x01\n" +
	"\x19BackfillActivitiesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12.\n" +
	"\x13source_activity_ids\x18\x04 \x03(\tR\x11sourceActivityIds\"?\n" +
	"\x1aBackfillActivitiesResponse\x12!\n" +
	"\fqueued_count\x18\x01 \x01(\x05R\vqueuedCount2\xea\x1b\n" +
	"\x0fPipelineService\x12\x99\x01\n" +
	"\rListPipelines\x12/.fitglue.services.pipeline.ListPipelinesRequest\x1a0.fitglue.services.pipeline.ListPipelinesResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v2/users/{user_id}/pipelines\x12\x9a\x01\n" +
	"\vGetPipeline\x12-.fitglue.services.pipeline.GetPipelineRequest\x1a'.fitglue.models.pipeline.PipelineConfig\"3\x82\xd3\xe4\x93\x02-\x12+/v2/users/{user_id}/pipelines/{pipeline_id}\x12\x9c\x01\n" +
	"\x0eCreatePipeline\x120.fitglue.services.pipeline.CreatePipelineRequest\x1a'.fitglue.models.pipeline.PipelineConfig\"/\x82\xd3\xe4\x93\x02):\bpipeline\"\x1d/v2/users/{user_id}/pipelines\x12\xaa\x01\n" +
	"\x0eUpdatePipeline\x120.fitglue.services.pipeline.UpdatePipelineRequest\x1a'.fitglue.models.pipeline.PipelineConfig\"=\x82\xd3\xe4\x93\x027:\bpipeline2+/v2/users/{user_id}/pipelines/{pipeline_id}\x12\x8f\x01\n" +
	"\x0eDeletePipeline\x120.fitglue.services.pipeline.DeletePipelineRequest\x1a\x16.google.protobuf.Empty\"3\x82\xd3\xe4\x93\x02-*+/v2/users/{user_id}/pipelines/{pipeline_id}\x12\x9d\x01\n" +
	"\vSubmitInput\x12-.fitglue.services.pipeline.SubmitInputRequest\x1a\x16.google.protobuf.Empty\"G\x82\xd3\xe4\x93\x02A:\x01*\"</v2/users/{user_id}/pending-inputs/{pending_input_id}/submit\x12\xaa\x01\n" +
	"\x11ListPendingInputs\x123.fitglue.services.pipeline.ListPendingInputsRequest\x1a4.fitglue.services.pipeline.ListPendingInputsResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v2/users/{user_id}/pending-inputs\x12\xae\x01\n" +
	"\x13ResolvePendingInput\x125.fitglue.services.pipeline.ResolvePendingInputRequest\x1a\x16.google.protobuf.Empty\"H\x82\xd3\xe4\x93\x02B:\x01*\"=/v2/users/{user_id}/pending-inputs/{pending_input_id}/resolve\x12\xa3\x01\n" +
	"\x0eCancelPipeline\x120.fitglue.services.pipeline.CancelPipelineRequest\x1a\x16.google.protobuf.Empty\"G\x82\xd3\xe4\x93\x02A:\x01*\"</v2/users/{user_id}/pending-inputs/{pending_input_id}/cancel\x12\x9e\x01\n" +
	"\x11CancelPipelineRun\x123.fitglue.services.pipeline.CancelPipelineRunRequest\x1a\x16.google.protobuf.Empty\"<\x82\xd3\xe4\x93\x026:\x01*\"1/v2/users/{user_id}/pipeline-runs/{run_id}/cancel\x12\x9a\x01\n" +
	"\x0eRepostActivity\x120.fitglue.services.pipeline.RepostActivityRequest\x1a\x16.google.protobuf.Empty\">\x82\xd3\xe4\x93\x028:\x01*\"3/v2/users/{user_id}/activities/{activity_id}/repost\x12\xc4\x01\n" +
	"\x15RefreshActivitySource\x127.fitglue.services.pipeline.RefreshActivitySourceRequest\x1a-.fitglue.models.activity.StandardizedActivity\"C\x82\xd3\xe4\x93\x02=\";/v2/users/{user_id}/activities/{activity_id}/refresh-source\x12\xcc\x01\n" +
	"\x0eInvokeEnricher\x120.fitglue.services.pipeline.InvokeEnricherRequest\x1a1.fitglue.services.pipeline.InvokeEnricherResponse\"U\x82\xd3\xe4\x93\x02O\"M/v2/users/{user_id}/activities/{activity_id}/enrichers/{provider_name}/invoke\x12\xe6\x01\n" +
	"\x19AcceptProposedEnricherRun\x12;.fitglue.services.pipeline.AcceptProposedEnricherRunRequest\x1a-.fitglue.models.activity.StandardizedActivity\"]\x82\xd3\xe4\x93\x02W\"U/v2/users/{user_id}/activities/{activity_id}/proposed-enrichers/{execution_id}/accept\x12\xd2\x01\n" +
	"\x1aDismissProposedEnricherRun\x12<.fitglue.services.pipeline.DismissProposedEnricherRunRequest\x1a\x16.google.protobuf.Empty\"^\x82\xd3\xe4\x93\x02X\"V/v2/users/{user_id}/activities/{activity_id}/proposed-enrichers/{execution_id}/dismiss\x12\x9c\x01\n" +
	"\x0eGetPipelineRun\x120.fitglue.services.pipeline.GetPipelineRunRequest\x1a$.fitglue.models.pipeline.PipelineRun\"2\x82\xd3\xe4\x93\x02,\x12*/v2/users/{user_id}/pipeline-runs/{run_id}\x12\xa6\x01\n" +
	"\x10ListPipelineRuns\x122.fitglue.services.pipeline.ListPipelineRunsRequest\x1a3.fitglue.services.pipeline.ListPipelineRunsResponse\")\x82\xd3\xe4\x93\x02#\x12!/v2/users/{user_id}/pipeline-runs\x12\xab\x01\n" +
	"\x15AdminListPipelineRuns\x127.fitglue.services.pipeline.AdminListPipelineRunsRequest\x1a8.fitglue.services.pipeline.AdminListPipelineRunsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v2/admin/pipeline-runs\x12\xce\x01\n" +
	"\x14ListSourceActivities\x126.fitglue.services.pipeline.ListSourceActivitiesRequest\x1a7.fitglue.services.pipeline.ListSourceActivitiesResponse\"E\x82\xd3\xe4\x93\x02?\x12=/v2/users/{user_id}/pipelines/{pipeline_id}/source-activities\x12\xc2\x01\n" +
	"\x12BackfillActivities\x124.fitglue.services.pipeline.BackfillActivitiesRequest\x1a5.fitglue.services.pipeline.BackfillActivitiesResponse\"?\x82\xd3\xe4\x93\x029:\x01*\"4/v2/users/{user_id}/pipelines/{pipeline_id}/backfillBAZ?github.com/fitglue/server/src/go/pkg/types/pb/services/pipelineb\x06proto3"

var (
	file_services_pipeline_pipeline_proto_rawDescOnce sync.Once
	file_services_pipeline_pipeline_proto_rawDescData []byte
)

func file_services_pipeline_pipeline_proto_rawDescGZIP() []byte {
	file_services_pipeline_pipeline_proto_rawDescOnce.Do(func() {
		file_services_pipeline_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_pipeline_pipeline_proto_rawDesc), len(file_services_pipeline_pipeline_proto_rawDesc)))
	})
	return file_services_pipeline_pipeline_proto_rawDescData
}

var file_services_pipeline_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_services_pipeline_pipeline_proto_goTypes = []any{
	(*AdminListPipelineRunsRequest)(nil),      // 0: fitglue.services.pipeline.AdminListPipelineRunsRequest
	(*AdminListPipelineRunsResponse)(nil),     // 1: fitglue.services.pipeline.AdminListPipelineRunsResponse
	(*ListPipelinesRequest)(nil),              // 2: fitglue.services.pipeline.ListPipelinesRequest
	(*ListPipelinesResponse)(nil),             // 3: fitglue.services.pipeline.ListPipelinesResponse
	(*GetPipelineRequest)(nil),                // 4: fitglue.services.pipeline.GetPipelineRequest
	(*CreatePipelineRequest)(nil),             // 5: fitglue.services.pipeline.CreatePipelineRequest
	(*UpdatePipelineRequest)(nil),             // 6: fitglue.services.pipeline.UpdatePipelineRequest
	(*DeletePipelineRequest)(nil),             // 7: fitglue.services.pipeline.DeletePipelineRequest
	(*SubmitInputRequest)(nil),                // 8: fitglue.services.pipeline.SubmitInputRequest
	(*ListPendingInputsRequest)(nil),          // 9: fitglue.services.pipeline.ListPendingInputsRequest
	(*ListPendingInputsResponse)(nil),         // 10: fitglue.services.pipeline.ListPendingInputsResponse
	(*ResolvePendingInputRequest)(nil),        // 11: fitglue.services.pipeline.ResolvePendingInputRequest
	(*CancelPipelineRequest)(nil),             // 12: fitglue.services.pipeline.CancelPipelineRequest
	(*CancelPipelineRunRequest)(nil),          // 13: fitglue.services.pipeline.CancelPipelineRunRequest
	(*RepostActivityRequest)(nil),             // 14: fitglue.services.pipeline.RepostActivityRequest
	(*RefreshActivitySourceRequest)(nil),      // 15: fitglue.services.pipeline.RefreshActivitySourceRequest
	(*InvokeEnricherRequest)(nil),             // 16: fitglue.services.pipeline.InvokeEnricherRequest
	(*InvokeEnricherResponse)(nil),            // 17: fitglue.services.pipeline.InvokeEnricherResponse
	(*AcceptProposedEnricherRunRequest)(nil),  // 18: fitglue.services.pipeline.AcceptProposedEnricherRunRequest
	(*DismissProposedEnricherRunRequest)(nil), // 19: fitglue.services.pipeline.DismissProposedEnricherRunRequest
	(*GetPipelineRunRequest)(nil),             // 20: fitglue.services.pipeline.GetPipelineRunRequest
	(*ListPipelineRunsRequest)(nil),           // 21: fitglue.services.pipeline.ListPipelineRunsRequest
	(*ListPipelineRunsResponse)(nil),          // 22: fitglue.services.pipeline.ListPipelineRunsResponse
	(*SourceActivityItem)(nil),                // 23: fitglue.services.pipeline.SourceActivityItem
	(*ListSourceActivitiesRequest)(nil),       // 24: fitglue.services.pipeline.ListSourceActivitiesRequest
	(*ListSourceActivitiesResponse)(nil),      // 25: fitglue.services.pipeline.ListSourceActivitiesResponse
	(*BackfillActivitiesRequest)(nil),         // 26: fitglue.services.pipeline.BackfillActivitiesRequest
	(*BackfillActivitiesResponse)(nil),        // 27: fitglue.services.pipeline.BackfillActivitiesResponse
	nil,                                       // 28: fitglue.services.pipeline.SubmitInputRequest.InputDataEntry
	(*pipeline.PipelineRun)(nil),              // 29: fitglue.models.pipeline.PipelineRun
	(*pipeline.PipelineConfig)(nil),           // 30: fitglue.models.pipeline.PipelineConfig
	(*pipeline.PendingInput)(nil),             // 31: fitglue.models.pipeline.PendingInput
	(*activity.EnricherRunLayer)(nil),         // 32: fitglue.models.activity.EnricherRunLayer
	(*activity.StandardizedActivity)(nil),     // 33: fitglue.models.activity.StandardizedActivity
	(*timestamppb.Timestamp)(nil),             // 34: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                     // 35: google.protobuf.Empty
}
var file_services_pipeline_pipeline_proto_depIdxs = []int32{
	29, // 0: fitglue.services.pipeline.AdminListPipelineRunsResponse.runs:type_name -> fitglue.models.pipeline.PipelineRun
	30, // 1: fitglue.services.pipeline.ListPipelinesResponse.pipelines:type_name -> fitglue.models.pipeline.PipelineConfig
	30, // 2: fitglue.services.pipeline.CreatePipelineRequest.pipeline:type_name -> fitglue.models.pipeline.PipelineConfig
	30, // 3: fitglue.services.pipeline.UpdatePipelineRequest.pipeline:type_name -> fitglue.models.pipeline.PipelineConfig
	28, // 4: fitglue.services.pipeline.SubmitInputRequest.input_data:type_name -> fitglue.services.pipeline.SubmitInputRequest.InputDataEntry
	31, // 5: fitglue.services.pipeline.ListPendingInputsResponse.inputs:type_name -> fitglue.models.pipeline.PendingInput
	32, // 6: fitglue.services.pipeline.InvokeEnricherResponse.proposed:type_name -> fitglue.models.activity.EnricherRunLayer
	33, // 7: fitglue.services.pipeline.InvokeEnricherResponse.preview:type_name -> fitglue.models.activity.StandardizedActivity
	34, // 8: fitglue.services.pipeline.ListPipelineRunsRequest.since:type_name -> google.protobuf.Timestamp
	34, // 9: fitglue.services.pipeline.ListPipelineRunsRequest.until:type_name -> google.protobuf.Timestamp
	29, // 10: fitglue.services.pipeline.ListPipelineRunsResponse.runs:type_name -> fitglue.models.pipeline.PipelineRun
	34, // 11: fitglue.services.pipeline.SourceActivityItem.start_time:type_name -> google.protobuf.Timestamp
	23, // 12: fitglue.services.pipeline.ListSourceActivitiesResponse.activities:type_name -> fitglue.services.pipeline.SourceActivityItem
	2,  // 13: fitglue.services.pipeline.PipelineService.ListPipelines:input_type -> fitglue.services.pipeline.ListPipelinesRequest
	4,  // 14: fitglue.services.pipeline.PipelineService.GetPipeline:input_type -> fitglue.services.pipeline.GetPipelineRequest
	5,  // 15: fitglue.services.pipeline.PipelineService.CreatePipeline:input_type -> fitglue.services.pipeline.CreatePipelineRequest
	6,  // 16: fitglue.services.pipeline.PipelineService.UpdatePipeline:input_type -> fitglue.services.pipeline.UpdatePipelineRequest
	7,  // 17: fitglue.services.pipeline.PipelineService.DeletePipeline:input_type -> fitglue.services.pipeline.DeletePipelineRequest
	8,  // 18: fitglue.services.pipeline.PipelineService.SubmitInput:input_type -> fitglue.services.pipeline.SubmitInputRequest
	9,  // 19: fitglue.services.pipeline.PipelineService.ListPendingInputs:input_type -> fitglue.services.pipeline.ListPendingInputsRequest
	11, // 20: fitglue.services.pipeline.PipelineService.ResolvePendingInput:input_type -> fitglue.services.pipeline.ResolvePendingInputRequest
	12, // 21: fitglue.services.pipeline.PipelineService.CancelPipeline:input_type -> fitglue.services.pipeline.CancelPipelineRequest
	13, // 22: fitglue.services.pipeline.PipelineService.CancelPipelineRun:input_type -> fitglue.services.pipeline.CancelPipelineRunRequest
	14, // 23: fitglue.services.pipeline.PipelineService.RepostActivity:input_type -> fitglue.services.pipeline.RepostActivityRequest
	15, // 24: fitglue.services.pipeline.PipelineService.RefreshActivitySource:input_type -> fitglue.services.pipeline.RefreshActivitySourceRequest
	16, // 25: fitglue.services.pipeline.PipelineService.InvokeEnricher:input_type -> fitglue.services.pipeline.InvokeEnricherRequest
	18, // 26: fitglue.services.pipeline.PipelineService.AcceptProposedEnricherRun:input_type -> fitglue.services.pipeline.AcceptProposedEnricherRunRequest
	19, // 27: fitglue.services.pipeline.PipelineService.DismissProposedEnricherRun:input_type -> fitglue.services.pipeline.DismissProposedEnricherRunRequest
	20, // 28: fitglue.services.pipeline.PipelineService.GetPipelineRun:input_type -> fitglue.services.pipeline.GetPipelineRunRequest
	21, // 29: fitglue.services.pipeline.PipelineService.ListPipelineRuns:input_type -> fitglue.services.pipeline.ListPipelineRunsRequest
	0,  // 30: fitglue.services.pipeline.PipelineService.AdminListPipelineRuns:input_type -> fitglue.services.pipeline.AdminListPipelineRunsRequest
	24, // 31: fitglue.services.pipeline.PipelineService.ListSourceActivities:input_type -> fitglue.services.pipeline.ListSourceActivitiesRequest
	26, // 32: fitglue.services.pipeline.PipelineService.BackfillActivities:input_type -> fitglue.services.pipeline.BackfillActivitiesRequest
	3,  // 33: fitglue.services.pipeline.PipelineService.ListPipelines:output_type -> fitglue.services.pipeline.ListPipelinesResponse
	30, // 34: fitglue.services.pipeline.PipelineService.GetPipeline:output_type -> fitglue.models.pipeline.PipelineConfig
	30, // 35: fitglue.services.pipeline.PipelineService.CreatePipeline:output_type -> fitglue.models.pipeline.PipelineConfig
	30, // 36: fitglue.services.pipeline.PipelineService.UpdatePipeline:output_type -> fitglue.models.pipeline.PipelineConfig
	35, // 37: fitglue.services.pipeline.PipelineService.DeletePipeline:output_type -> google.protobuf.Empty
	35, // 38: fitglue.services.pipeline.PipelineService.SubmitInput:output_type -> google.protobuf.Empty
	10, // 39: fitglue.services.pipeline.PipelineService.ListPendingInputs:output_type -> fitglue.services.pipeline.ListPendingInputsResponse
	35, // 40: fitglue.services.pipeline.PipelineService.ResolvePendingInput:output_type -> google.protobuf.Empty
	35, // 41: fitglue.services.pipeline.PipelineService.CancelPipeline:output_type -> google.protobuf.Empty
	35, // 42: fitglue.services.pipeline.PipelineService.CancelPipelineRun:output_type -> google.protobuf.Empty
	35, // 43: fitglue.services.pipeline.PipelineService.RepostActivity:output_type -> google.protobuf.Empty
	33, // 44: fitglue.services.pipeline.PipelineService.RefreshActivitySource:output_type -> fitglue.models.activity.StandardizedActivity
	17, // 45: fitglue.services.pipeline.PipelineService.InvokeEnricher:output_type -> fitglue.services.pipeline.InvokeEnricherResponse
	33, // 46: fitglue.services.pipeline.PipelineService.AcceptProposedEnricherRun:output_type -> fitglue.models.activity.StandardizedActivity
	35, // 47: fitglue.services.pipeline.PipelineService.DismissProposedEnricherRun:output_type -> google.protobuf.Empty
	29, // 48: fitglue.services.pipeline.PipelineService.GetPipelineRun:output_type -> fitglue.models.pipeline.PipelineRun
	22, // 49: fitglue.services.pipeline.PipelineService.ListPipelineRuns:output_type -> fitglue.services.pipeline.ListPipelineRunsResponse
	1,  // 50: fitglue.services.pipeline.PipelineService.AdminListPipelineRuns:output_type -> fitglue.services.pipeline.AdminListPipelineRunsResponse
	25, // 51: fitglue.services.pipeline.PipelineService.ListSourceActivities:output_type -> fitglue.services.pipeline.ListSourceActivitiesResponse
	27, // 52: fitglue.services.pipeline.PipelineService.BackfillActivities:output_type -> fitglue.services.pipeline.BackfillActivitiesResponse
	33, // [33:53] is the sub-list for method output_type
	13, // [13:33] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_services_pipeline_pipeline_proto_init() }
func file_services_pipeline_pipeline_proto_init() {
	if File_services_pipeline_pipeline_proto != nil {
		return
	}
	file_services_pipeline_pipeline_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_pipeline_pipeline_proto_rawDesc), len(file_services_pipeline_pipeline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_pipeline_pipeline_proto_goTypes,
		DependencyIndexes: file_services_pipeline_pipeline_proto_depIdxs,
		MessageInfos:      file_services_pipeline_pipeline_proto_msgTypes,
	}.Build()
	File_services_pipeline_pipeline_proto = out.File
	file_services_pipeline_pipeline_proto_goTypes = nil
	file_services_pipeline_pipeline_proto_depIdxs = nil
}
